wxLua: wxLuaDebuggerEvent Class Reference
wxLuaDebuggerEvent Class Reference
#include <wxldserv.h>
Public Member Functions
wxLuaDebuggerEvent (const wxLuaDebuggerEvent &event)
wxLuaDebuggerEvent (wxEventType eventType=wxEVT_NULL, wxObject *eventObject=NULL, int lineNumber=0, const wxString &fileName=wxEmptyString, bool enabledFlag=false)
void SetMessage (const wxString &message)
void SetDebugData (long nReference, const wxLuaDebugData &pDebugData=wxNullLuaDebugData)
int GetLineNumber () const
wxString GetFileName () const
wxString GetMessage () const
bool HasMessage () const
long GetReference () const
wxLuaDebugData GetDebugData () const
bool GetEnabledFlag () const
Protected Member Functions
virtual wxEvent * Clone () const
Protected Attributes
int m_line_number
wxString m_fileName
wxString m_strMessage
bool m_has_message
long m_lua_ref
wxLuaDebugData m_debugData
bool m_enabled_flag
Detailed Description
Definition at line 382 of file wxldserv.h.
Constructor & Destructor Documentation
wxLuaDebuggerEvent::wxLuaDebuggerEvent (const wxLuaDebuggerEvent & event)
Definition at line 47 of file wxldserv.cpp.
wxLuaDebuggerEvent::wxLuaDebuggerEvent (wxEventType eventType = wxEVT_NULL, wxObject * eventObject = NULL, int lineNumber = 0, const wxString & fileName = wxEmptyString, bool enabledFlag = false)
Definition at line 60 of file wxldserv.cpp.
Member Function Documentation
virtual wxEvent* wxLuaDebuggerEvent::Clone () const [protected, virtual]
Definition at line 404 of file wxldserv.h.
References wxLuaDebuggerEvent.
wxLuaDebugData wxLuaDebuggerEvent::GetDebugData () const
Definition at line 400 of file wxldserv.h.
Referenced by wxLuaDebuggerBase::OnDebugStackEnum().
bool wxLuaDebuggerEvent::GetEnabledFlag () const
Definition at line 401 of file wxldserv.h.
wxString wxLuaDebuggerEvent::GetFileName () const
Definition at line 396 of file wxldserv.h.
int wxLuaDebuggerEvent::GetLineNumber () const
Definition at line 395 of file wxldserv.h.
wxString wxLuaDebuggerEvent::GetMessage () const
Definition at line 397 of file wxldserv.h.
long wxLuaDebuggerEvent::GetReference () const
Definition at line 399 of file wxldserv.h.
Referenced by wxLuaDebuggerBase::OnDebugStackEntryEnum(), and wxLuaDebuggerBase::OnDebugTableEnum().
bool wxLuaDebuggerEvent::HasMessage () const
Definition at line 398 of file wxldserv.h.
void wxLuaDebuggerEvent::SetDebugData (long nReference, const wxLuaDebugData & pDebugData = wxNullLuaDebugData)
Definition at line 81 of file wxldserv.cpp.
References m_debugData, and m_lua_ref.
Referenced by wxLuaDebuggerBase::HandleDebuggeeEvent().
void wxLuaDebuggerEvent::SetMessage (const wxString & message)
Definition at line 75 of file wxldserv.cpp.
References m_has_message, and m_strMessage.
Referenced by wxLuaDebuggerBase::CheckSocketConnected(), wxLuaDebuggerBase::CheckSocketRead(), wxLuaDebuggerBase::CheckSocketWrite(), wxLuaDebuggerBase::HandleDebuggeeEvent(), wxLuaDebuggerBase::OnEndDebugeeProcess(), wxLuaDebuggerCServer::StartServer(), wxLuaDebuggerCServer::StopServer(), and wxLuaDebuggerCServer::ThreadFunction().
Member Data Documentation
wxLuaDebugData wxLuaDebuggerEvent::m_debugData [protected]
Definition at line 411 of file wxldserv.h.
Referenced by SetDebugData().
bool wxLuaDebuggerEvent::m_enabled_flag [protected]
Definition at line 412 of file wxldserv.h.
wxString wxLuaDebuggerEvent::m_fileName [protected]
Definition at line 407 of file wxldserv.h.
bool wxLuaDebuggerEvent::m_has_message [protected]
Definition at line 409 of file wxldserv.h.
Referenced by SetMessage().
int wxLuaDebuggerEvent::m_line_number [protected]
Definition at line 406 of file wxldserv.h.
long wxLuaDebuggerEvent::m_lua_ref [protected]
Definition at line 410 of file wxldserv.h.
Referenced by SetDebugData().
wxString wxLuaDebuggerEvent::m_strMessage [protected]
Definition at line 408 of file wxldserv.h.
Referenced by SetMessage().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluasocket/include/wxldserv.h
/mnt/share/devel/lua/wxLua/modules/wxluasocket/src/wxldserv.cpp