wxLua: wxLuaStackListCtrl Class Reference
wxLuaStackListCtrl Class Reference
Public Member Functions
wxLuaStackListCtrl (wxLuaStackDialog *stkDialog, wxWindow *parent, wxWindowID winid=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxLC_REPORT, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxT("wxLuaStackListCtrl"))
virtual wxString OnGetItemText (long item, long column) const
virtual int OnGetItemImage (long item) const
virtual int OnGetItemColumnImage (long item, long column) const
virtual wxListItemAttr * OnGetItemAttr (long item) const
Public Attributes
wxListItemAttr m_itemAttr
wxLuaStackDialog * m_stkDlg
Detailed Description
Definition at line 48 of file wxlstack.cpp.
Constructor & Destructor Documentation
wxLuaStackListCtrl::wxLuaStackListCtrl (wxLuaStackDialog * stkDialog, wxWindow * parent, wxWindowID winid = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxLC_REPORT, const wxValidator & validator = wxDefaultValidator, const wxString & name = wxT("wxLuaStackListCtrl"))
Definition at line 51 of file wxlstack.cpp.
References m_stkDlg.
Member Function Documentation
wxListItemAttr * wxLuaStackListCtrl::OnGetItemAttr (long item) const [virtual]
Definition at line 119 of file wxlstack.cpp.
References wxLuaStackListData::GetDebugItem(), wxLuaStackDialog::GetItemImage(), m_itemAttr, wxLuaStackDialog::m_listData, m_stkDlg, and wxLuaStackDialog::m_typeColours.
int wxLuaStackListCtrl::OnGetItemColumnImage (long item, long column) const [virtual]
Definition at line 82 of file wxlstack.cpp.
References wxLuaStackListData::GetDebugItem(), wxLuaDebugItem::GetFlagBit(), wxLuaStackDialog::GetItemImage(), wxLuaStackDialog::IMG_TABLE, wxLuaStackDialog::IMG_TABLE_OPEN, wxLuaStackDialog::LIST_COL_KEY, wxLuaStackDialog::LIST_COL_KEY_TYPE, wxLuaStackDialog::LIST_COL_VALUE_TYPE, wxLuaStackDialog::m_listData, m_stkDlg, WXLUA_DEBUGITEM_EXPANDED, WXLUA_DEBUGITEM_KEY_REF, and WXLUA_DEBUGITEM_VALUE_REF.
int wxLuaStackListCtrl::OnGetItemImage (long item) const [virtual]
Definition at line 78 of file wxlstack.cpp.
wxString wxLuaStackListCtrl::OnGetItemText (long item, long column) const [virtual]
Definition at line 74 of file wxlstack.cpp.
References wxLuaStackDialog::GetItemText(), and m_stkDlg.
Member Data Documentation
wxListItemAttr wxLuaStackListCtrl::m_itemAttr
Definition at line 69 of file wxlstack.cpp.
Referenced by OnGetItemAttr().
wxLuaStackDialog* wxLuaStackListCtrl::m_stkDlg
Definition at line 70 of file wxlstack.cpp.
Referenced by OnGetItemAttr(), OnGetItemColumnImage(), OnGetItemText(), and wxLuaStackListCtrl().
The documentation for this class was generated from the following file:
/mnt/share/devel/lua/wxLua/modules/wxluadebug/src/wxlstack.cpp