wxLua: wxLuaObject Class Reference
wxLuaObject Class Reference
#include <wxlbind.h>
Public Member Functions
wxLuaObject (const wxLuaState &wxlState, int stack_idx)
virtual ~wxLuaObject ()
bool GetObject ()
void SetObject (int stack_idx)
bool * GetBoolPtr ()
int * GetIntPtr ()
wxString * GetStringPtr ()
wxArrayInt * GetArrayPtr ()
wxLuaObject_Type GetAllocationFlag () const
wxLuaState GetwxLuaState () const
Protected Attributes
wxLuaState * m_wxlState
int m_reference
wxLuaObject_Type m_alloc_flag
union {
bool m_bool
int m_int
wxString * m_string
wxArrayInt * m_arrayInt
};
Detailed Description
Definition at line 293 of file wxlbind.h.
Constructor & Destructor Documentation
wxLuaObject::wxLuaObject (const wxLuaState & wxlState, int stack_idx)
Definition at line 65 of file wxlbind.cpp.
References wxlua_lreg_refs_key.
wxLuaObject::~wxLuaObject () [virtual]
Definition at line 75 of file wxlbind.cpp.
References wxLuaState::IsClosing(), m_alloc_flag, m_arrayInt, m_reference, m_string, m_wxlState, wxLuaState::Ok(), wxlua_lreg_refs_key, wxLUAOBJECT_ARRAYINT, wxLUAOBJECT_STRING, and wxLuaState::wxluaR_Unref().
Member Function Documentation
wxLuaObject_Type wxLuaObject::GetAllocationFlag () const
Definition at line 325 of file wxlbind.h.
wxArrayInt * wxLuaObject::GetArrayPtr ()
Definition at line 180 of file wxlbind.cpp.
References GetObject(), wxLuaState::GetwxArrayInt(), wxLuaState::lua_Pop(), m_alloc_flag, m_arrayInt, m_reference, m_wxlState, wxLuaState::Ok(), wxLUAOBJECT_ARRAYINT, and wxLUAOBJECT_NONE.
bool * wxLuaObject::GetBoolPtr ()
Definition at line 135 of file wxlbind.cpp.
References GetObject(), wxLuaState::lua_Pop(), wxLuaState::lua_ToBoolean(), m_alloc_flag, m_bool, m_reference, m_wxlState, wxLuaState::Ok(), wxLUAOBJECT_BOOL, and wxLUAOBJECT_NONE.
int * wxLuaObject::GetIntPtr ()
Definition at line 149 of file wxlbind.cpp.
References GetObject(), wxLuaState::lua_Pop(), wxLuaState::lua_ToNumber(), m_alloc_flag, m_int, m_reference, m_wxlState, wxLuaState::Ok(), wxLUAOBJECT_INT, and wxLUAOBJECT_NONE.
bool wxLuaObject::GetObject ()
Definition at line 94 of file wxlbind.cpp.
References wxLuaState::GetLuaState(), m_alloc_flag, m_arrayInt, m_bool, m_int, m_reference, m_string, m_wxlState, wxLuaState::Ok(), wx2lua(), wxlua_lreg_refs_key, wxlua_pushwxArrayInttable(), wxLUAOBJECT_ARRAYINT, wxLUAOBJECT_BOOL, wxLUAOBJECT_INT, wxLUAOBJECT_STRING, and wxluaR_getref().
Referenced by GetArrayPtr(), GetBoolPtr(), GetIntPtr(), GetStringPtr(), and wxlua_hasderivedmethod().
wxString * wxLuaObject::GetStringPtr ()
Definition at line 163 of file wxlbind.cpp.
References GetObject(), wxLuaState::lua_Pop(), wxLuaState::lua_TowxString(), m_alloc_flag, m_reference, m_string, m_wxlState, wxLuaState::Ok(), wxLUAOBJECT_NONE, and wxLUAOBJECT_STRING.
wxLuaState wxLuaObject::GetwxLuaState () const
Definition at line 89 of file wxlbind.cpp.
References m_wxlState, and wxNullLuaState.
void wxLuaObject::SetObject (int stack_idx)
Definition at line 125 of file wxlbind.cpp.
References m_reference, m_wxlState, wxLuaState::Ok(), wxlua_lreg_refs_key, wxLuaState::wxluaR_Ref(), and wxLuaState::wxluaR_Unref().
Member Data Documentation
union { ... } [protected]
wxLuaObject_Type wxLuaObject::m_alloc_flag [protected]
Definition at line 333 of file wxlbind.h.
Referenced by GetArrayPtr(), GetBoolPtr(), GetIntPtr(), GetObject(), GetStringPtr(), and ~wxLuaObject().
wxArrayInt* wxLuaObject::m_arrayInt
Definition at line 340 of file wxlbind.h.
Referenced by GetArrayPtr(), GetObject(), and ~wxLuaObject().
bool wxLuaObject::m_bool
Definition at line 337 of file wxlbind.h.
Referenced by GetBoolPtr(), and GetObject().
int wxLuaObject::m_int
Definition at line 338 of file wxlbind.h.
Referenced by GetIntPtr(), and GetObject().
int wxLuaObject::m_reference [protected]
Definition at line 331 of file wxlbind.h.
Referenced by GetArrayPtr(), GetBoolPtr(), GetIntPtr(), GetObject(), GetStringPtr(), SetObject(), and ~wxLuaObject().
wxString* wxLuaObject::m_string
Definition at line 339 of file wxlbind.h.
Referenced by GetObject(), GetStringPtr(), and ~wxLuaObject().
wxLuaState* wxLuaObject::m_wxlState [protected]
Definition at line 330 of file wxlbind.h.
Referenced by GetArrayPtr(), GetBoolPtr(), GetIntPtr(), GetObject(), GetStringPtr(), GetwxLuaState(), SetObject(), and ~wxLuaObject().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxlua/include/wxlbind.h
/mnt/share/devel/lua/wxLua/modules/wxlua/src/wxlbind.cpp