wxLua: wxLuaCheckStack Class Reference
wxLuaCheckStack Class Reference
#include <wxldebug.h>
Public Member Functions
wxLuaCheckStack (lua_State *L, const wxString &msg=wxEmptyString, bool print_to_console=true)
~wxLuaCheckStack ()
wxString TestStack (const wxString &msg=wxEmptyString)
wxString DumpStack (const wxString &msg=wxEmptyString)
wxString DumpGlobals (const wxString &msg=wxEmptyString)
wxString DumpTable (const wxString &tableName, const wxString &msg=wxEmptyString)
wxString DumpTable (int stack_idx, const wxString &msg=wxEmptyString)
wxString DumpTable (int stack_idx, const wxString &tablename, const wxString &msg, wxSortedArrayString &tableArray, int indent)
void OutputMsg (const wxString &msg) const
Public Attributes
lua_State * m_luaState
wxString m_msg
int m_top
bool m_print_to_console
Detailed Description
Definition at line 186 of file wxldebug.h.
Constructor & Destructor Documentation
wxLuaCheckStack::wxLuaCheckStack (lua_State * L, const wxString & msg = wxEmptyString, bool print_to_console = true)
Definition at line 672 of file wxldebug.cpp.
References m_luaState, m_msg, m_print_to_console, and m_top.
wxLuaCheckStack::~wxLuaCheckStack ()
Definition at line 680 of file wxldebug.cpp.
References m_print_to_console, and TestStack().
Member Function Documentation
wxString wxLuaCheckStack::DumpGlobals (const wxString & msg = wxEmptyString)
Definition at line 729 of file wxldebug.cpp.
References DumpTable(), and m_luaState.
wxString wxLuaCheckStack::DumpStack (const wxString & msg = wxEmptyString)
Definition at line 699 of file wxldebug.cpp.
References wxLuaDebugData::GetTypeValue(), m_luaState, m_msg, m_top, OutputMsg(), and wxluaT_typename().
wxString wxLuaCheckStack::DumpTable (int stack_idx, const wxString & tablename, const wxString & msg, wxSortedArrayString & tableArray, int indent)
Definition at line 782 of file wxldebug.cpp.
References DumpTable(), wxLuaDebugData::GetTypeValue(), m_luaState, OutputMsg(), WXLUA_TTABLE, and wxluaT_typename().
wxString wxLuaCheckStack::DumpTable (int stack_idx, const wxString & msg = wxEmptyString)
Definition at line 773 of file wxldebug.cpp.
References DumpTable(), and m_luaState.
wxString wxLuaCheckStack::DumpTable (const wxString & tableName, const wxString & msg = wxEmptyString)
Definition at line 738 of file wxldebug.cpp.
References m_luaState, OutputMsg(), and wx2lua().
Referenced by DumpGlobals(), and DumpTable().
void wxLuaCheckStack::OutputMsg (const wxString & msg) const
Definition at line 858 of file wxldebug.cpp.
References m_print_to_console.
Referenced by DumpStack(), DumpTable(), and TestStack().
wxString wxLuaCheckStack::TestStack (const wxString & msg = wxEmptyString)
Definition at line 686 of file wxldebug.cpp.
References m_luaState, m_msg, m_top, and OutputMsg().
Referenced by ~wxLuaCheckStack().
Member Data Documentation
lua_State* wxLuaCheckStack::m_luaState
Definition at line 221 of file wxldebug.h.
Referenced by DumpGlobals(), DumpStack(), DumpTable(), TestStack(), and wxLuaCheckStack().
wxString wxLuaCheckStack::m_msg
Definition at line 222 of file wxldebug.h.
Referenced by DumpStack(), TestStack(), and wxLuaCheckStack().
bool wxLuaCheckStack::m_print_to_console
Definition at line 224 of file wxldebug.h.
Referenced by OutputMsg(), wxLuaCheckStack(), and ~wxLuaCheckStack().
int wxLuaCheckStack::m_top
Definition at line 223 of file wxldebug.h.
Referenced by DumpStack(), TestStack(), and wxLuaCheckStack().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluadebug/include/wxldebug.h
/mnt/share/devel/lua/wxLua/modules/wxluadebug/src/wxldebug.cpp