wxLua: wxLuaStackListData Class Reference
wxLuaStackListData Class Reference
#include <wxlstack.h>
Public Member Functions
wxLuaStackListData (int item_idx, int level, const wxLuaDebugData &parentDebugData, const wxLuaDebugData &childrenDebugData=wxNullLuaDebugData)
wxLuaDebugItem * GetDebugItem ()
Public Attributes
int m_item_idx
int m_level
wxLuaDebugData m_parentDebugData
wxLuaDebugData m_childrenDebugData
wxTreeItemId m_treeId
Detailed Description
Definition at line 68 of file wxlstack.h.
Constructor & Destructor Documentation
wxLuaStackListData::wxLuaStackListData (int item_idx, int level, const wxLuaDebugData & parentDebugData, const wxLuaDebugData & childrenDebugData = wxNullLuaDebugData)
Definition at line 71 of file wxlstack.h.
Member Function Documentation
wxLuaDebugItem* wxLuaStackListData::GetDebugItem ()
Definition at line 78 of file wxlstack.h.
Referenced by wxLuaStackDialog::CollapseItem(), wxLuaStackDialog::ExpandItem(), wxLuaStackDialog::ExpandItemChildren(), wxLuaStackDialog::GetItemText(), wxLuaStackListCtrl::OnGetItemAttr(), wxLuaStackListCtrl::OnGetItemColumnImage(), and wxLuaStackDialog::OnListItem().
Member Data Documentation
wxLuaDebugData wxLuaStackListData::m_childrenDebugData
Definition at line 83 of file wxlstack.h.
Referenced by wxLuaStackDialog::CollapseItem(), wxLuaStackDialog::ExpandItem(), wxLuaStackDialog::FillTableEntry(), and wxLuaStackDialog::FindListItem().
int wxLuaStackListData::m_item_idx
Definition at line 80 of file wxlstack.h.
Referenced by wxLuaStackDialog::GetItemText().
int wxLuaStackListData::m_level
Definition at line 81 of file wxlstack.h.
Referenced by wxLuaStackDialog::ExpandItemChildren(), wxLuaStackDialog::FillTableEntry(), and wxLuaStackDialog::GetItemText().
wxLuaDebugData wxLuaStackListData::m_parentDebugData
Definition at line 82 of file wxlstack.h.
Referenced by wxLuaStackDialog::CollapseItem(), and wxLuaStackDialog::FindListItem().
wxTreeItemId wxLuaStackListData::m_treeId
Definition at line 84 of file wxlstack.h.
Referenced by wxLuaStackDialog::CollapseItem(), wxLuaStackDialog::FillTableEntry(), and wxLuaStackDialog::OnListItem().
The documentation for this class was generated from the following file:
/mnt/share/devel/lua/wxLua/modules/wxluadebug/include/wxlstack.h