wxLua: wxLuaSocketBase Class Reference
wxLuaSocketBase Class Reference
#include <wxlsock.h>
Public Member Functions
wxLuaSocketBase ()
virtual ~wxLuaSocketBase ()
int GetPortNumber () const
wxString GetAddress () const
virtual bool IsConnected ()=0
virtual int Read (char *buffer, wxUint32 length)=0
virtual int Write (const char *buffer, wxUint32 length)=0
bool ReadCmd (unsigned char &value)
bool ReadInt32 (wxInt32 &value)
bool ReadLong (long &value)
bool ReadString (wxString &value)
bool ReadDebugData (wxLuaDebugData &data)
bool WriteCmd (char value)
bool WriteInt32 (wxInt32 value)
bool WriteLong (long value)
bool WriteString (const wxString &value)
bool WriteDebugData (const wxLuaDebugData &debugData)
virtual wxString GetErrorMsg (bool clear_msg)
void AddErrorMessage (const wxString &msg)
virtual wxString GetLastErrorMsg () const =0
Public Attributes
wxString m_name
wxString m_errorMsg
wxString m_address
int m_port_number
Private Member Functions
DECLARE_ABSTRACT_CLASS (wxLuaSocketBase)
Detailed Description
Definition at line 55 of file wxlsock.h.
Constructor & Destructor Documentation
wxLuaSocketBase::wxLuaSocketBase ()
Definition at line 58 of file wxlsock.h.
virtual wxLuaSocketBase::~wxLuaSocketBase () [virtual]
Definition at line 59 of file wxlsock.h.
Member Function Documentation
void wxLuaSocketBase::AddErrorMessage (const wxString & msg)
Definition at line 317 of file wxlsock.cpp.
References GetLastErrorMsg(), m_address, m_errorMsg, and m_port_number.
Referenced by wxLuaCSocket::Accept(), wxLuaCSocket::Close(), wxLuaCSocket::Connect(), wxLuaCSocket::Listen(), wxLuawxSocket::Read(), wxLuaCSocket::Read(), wxLuawxSocket::Write(), and wxLuaCSocket::Write().
wxLuaSocketBase::DECLARE_ABSTRACT_CLASS (wxLuaSocketBase) [private]
wxString wxLuaSocketBase::GetAddress () const
Definition at line 64 of file wxlsock.h.
wxString wxLuaSocketBase::GetErrorMsg (bool clear_msg) [virtual]
Definition at line 308 of file wxlsock.cpp.
References m_errorMsg.
Referenced by wxLuaDebuggerCServer::GetSocketErrorMsg(), wxLuaDebuggerCServer::StartServer(), wxLuaDebuggerCServer::StopServer(), and wxLuaDebuggerCServer::ThreadFunction().
virtual wxString wxLuaSocketBase::GetLastErrorMsg () const [pure virtual]
Implemented in wxLuaCSocket, and wxLuawxSocket.
Referenced by AddErrorMessage().
int wxLuaSocketBase::GetPortNumber () const
Definition at line 62 of file wxlsock.h.
virtual bool wxLuaSocketBase::IsConnected () [pure virtual]
Implemented in wxLuaCSocket, and wxLuawxSocket.
virtual int wxLuaSocketBase::Read (char * buffer, wxUint32 length) [pure virtual]
Implemented in wxLuaCSocket, and wxLuawxSocket.
Referenced by ReadCmd(), ReadDebugData(), ReadInt32(), ReadLong(), and ReadString().
bool wxLuaSocketBase::ReadCmd (unsigned char & value)
Definition at line 105 of file wxlsock.cpp.
References m_name, Read(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::ThreadFunction(), and wxLuaDebuggerCServer::ThreadFunction().
bool wxLuaSocketBase::ReadDebugData (wxLuaDebugData & data)
Definition at line 153 of file wxlsock.cpp.
References wxLuaDebugData::Add(), lua2wx(), m_name, Read(), ReadInt32(), and wxLuaSocketDebugMsg.
bool wxLuaSocketBase::ReadInt32 (wxInt32 & value)
Definition at line 113 of file wxlsock.cpp.
References m_name, Read(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::HandleDebuggerCmd(), and ReadDebugData().
bool wxLuaSocketBase::ReadLong (long & value)
Definition at line 121 of file wxlsock.cpp.
References lua2wx(), m_name, Read(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::HandleDebuggerCmd().
bool wxLuaSocketBase::ReadString (wxString & value)
Definition at line 132 of file wxlsock.cpp.
References lua2wx(), m_name, Read(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::HandleDebuggerCmd().
virtual int wxLuaSocketBase::Write (const char * buffer, wxUint32 length) [pure virtual]
Implemented in wxLuaCSocket, and wxLuawxSocket.
Referenced by WriteCmd(), WriteDebugData(), WriteInt32(), WriteLong(), and WriteString().
bool wxLuaSocketBase::WriteCmd (char value)
Definition at line 211 of file wxlsock.cpp.
References m_name, Write(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::NotifyBreak(), wxLuaDebugTarget::NotifyError(), wxLuaDebugTarget::NotifyEvaluateExpr(), wxLuaDebugTarget::NotifyExit(), wxLuaDebugTarget::NotifyPrint(), wxLuaDebugTarget::NotifyStackEntryEnumeration(), wxLuaDebugTarget::NotifyStackEnumeration(), and wxLuaDebugTarget::NotifyTableEnumeration().
bool wxLuaSocketBase::WriteDebugData (const wxLuaDebugData & debugData)
Definition at line 242 of file wxlsock.cpp.
References wxLuaDebugData::GetCount(), wxLuaDebugItem::GetFlag(), wxLuaDebugItem::GetIndex(), wxLuaDebugItem::GetKey(), wxLuaDebugItem::GetKeyType(), wxLuaDebugItem::GetRef(), wxLuaDebugItem::GetSource(), wxLuaDebugItem::GetValue(), wxLuaDebugItem::GetValueType(), wxLuaDebugData::Item(), m_name, Write(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::NotifyStackEntryEnumeration(), wxLuaDebugTarget::NotifyStackEnumeration(), and wxLuaDebugTarget::NotifyTableEnumeration().
bool wxLuaSocketBase::WriteInt32 (wxInt32 value)
Definition at line 216 of file wxlsock.cpp.
References m_name, Write(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::NotifyBreak(), wxLuaDebugTarget::NotifyEvaluateExpr(), and wxLuaDebugTarget::NotifyStackEntryEnumeration().
bool wxLuaSocketBase::WriteLong (long value)
Definition at line 221 of file wxlsock.cpp.
References m_name, Write(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::NotifyTableEnumeration().
bool wxLuaSocketBase::WriteString (const wxString & value)
Definition at line 229 of file wxlsock.cpp.
References wxLuaCharBuffer::GetData(), wxLuaCharBuffer::Length(), m_name, Write(), and wxLuaSocketDebugMsg.
Referenced by wxLuaDebugTarget::NotifyBreak(), wxLuaDebugTarget::NotifyError(), wxLuaDebugTarget::NotifyEvaluateExpr(), and wxLuaDebugTarget::NotifyPrint().
Member Data Documentation
wxString wxLuaSocketBase::m_address
Definition at line 105 of file wxlsock.h.
Referenced by AddErrorMessage(), wxLuaCSocket::Connect(), and wxLuaCSocket::wxLuaCSocket().
wxString wxLuaSocketBase::m_errorMsg
Definition at line 104 of file wxlsock.h.
Referenced by AddErrorMessage(), and GetErrorMsg().
wxString wxLuaSocketBase::m_name
Definition at line 103 of file wxlsock.h.
Referenced by ReadCmd(), ReadDebugData(), ReadInt32(), ReadLong(), ReadString(), wxLuaDebuggerCServer::StartServer(), wxLuaDebuggerCServer::StopServer(), wxLuaDebuggerCServer::ThreadFunction(), WriteCmd(), WriteDebugData(), WriteInt32(), WriteLong(), WriteString(), and wxLuaDebugTarget::wxLuaDebugTarget().
int wxLuaSocketBase::m_port_number
Definition at line 106 of file wxlsock.h.
Referenced by AddErrorMessage(), wxLuaCSocket::Connect(), wxLuaCSocket::Listen(), and wxLuaCSocket::wxLuaCSocket().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluasocket/include/wxlsock.h
/mnt/share/devel/lua/wxLua/modules/wxluasocket/src/wxlsock.cpp