wxLua: wxLuaStackDialog Class Reference
wxLuaStackDialog Class Reference
#include <wxlstack.h>
Public Types
enum {
IMG_UNKNOWN, IMG_NONE, IMG_NIL, IMG_BOOLEAN,
IMG_LIGHTUSERDATA, IMG_NUMBER, IMG_STRING, IMG_TABLE,
IMG_LUAFUNCTION, IMG_USERDATA, IMG_THREAD, IMG_INTEGER,
IMG_CFUNCTION, IMG_TABLE_OPEN, IMG__COUNT
}
enum {
LIST_COL_KEY, LIST_COL_LEVEL, LIST_COL_KEY_TYPE, LIST_COL_VALUE_TYPE,
LIST_COL_VALUE
}
Public Member Functions
wxLuaStackDialog ()
wxLuaStackDialog (const wxLuaState &wxlState, wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("wxLua Stack"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~wxLuaStackDialog ()
bool Create (const wxLuaState &wxlState, wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("wxLua Stack"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual wxBitmap CreateBmpString (const wxBitmap &bmp, const wxString &s)
virtual int GetItemImage (const wxLuaDebugItem *dbgItem)
virtual wxString GetItemText (long item, long column, bool exact_value=false)
virtual void EnumerateStack ()
virtual void EnumerateStackEntry (int nEntry)
virtual void EnumerateTable (int nRef, int nEntry, long lc_item)
virtual void EnumerateGlobalData (long lc_item)
void FillStackCombobox (const wxLuaDebugData &debugData)
void FillStackEntry (int nEntry, const wxLuaDebugData &debugData)
void FillTableEntry (long lc_item, const wxLuaDebugData &debugData)
void BeginBatch ()
void EndBatch ()
long FindListItem (wxLuaStackListData *stkListData, bool get_parent=false) const
void OnExpandButton (wxCommandEvent &event)
void OnMenu (wxCommandEvent &event)
void OnFind (wxCommandEvent &event)
void OnSelectStack (wxCommandEvent &event)
void SelectStack (int stack_sel)
void OnTreeItem (wxTreeEvent &event)
void OnListItem (wxListEvent &event)
void OnListRightClick (wxListEvent &event)
bool ExpandItem (long lc_item)
bool ExpandItemChildren (long lc_item)
bool CollapseItem (long lc_item)
void SetShowDuplicateExpandMessage (bool show)
void DeleteAllListItemData ()
void RemoveAllLuaReferences ()
Public Attributes
wxSplitterWindow * m_splitterWin
wxListCtrl * m_listCtrl
wxTreeCtrl * m_treeCtrl
wxMenu * m_listMenu
wxChoice * m_stackChoice
int m_stack_sel
wxArrayInt m_stackEntries
wxComboBox * m_findComboBox
wxMenu * m_findMenu
wxLuaState m_wxlState
wxArrayInt m_luaReferences
wxImageList * m_imageList
wxColour m_typeColours [IMG__COUNT]
int m_img_font_size
bool m_show_dup_expand_msg
int m_batch_count
wxLongToLongHashMap m_expandedItems
wxArrayPtrVoid m_listData
Static Public Attributes
static wxSize m_defaultSize
Private Member Functions
void Init ()
Detailed Description
Definition at line 103 of file wxlstack.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
IMG_UNKNOWN
IMG_NONE
IMG_NIL
IMG_BOOLEAN
IMG_LIGHTUSERDATA
IMG_NUMBER
IMG_STRING
IMG_TABLE
IMG_LUAFUNCTION
IMG_USERDATA
IMG_THREAD
IMG_INTEGER
IMG_CFUNCTION
IMG_TABLE_OPEN
IMG__COUNT
Definition at line 127 of file wxlstack.h.
anonymous enum
Enumerator:
LIST_COL_KEY
LIST_COL_LEVEL
LIST_COL_KEY_TYPE
LIST_COL_VALUE_TYPE
LIST_COL_VALUE
Definition at line 148 of file wxlstack.h.
Constructor & Destructor Documentation
wxLuaStackDialog::wxLuaStackDialog ()
Definition at line 106 of file wxlstack.h.
wxLuaStackDialog::wxLuaStackDialog (const wxLuaState & wxlState, wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxT("wxLua Stack"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Definition at line 108 of file wxlstack.h.
wxLuaStackDialog::~wxLuaStackDialog () [virtual]
Definition at line 381 of file wxlstack.cpp.
References DeleteAllListItemData(), m_defaultSize, m_findMenu, m_imageList, m_listCtrl, m_listMenu, m_treeCtrl, and RemoveAllLuaReferences().
Member Function Documentation
void wxLuaStackDialog::BeginBatch ()
Definition at line 694 of file wxlstack.cpp.
References m_batch_count, m_listCtrl, and m_treeCtrl.
Referenced by CollapseItem(), ExpandItemChildren(), and FillTableEntry().
bool wxLuaStackDialog::CollapseItem (long lc_item)
Definition at line 1132 of file wxlstack.cpp.
References BeginBatch(), DUMMY_TREEITEM, EndBatch(), wxLuaStackListData::GetDebugItem(), wxLuaDebugItem::GetFlagBit(), wxLuaDebugItem::GetRefPtr(), wxLuaStackListData::m_childrenDebugData, m_expandedItems, m_listCtrl, m_listData, wxLuaStackListData::m_parentDebugData, m_treeCtrl, wxLuaStackListData::m_treeId, wxLuaDebugData::Ok(), wxLuaDebugItem::SetFlagBit(), and WXLUA_DEBUGITEM_EXPANDED.
Referenced by OnExpandButton(), OnListItem(), and OnTreeItem().
bool wxLuaStackDialog::Create (const wxLuaState & wxlState, wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxT("wxLua Stack"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Definition at line 184 of file wxlstack.cpp.
References CreateBmpString(), EnumerateStack(), ID_WXLUA_STACK_CHOICE, ID_WXLUA_STACK_COLLAPSE_BUTTON, ID_WXLUA_STACK_EXPAND_BUTTON, ID_WXLUA_STACK_FIND_COMBO, ID_WXLUA_STACK_FINDMENU_ALL, ID_WXLUA_STACK_FINDMENU_BUTTON, ID_WXLUA_STACK_FINDMENU_CASE, ID_WXLUA_STACK_FINDMENU_KEYTYPE, ID_WXLUA_STACK_FINDMENU_LEVEL, ID_WXLUA_STACK_FINDMENU_NAME, ID_WXLUA_STACK_FINDMENU_VALUE, ID_WXLUA_STACK_FINDMENU_VALUETYPE, ID_WXLUA_STACK_FINDMENU_WHOLE_STRING, ID_WXLUA_STACK_FINDNEXT_BUTTON, ID_WXLUA_STACK_FINDPREV_BUTTON, ID_WXLUA_STACK_LISTCTRL, ID_WXLUA_STACK_LISTMENU_COPY0, ID_WXLUA_STACK_LISTMENU_COPY1, ID_WXLUA_STACK_LISTMENU_COPY2, ID_WXLUA_STACK_LISTMENU_COPY3, ID_WXLUA_STACK_LISTMENU_COPY4, ID_WXLUA_STACK_SPLITTERWIN, ID_WXLUA_STACK_TREECTRL, IMG_BOOLEAN, IMG_CFUNCTION, IMG_INTEGER, IMG_LIGHTUSERDATA, IMG_LUAFUNCTION, IMG_NIL, IMG_NONE, IMG_NUMBER, IMG_STRING, IMG_TABLE, IMG_TABLE_OPEN, IMG_THREAD, IMG_UNKNOWN, IMG_USERDATA, LIST_COL_KEY, LIST_COL_KEY_TYPE, LIST_COL_LEVEL, LIST_COL_VALUE, LIST_COL_VALUE_TYPE, m_defaultSize, m_findComboBox, m_findMenu, m_imageList, m_listCtrl, m_listMenu, m_splitterWin, m_stackChoice, m_treeCtrl, m_typeColours, m_wxlState, and wxSplitterWindow.
wxBitmap wxLuaStackDialog::CreateBmpString (const wxBitmap & bmp, const wxString & s) [virtual]
Definition at line 397 of file wxlstack.cpp.
References m_img_font_size.
Referenced by Create().
void wxLuaStackDialog::DeleteAllListItemData ()
Definition at line 1209 of file wxlstack.cpp.
References m_expandedItems, and m_listData.
Referenced by FillStackEntry(), and ~wxLuaStackDialog().
void wxLuaStackDialog::EndBatch ()
Definition at line 705 of file wxlstack.cpp.
References m_batch_count, m_listCtrl, and m_treeCtrl.
Referenced by CollapseItem(), ExpandItemChildren(), and FillTableEntry().
void wxLuaStackDialog::EnumerateGlobalData (long lc_item) [virtual]
Reimplemented in wxLuaDebuggerStackDialog.
Definition at line 531 of file wxlstack.cpp.
References wxLuaDebugData::EnumerateTable(), FillTableEntry(), m_luaReferences, m_wxlState, and wxLuaState::Ok().
Referenced by FillStackEntry().
void wxLuaStackDialog::EnumerateStack () [virtual]
Reimplemented in wxLuaDebuggerStackDialog.
Definition at line 507 of file wxlstack.cpp.
References wxLuaDebugData::EnumerateStack(), FillStackCombobox(), m_wxlState, and wxLuaState::Ok().
Referenced by Create().
void wxLuaStackDialog::EnumerateStackEntry (int nEntry) [virtual]
Reimplemented in wxLuaDebuggerStackDialog.
Definition at line 515 of file wxlstack.cpp.
References wxLuaDebugData::EnumerateStackEntry(), FillStackEntry(), m_luaReferences, m_wxlState, and wxLuaState::Ok().
Referenced by SelectStack().
void wxLuaStackDialog::EnumerateTable (int nRef, int nEntry, long lc_item) [virtual]
Reimplemented in wxLuaDebuggerStackDialog.
Definition at line 523 of file wxlstack.cpp.
References wxLuaDebugData::EnumerateTable(), FillTableEntry(), m_luaReferences, m_wxlState, and wxLuaState::Ok().
Referenced by ExpandItem().
bool wxLuaStackDialog::ExpandItem (long lc_item)
Definition at line 1009 of file wxlstack.cpp.
References EnumerateTable(), FillTableEntry(), wxLuaStackListData::GetDebugItem(), wxLuaDebugItem::GetFlagBit(), wxLuaDebugItem::GetIndex(), wxLuaDebugItem::GetRef(), wxLuaDebugItem::GetRefPtr(), wxLuaStackListData::m_childrenDebugData, m_expandedItems, m_listCtrl, m_listData, m_show_dup_expand_msg, wxLuaDebugData::Ok(), wxLuaDebugItem::SetFlagBit(), and WXLUA_DEBUGITEM_EXPANDED.
Referenced by ExpandItemChildren(), OnListItem(), and OnTreeItem().
bool wxLuaStackDialog::ExpandItemChildren (long lc_item)
Definition at line 1081 of file wxlstack.cpp.
References BeginBatch(), EndBatch(), ExpandItem(), wxLuaStackListData::GetDebugItem(), wxLuaDebugItem::GetFlagBit(), wxLuaStackListData::m_level, m_listData, m_show_dup_expand_msg, WXLUA_DEBUGITEM_EXPANDED, and wxProgressDialog.
Referenced by OnExpandButton().
void wxLuaStackDialog::FillStackCombobox (const wxLuaDebugData & debugData)
Definition at line 540 of file wxlstack.cpp.
References wxLuaDebugData::GetCount(), wxLuaDebugItem::GetIndex(), wxLuaDebugItem::GetKey(), wxLuaDebugData::Item(), m_stackChoice, m_stackEntries, wxLuaDebugData::Ok(), and SelectStack().
Referenced by EnumerateStack(), and wxLuaDebuggerBase::OnDebugStackEnum().
void wxLuaStackDialog::FillStackEntry (int nEntry, const wxLuaDebugData & debugData)
Definition at line 564 of file wxlstack.cpp.
References DeleteAllListItemData(), EnumerateGlobalData(), wxLuaDebugData::EnumerateTable(), FillTableEntry(), wxLuaDebugData::GetCount(), m_expandedItems, m_listCtrl, m_luaReferences, m_stack_sel, m_stackEntries, m_treeCtrl, m_wxlState, wxLuaState::Ok(), wxLuaDebugData::Ok(), RemoveAllLuaReferences(), WXLUA_DEBUGITEM_EXPANDED, WXLUA_DEBUGITEM_LOCALS, WXLUA_DEBUGITEM_VALUE_REF, and WXLUA_TNONE.
Referenced by EnumerateStackEntry(), and wxLuaDebuggerBase::OnDebugStackEntryEnum().
void wxLuaStackDialog::FillTableEntry (long lc_item, const wxLuaDebugData & debugData)
defined(WXLUA_STACK_MSWTREE)
Definition at line 603 of file wxlstack.cpp.
References BeginBatch(), DUMMY_TREEITEM, EndBatch(), wxLuaDebugData::GetCount(), wxLuaDebugItem::GetFlagBit(), GetItemImage(), wxLuaDebugItem::GetKey(), wxLuaDebugItem::GetRef(), wxLuaDebugData::Item(), wxLuaStackListData::m_childrenDebugData, wxLuaStackListData::m_level, m_listCtrl, m_listData, m_treeCtrl, wxLuaStackListData::m_treeId, wxLuaDebugData::Ok(), and WXLUA_DEBUGITEM_LOCALS.
Referenced by EnumerateGlobalData(), EnumerateTable(), ExpandItem(), FillStackEntry(), and wxLuaDebuggerBase::OnDebugTableEnum().
long wxLuaStackDialog::FindListItem (wxLuaStackListData * stkListData, bool get_parent = false) const
Definition at line 717 of file wxlstack.cpp.
References wxLuaStackListData::m_childrenDebugData, m_listCtrl, m_listData, and wxLuaStackListData::m_parentDebugData.
Referenced by OnTreeItem().
int wxLuaStackDialog::GetItemImage (const wxLuaDebugItem * dbgItem) [virtual]
Definition at line 427 of file wxlstack.cpp.
References wxLuaDebugItem::GetFlagBit(), wxLuaDebugItem::GetValueType(), IMG_BOOLEAN, IMG_CFUNCTION, IMG_INTEGER, IMG_LIGHTUSERDATA, IMG_LUAFUNCTION, IMG_NIL, IMG_NONE, IMG_NUMBER, IMG_STRING, IMG_TABLE, IMG_TABLE_OPEN, IMG_THREAD, IMG_UNKNOWN, IMG_USERDATA, WXLUA_DEBUGITEM_EXPANDED, WXLUA_DEBUGITEM_LOCALS, WXLUA_TBOOLEAN, WXLUA_TCFUNCTION, WXLUA_TFUNCTION, WXLUA_TINTEGER, WXLUA_TLIGHTUSERDATA, WXLUA_TNIL, WXLUA_TNONE, WXLUA_TNUMBER, WXLUA_TSTRING, WXLUA_TTABLE, WXLUA_TTHREAD, WXLUA_TUNKNOWN, and WXLUA_TUSERDATA.
Referenced by FillTableEntry(), wxLuaStackListCtrl::OnGetItemAttr(), and wxLuaStackListCtrl::OnGetItemColumnImage().
wxString wxLuaStackDialog::GetItemText (long item, long column, bool exact_value = false) [virtual]
Definition at line 461 of file wxlstack.cpp.
References wxLuaStackListData::GetDebugItem(), wxLuaDebugItem::GetKey(), wxLuaDebugItem::GetKeyTypeString(), wxLuaDebugItem::GetValue(), wxLuaDebugItem::GetValueTypeString(), LIST_COL_KEY, LIST_COL_KEY_TYPE, LIST_COL_LEVEL, LIST_COL_VALUE, LIST_COL_VALUE_TYPE, wxLuaStackListData::m_item_idx, wxLuaStackListData::m_level, and m_listData.
Referenced by OnFind(), wxLuaStackListCtrl::OnGetItemText(), and OnMenu().
void wxLuaStackDialog::Init () [private]
Definition at line 167 of file wxlstack.cpp.
void wxLuaStackDialog::OnExpandButton (wxCommandEvent & event)
Definition at line 735 of file wxlstack.cpp.
References CollapseItem(), ExpandItemChildren(), ID_WXLUA_STACK_EXPAND_BUTTON, and m_listCtrl.
void wxLuaStackDialog::OnFind (wxCommandEvent & event)
Definition at line 808 of file wxlstack.cpp.
References GetItemText(), ID_WXLUA_STACK_FINDMENU_BUTTON, ID_WXLUA_STACK_FINDMENU_CASE, ID_WXLUA_STACK_FINDMENU_KEYTYPE, ID_WXLUA_STACK_FINDMENU_LEVEL, ID_WXLUA_STACK_FINDMENU_NAME, ID_WXLUA_STACK_FINDMENU_VALUE, ID_WXLUA_STACK_FINDMENU_VALUETYPE, ID_WXLUA_STACK_FINDMENU_WHOLE_STRING, ID_WXLUA_STACK_FINDPREV_BUTTON, m_findComboBox, m_findMenu, m_listCtrl, and wxLuaPrependComboBoxString().
void wxLuaStackDialog::OnListItem (wxListEvent & event)
Definition at line 959 of file wxlstack.cpp.
References CollapseItem(), ExpandItem(), wxLuaStackListData::GetDebugItem(), wxLuaDebugItem::GetFlagBit(), m_listCtrl, m_listData, m_treeCtrl, wxLuaStackListData::m_treeId, and WXLUA_DEBUGITEM_EXPANDED.
void wxLuaStackDialog::OnListRightClick (wxListEvent & event)
Definition at line 1001 of file wxlstack.cpp.
References m_listCtrl, and m_listMenu.
void wxLuaStackDialog::OnMenu (wxCommandEvent & event)
Definition at line 765 of file wxlstack.cpp.
References GetItemText(), ID_WXLUA_STACK_FINDMENU_ALL, ID_WXLUA_STACK_FINDMENU_KEYTYPE, ID_WXLUA_STACK_FINDMENU_LEVEL, ID_WXLUA_STACK_FINDMENU_NAME, ID_WXLUA_STACK_FINDMENU_VALUE, ID_WXLUA_STACK_FINDMENU_VALUETYPE, ID_WXLUA_STACK_LISTMENU_COPY0, ID_WXLUA_STACK_LISTMENU_COPY4, m_findMenu, and m_listCtrl.
void wxLuaStackDialog::OnSelectStack (wxCommandEvent & event)
Definition at line 911 of file wxlstack.cpp.
References SelectStack().
void wxLuaStackDialog::OnTreeItem (wxTreeEvent & event)
Definition at line 925 of file wxlstack.cpp.
References CollapseItem(), ExpandItem(), FindListItem(), m_batch_count, m_listCtrl, wxLuaStackTreeData::m_stkListData, and m_treeCtrl.
void wxLuaStackDialog::RemoveAllLuaReferences ()
Definition at line 1226 of file wxlstack.cpp.
References wxLuaState::GetLuaState(), m_luaReferences, m_wxlState, wxLuaState::Ok(), wxlua_lreg_createtable(), wxlua_lreg_debug_refs_key, and wxluaR_unref().
Referenced by FillStackEntry(), and ~wxLuaStackDialog().
void wxLuaStackDialog::SelectStack (int stack_sel)
Definition at line 917 of file wxlstack.cpp.
References EnumerateStackEntry(), m_stack_sel, and m_stackEntries.
Referenced by FillStackCombobox(), and OnSelectStack().
void wxLuaStackDialog::SetShowDuplicateExpandMessage (bool show)
Definition at line 211 of file wxlstack.h.
Member Data Documentation
int wxLuaStackDialog::m_batch_count
Definition at line 237 of file wxlstack.h.
Referenced by BeginBatch(), EndBatch(), and OnTreeItem().
wxSize wxLuaStackDialog::m_defaultSize [static]
Definition at line 243 of file wxlstack.h.
Referenced by Create(), and ~wxLuaStackDialog().
wxLongToLongHashMap wxLuaStackDialog::m_expandedItems
Definition at line 239 of file wxlstack.h.
Referenced by CollapseItem(), DeleteAllListItemData(), ExpandItem(), and FillStackEntry().
wxComboBox* wxLuaStackDialog::m_findComboBox
Definition at line 226 of file wxlstack.h.
Referenced by Create(), and OnFind().
wxMenu* wxLuaStackDialog::m_findMenu
Definition at line 227 of file wxlstack.h.
Referenced by Create(), OnFind(), OnMenu(), and ~wxLuaStackDialog().
wxImageList* wxLuaStackDialog::m_imageList
Definition at line 232 of file wxlstack.h.
Referenced by Create(), and ~wxLuaStackDialog().
int wxLuaStackDialog::m_img_font_size
Definition at line 234 of file wxlstack.h.
Referenced by CreateBmpString().
wxListCtrl* wxLuaStackDialog::m_listCtrl
Definition at line 218 of file wxlstack.h.
Referenced by BeginBatch(), CollapseItem(), Create(), EndBatch(), ExpandItem(), FillStackEntry(), FillTableEntry(), FindListItem(), OnExpandButton(), OnFind(), OnListItem(), OnListRightClick(), OnMenu(), OnTreeItem(), and ~wxLuaStackDialog().
wxArrayPtrVoid wxLuaStackDialog::m_listData
Definition at line 241 of file wxlstack.h.
Referenced by CollapseItem(), DeleteAllListItemData(), ExpandItem(), ExpandItemChildren(), FillTableEntry(), FindListItem(), GetItemText(), wxLuaStackListCtrl::OnGetItemAttr(), wxLuaStackListCtrl::OnGetItemColumnImage(), and OnListItem().
wxMenu* wxLuaStackDialog::m_listMenu
Definition at line 220 of file wxlstack.h.
Referenced by Create(), OnListRightClick(), and ~wxLuaStackDialog().
wxArrayInt wxLuaStackDialog::m_luaReferences
Definition at line 230 of file wxlstack.h.
Referenced by EnumerateGlobalData(), EnumerateStackEntry(), EnumerateTable(), FillStackEntry(), and RemoveAllLuaReferences().
bool wxLuaStackDialog::m_show_dup_expand_msg
Definition at line 236 of file wxlstack.h.
Referenced by ExpandItem(), and ExpandItemChildren().
wxSplitterWindow* wxLuaStackDialog::m_splitterWin
Definition at line 217 of file wxlstack.h.
Referenced by Create().
int wxLuaStackDialog::m_stack_sel
Definition at line 223 of file wxlstack.h.
Referenced by FillStackEntry(), and SelectStack().
wxChoice* wxLuaStackDialog::m_stackChoice
Definition at line 222 of file wxlstack.h.
Referenced by Create(), and FillStackCombobox().
wxArrayInt wxLuaStackDialog::m_stackEntries
Definition at line 224 of file wxlstack.h.
Referenced by FillStackCombobox(), FillStackEntry(), and SelectStack().
wxTreeCtrl* wxLuaStackDialog::m_treeCtrl
Definition at line 219 of file wxlstack.h.
Referenced by BeginBatch(), CollapseItem(), Create(), EndBatch(), FillStackEntry(), FillTableEntry(), OnListItem(), OnTreeItem(), and ~wxLuaStackDialog().
wxColour wxLuaStackDialog::m_typeColours[IMG__COUNT]
Definition at line 233 of file wxlstack.h.
Referenced by Create(), and wxLuaStackListCtrl::OnGetItemAttr().
wxLuaState wxLuaStackDialog::m_wxlState
Definition at line 229 of file wxlstack.h.
Referenced by Create(), EnumerateGlobalData(), EnumerateStack(), EnumerateStackEntry(), EnumerateTable(), FillStackEntry(), and RemoveAllLuaReferences().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluadebug/include/wxlstack.h
/mnt/share/devel/lua/wxLua/modules/wxluadebug/src/wxlstack.cpp