wxLua: wxLuaState Class Reference
wxLuaState Class Reference
#include <wxlstate.h>
Public Member Functions
wxLuaState (bool create=false)
wxLuaState (wxEvtHandler *handler, wxWindowID id=wxID_ANY)
wxLuaState (lua_State *L, int state_type=wxLUASTATE_GETSTATE)
wxLuaState (const wxLuaState &wxlState)
virtual ~wxLuaState ()
void Create (const wxLuaState &wxlState)
bool Create (wxEvtHandler *handler=NULL, wxWindowID id=wxID_ANY)
bool Create (lua_State *L, int state_type=wxLUASTATE_GETSTATE)
bool Ok () const
void Destroy ()
bool CloseLuaState (bool force)
bool IsClosing () const
lua_State * GetLuaState () const
wxLuaStateRefData * GetLuaStateRefData () const
wxLuaStateData * GetLuaStateData () const
void SetEventHandler (wxEvtHandler *evtHandler)
wxEvtHandler * GetEventHandler () const
void SetId (wxWindowID id)
wxWindowID GetId () const
bool SendEvent (wxLuaEvent &event) const
int RunFile (const wxString &fileName, int nresults=0)
int RunString (const wxString &script, const wxString &name=wxEmptyString, int nresults=0)
int RunBuffer (const char buf[], size_t size, const wxString &name=wxT("= lua"), int nresults=0)
int LuaDoString (const wxString &script, const wxString &name=wxEmptyString, int nresults=0)
int LuaDoFile (const wxString &filename, int nresults=0)
int LuaDoBuffer (const char *buffer, size_t len, const char *name, int nresults=0)
bool IsRunning () const
int LuaPCall (int narg, int nresults)
bool SendLuaErrorEvent (int status, int top)
wxEventType GetInEventType () const
void SetInEventType (wxEventType eventType)
int CompileString (const wxString &script, const wxString &name=wxEmptyString, wxString *errMsg=NULL, int *line_num=NULL)
int CompileBuffer (const char buf[], size_t size, const wxString &name=wxEmptyString, wxString *errMsg=NULL, int *line_num=NULL)
void DebugHookBreak (const wxString &message=wxT("Lua interpreter stopped"))
void ClearDebugHookBreak ()
bool GetDebugHookBreak () const
wxString GetDebugHookBreakMessage () const
void SetLuaDebugHook (int hook=LUA_MASKCALL|LUA_MASKRET|LUA_MASKLINE|LUA_MASKCOUNT, int count=1000, int yield_ms=100, bool send_debug_evt=false)
int GetLuaDebugHook () const
int GetLuaDebugHookCount () const
int GetLuaDebugHookYield () const
bool GetLuaDebugHookSendEvt () const
unsigned long GetLastLuaDebugHookTime () const
void SetLastLuaDebugHookTime (unsigned long t)
void RegisterFunction (lua_CFunction func, const char *funcName)
bool RegisterBinding (wxLuaBinding *binding)
bool RegisterBindings ()
wxLuaBinding * GetLuaBinding (const wxString &bindingName) const
const wxLuaBindClass * GetBindClass (int iClassTag) const
const wxLuaBindClass * GetBindClass (const char *className) const
const wxLuaBindClass * GetBindClass (const wxLuaBindMethod *wxlMethod) const
const wxLuaBindClass * GetBindClass (const wxLuaBindCFunc *wxlCFunc) const
int IsDerivedType (int wxl_type, int base_wxl_type) const
const wxLuaBindEvent * GetBindEvent (wxEventType eventType) const
void SetCallBaseClassFunction (bool call_base)
bool GetCallBaseClassFunction ()
void AddGCObject (wxObject *wxobj)
void AddGCObject (void *obj_ptr, wxObject *wxobj)
bool DeleteGCObject (void *udata, void *obj_ptr, int flags)
bool IsGCObject (void *obj_ptr) const
wxArrayString GetGCObjectInfo () const
void AddTrackedWindow (wxObject *win)
void RemoveTrackedWindow (wxWindow *win)
bool IsTrackedWindow (wxWindow *win, bool check_parents=true) const
wxArrayString GetTrackedWindowInfo () const
void GarbageCollectWindows (bool closeWindows)
void AddTrackedEventCallback (wxLuaEventCallback *callback)
bool RemoveTrackedEventCallback (wxLuaEventCallback *callback)
wxArrayString GetTrackedEventCallbackInfo () const
void AddTrackedWinDestroyCallback (wxLuaWinDestroyCallback *callback)
bool RemoveTrackedWinDestroyCallback (wxLuaWinDestroyCallback *callback)
wxArrayString GetTrackedWinDestroyCallbackInfo () const
void wxlua_Error (const char *errorMsg) const
void * wxlua_ToUserdata (int stack_idx, bool null_ptr=false) const
int wxluaR_Ref (int stack_idx, void *lightuserdata_reg_key)
bool wxluaR_Unref (int wxlref_index, void *lightuserdata_reg_key)
bool wxluaR_GetRef (int wxlref_index, void *lightuserdata_reg_key)
int wxluaT_NewMetatable (int wxl_type)
bool wxluaT_SetMetatable (int wxl_type)
int wxluaT_Type (int stack_idx) const
bool wxluaT_PushUserDataType (const void *obj_ptr, int wxl_type, bool track)
int IswxLuaType (int luatype, int wxl_type) const
bool IsUserDataType (int stack_idx, int wxl_type) const
void * GetUserDataType (int stack_idx, int iTag) const
const char * GetStringType (int stack_idx)
wxString GetwxStringType (int stack_idx)
bool GetBooleanType (int stack_idx)
long GetIntegerType (int stack_idx)
double GetNumberType (int stack_idx)
bool IsStringType (int stack_idx) const
bool IswxStringType (int stack_idx) const
bool IsBooleanType (int stack_idx) const
bool IsIntegerType (int stack_idx) const
bool IsNumberType (int stack_idx) const
wxString * GetwxStringArray (int stack_idx, int &count)
wxLuaSmartwxArrayString GetwxArrayString (int stack_idx)
const char ** GetCharArray (int stack_idx, int &count)
int * GetIntArray (int stack_idx, int &count)
wxLuaSmartwxArrayInt GetwxArrayInt (int stack_idx)
int PushwxArrayStringTable (const wxArrayString &strArray)
int PushwxArrayIntTable (const wxArrayInt &intArray)
wxString GetwxLuaTypeName (int wxl_type) const
bool SetDerivedMethod (void *obj_ptr, const char *method_name, wxLuaObject *wxlObj)
bool HasDerivedMethod (void *obj_ptr, const char *method_name, bool push_method) const
bool RemoveDerivedMethods (void *obj_ptr) const
int lua_GetTop () const
void lua_SetTop (int index)
void lua_PushValue (int index)
void lua_Remove (int index)
void lua_Pop (int count)
void lua_Insert (int index)
void lua_Replace (int index)
int lua_CheckStack (int size)
void lua_XMove (const wxLuaState &to, int n)
bool lua_IsNumber (int index) const
bool lua_IsString (int index) const
bool lua_IsCFunction (int index) const
bool lua_IsUserdata (int index) const
int lua_Type (int index) const
wxString lua_TypeName (int type) const
int lua_Equal (int index1, int index2) const
int lua_RawEqual (int index1, int index2) const
int lua_LessThan (int index1, int index2) const
double lua_ToNumber (int index) const
int lua_ToInteger (int index) const
int lua_ToBoolean (int index) const
const char * lua_ToString (int index) const
wxString lua_TowxString (int index) const
size_t lua_StrLen (int index) const
size_t luaL_ObjLen (int index) const
lua_CFunction lua_ToCFunction (int index) const
void * lua_ToUserdata (int index) const
wxLuaState lua_ToThread (int index) const
const void * lua_ToPointer (int index) const
void lua_PushNil ()
void lua_PushNumber (lua_Number n)
void lua_PushInteger (lua_Integer n)
void lua_PushLString (const char *s, size_t len)
void lua_PushString (const char *s)
void lua_PushCClosure (lua_CFunction fn, int n)
void lua_PushBoolean (bool b)
void lua_PushLightUserdata (void *p)
void lua_GetTable (int idx)
void lua_GetField (int idx, const char *k)
void lua_RawGet (int idx)
void lua_RawGeti (int idx, int n)
void lua_CreateTable (int narr, int nrec)
void lua_NewTable ()
void * lua_NewUserdata (size_t sz)
int lua_GetMetatable (int objindex)
void lua_GetFenv (int idx)
void lua_SetTable (int idx)
void lua_SetField (int idx, const char *k)
void lua_RawSet (int idx)
void lua_RawSeti (int idx, int n)
int lua_SetMetatable (int objindex)
int lua_SetFenv (int idx)
void lua_Call (int nargs, int nresults)
int lua_PCall (int nargs, int nresults, int errfunc)
int lua_CPCall (lua_CFunction func, void *ud)
int lua_Load (lua_Reader reader, void *dt, const char *chunkname)
int lua_Dump (lua_Writer writer, void *data)
int lua_Yield (int nresults)
int lua_Resume (int narg)
int lua_Status ()
int lua_GetGCCount ()
wxString lua_Version () const
int lua_Error ()
int lua_Next (int idx)
void lua_Concat (int n)
void lua_Register (const char *funcName, lua_CFunction f)
void lua_PushCFunction (lua_CFunction f)
bool lua_IsFunction (int idx) const
bool lua_IsTable (int idx) const
bool lua_IsLightUserdata (int idx) const
bool lua_IsNil (int idx) const
bool lua_IsBoolean (int idx) const
bool lua_IsThread (int idx) const
bool lua_IsNone (int idx) const
bool lua_IsNoneOrNil (int idx) const
void lua_SetGlobal (const char *s)
void lua_GetGlobal (const char *s)
int lua_GetStack (int level, lua_Debug *ar)
int lua_GetInfo (const char *what, lua_Debug *ar)
const char * lua_GetLocal (const lua_Debug *ar, int n)
const char * lua_SetLocal (const lua_Debug *ar, int n)
const char * lua_GetUpvalue (int funcindex, int n)
const char * lua_SetUpvalue (int funcindex, int n)
int lua_SetHook (lua_Hook func, int mask, int count)
lua_Hook lua_GetHook ()
int lua_GetHookMask ()
int lua_GetHookCount ()
void luaI_OpenLib (const char *libname, const luaL_reg *l, int nup)
void luaL_Register (const char *libname, const luaL_reg *l)
int luaL_GetMetafield (int obj, const char *e)
int luaL_CallMeta (int obj, const char *e)
int luaL_TypeError (int narg, const char *tname)
int luaL_ArgError (int numarg, const char *extramsg)
const char * luaL_CheckLString (int numArg, size_t *l)
const char * luaL_OptLString (int numArg, const char *def, size_t *len)
lua_Number luaL_CheckNumber (int numArg)
lua_Number luaL_OptNumber (int nArg, lua_Number def)
lua_Integer luaL_CheckInteger (int numArg)
lua_Integer luaL_OptInteger (int nArg, lua_Integer def)
void luaL_CheckStack (int sz, const char *msg)
void luaL_CheckType (int narg, int t)
void luaL_CheckAny (int narg)
int luaL_NewMetatable (const char *tname)
void luaL_GetMetatable (const char *tname)
void * luaL_CheckUdata (int ud, const char *tname)
void luaL_Where (int lvl)
int luaL_Error (const char *fmt,...)
int luaL_CheckOption (int narg, const char *def, const char *const lst[])
int luaL_Ref (int t)
void luaL_Unref (int t, int ref)
int luaL_LoadFile (const char *filename)
int luaL_LoadBuffer (const char *buff, size_t sz, const char *name)
int luaL_LoadString (const char *s)
void luaL_ArgCheck (bool condition, int numarg, const char *extramsg)
const char * luaL_CheckString (int numArg)
const char * luaL_OptString (int numArg, const char *def)
int luaL_CheckInt (int numArg)
int luaL_OptInt (int numArg, int def)
long luaL_CheckLong (int numArg)
long luaL_OptLong (int numArg, int def)
void GetGlobals ()
wxString GetLuaPath ()
void AddLuaPath (const wxPathList &pathlist)
void AddLuaPath (const wxFileName &filename)
bool operator== (const wxLuaState &wxlState) const
bool operator!= (const wxLuaState &wxlState) const
wxLuaState & operator= (const wxLuaState &wxlState)
Static Public Member Functions
static wxLuaState GetwxLuaState (lua_State *L)
static wxLuaState GetDerivedMethodState (void *obj_ptr, const char *method_name)
Static Public Attributes
static wxHashMapLuaState s_wxHashMapLuaState
static bool sm_wxAppMainLoop_will_run = false
Private Member Functions
virtual wxObjectRefData * CreateRefData () const
Detailed Description
Definition at line 682 of file wxlstate.h.
Constructor & Destructor Documentation
wxLuaState::wxLuaState (bool create = false)
Definition at line 687 of file wxlstate.h.
Referenced by Create(), GetwxLuaState(), and lua_ToThread().
wxLuaState::wxLuaState (wxEvtHandler * handler, wxWindowID id = wxID_ANY)
Definition at line 690 of file wxlstate.h.
wxLuaState::wxLuaState (lua_State * L, int state_type = wxLUASTATE_GETSTATE)
Definition at line 693 of file wxlstate.h.
wxLuaState::wxLuaState (const wxLuaState & wxlState)
Definition at line 695 of file wxlstate.h.
virtual wxLuaState::~wxLuaState () [virtual]
Definition at line 699 of file wxlstate.h.
Member Function Documentation
void wxLuaState::AddGCObject (void * obj_ptr, wxObject * wxobj)
Definition at line 2945 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaO_addgcobject().
void wxLuaState::AddGCObject (wxObject * wxobj)
Definition at line 2940 of file wxlstate.cpp.
void wxLuaState::AddLuaPath (const wxFileName & filename)
Definition at line 4027 of file wxlstate.cpp.
References GetLuaPath(), LUA_PATH, lua_PushString(), and lua_SetGlobal().
void wxLuaState::AddLuaPath (const wxPathList & pathlist)
Definition at line 4016 of file wxlstate.cpp.
void wxLuaState::AddTrackedEventCallback (wxLuaEventCallback * callback)
Definition at line 3000 of file wxlstate.cpp.
References wxLuaEventCallback::GetEvtHandler(), M_WXLSTATEDATA, Ok(), and wxlua_lreg_evtcallbacks_key.
void wxLuaState::AddTrackedWinDestroyCallback (wxLuaWinDestroyCallback * callback)
Definition at line 3059 of file wxlstate.cpp.
References wxLuaWinDestroyCallback::GetWindow(), M_WXLSTATEDATA, Ok(), and wxlua_lreg_windestroycallbacks_key.
void wxLuaState::AddTrackedWindow (wxObject * win)
Definition at line 2969 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaW_addtrackedwindow().
void wxLuaState::ClearDebugHookBreak ()
Definition at line 2769 of file wxlstate.cpp.
References GetLuaDebugHook(), GetLuaDebugHookCount(), GetLuaDebugHookSendEvt(), GetLuaDebugHookYield(), M_WXLSTATEDATA, Ok(), and SetLuaDebugHook().
Referenced by wxlua_debugHookFunction().
bool wxLuaState::CloseLuaState (bool force)
Definition at line 2498 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::CompileBuffer (const char buf[], size_t size, const wxString & name = wxEmptyString, wxString * errMsg = NULL, int * line_num = NULL)
Definition at line 2743 of file wxlstate.cpp.
References wx2lua(), and wxlua_errorinfo().
Referenced by CompileString().
int wxLuaState::CompileString (const wxString & script, const wxString & name = wxEmptyString, wxString * errMsg = NULL, int * line_num = NULL)
Definition at line 2738 of file wxlstate.cpp.
References CompileBuffer(), wxLuaCharBuffer::GetData(), and wxLuaCharBuffer::Length().
Referenced by wxLua_function_CompileLuaScript().
bool wxLuaState::Create (lua_State * L, int state_type = wxLUASTATE_GETSTATE)
Definition at line 2358 of file wxlstate.cpp.
References Destroy(), GetwxLuaState(), wxLuaBinding::InstallClassMetatable(), luaopen_bit(), M_WXLSTATEDATA, Ok(), RegisterBindings(), RegisterFunction(), s_wxHashMapLuaState, WXLUA_HASBIT, wxlua_lreg_classes_key, wxlua_lreg_createtable(), wxlua_lreg_debug_refs_key, wxlua_lreg_derivedmethods_key, wxlua_lreg_evtcallbacks_key, wxlua_lreg_gcobjects_key, wxlua_lreg_refs_key, wxlua_lreg_regtable_key, wxlua_lreg_topwindows_key, wxlua_lreg_types_key, wxlua_lreg_weakobjects_key, wxlua_lreg_windestroycallbacks_key, wxlua_lreg_wxluabindings_key, wxlua_lreg_wxluastate_key, wxlua_lreg_wxluastatedata_key, wxlua_printFunction(), wxlua_setwxeventtype(), wxLuaBindClass_NULL, wxLuaState(), wxLUASTATE_GETSTATE, wxLUASTATE_OPENBINDINGS, wxLUASTATE_SETSTATE, and wxLUASTATE_STATICSTATE.
bool wxLuaState::Create (wxEvtHandler * handler = NULL, wxWindowID id = wxID_ANY)
Definition at line 2338 of file wxlstate.cpp.
References Create(), Destroy(), GetId(), M_WXLSTATEDATA, SendEvent(), wxLUASTATE_OPENBINDINGS, and wxLUASTATE_SETSTATE.
void wxLuaState::Create (const wxLuaState & wxlState)
Definition at line 2332 of file wxlstate.cpp.
References Destroy().
Referenced by Create().
wxObjectRefData * wxLuaState::CreateRefData () const [private, virtual]
Definition at line 2323 of file wxlstate.cpp.
void wxLuaState::DebugHookBreak (const wxString & message = wxT("Lua interpreter stopped"))
Definition at line 2755 of file wxlstate.cpp.
References GetLuaState(), M_WXLSTATEDATA, Ok(), and wxlua_debugHookFunction().
bool wxLuaState::DeleteGCObject (void * udata, void * obj_ptr, int flags)
Definition at line 2951 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaO_deletegcobject().
void wxLuaState::Destroy ()
Definition at line 2487 of file wxlstate.cpp.
References M_WXLSTATEDATA.
Referenced by Create().
void wxLuaState::GarbageCollectWindows (bool closeWindows)
Definition at line 2993 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxLuaCleanupWindows().
const wxLuaBindClass * wxLuaState::GetBindClass (const wxLuaBindCFunc * wxlCFunc) const
Definition at line 2908 of file wxlstate.cpp.
References wxLuaBinding::FindBindClass().
const wxLuaBindClass * wxLuaState::GetBindClass (const wxLuaBindMethod * wxlMethod) const
Definition at line 2903 of file wxlstate.cpp.
References wxLuaBinding::FindBindClass().
const wxLuaBindClass * wxLuaState::GetBindClass (const char * className) const
Definition at line 2898 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaT_getclass().
const wxLuaBindClass * wxLuaState::GetBindClass (int iClassTag) const
Definition at line 2885 of file wxlstate.cpp.
References wxLuaBinding::FindBindClass(), M_WXLSTATEDATA, Ok(), and wxluaT_getclass().
Referenced by wxLuaEventCallback::OnEvent().
const wxLuaBindEvent * wxLuaState::GetBindEvent (wxEventType eventType) const
Definition at line 2920 of file wxlstate.cpp.
References wxLuaBinding::FindBindEvent(), and Ok().
Referenced by wxLuaEventCallback::Connect().
bool wxLuaState::GetBooleanType (int stack_idx)
Definition at line 3208 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getbooleantype().
bool wxLuaState::GetCallBaseClassFunction ()
Definition at line 2931 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getcallbaseclassfunction().
const char ** wxLuaState::GetCharArray (int stack_idx, int & count)
Definition at line 3264 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getchararray().
bool wxLuaState::GetDebugHookBreak () const
Definition at line 2780 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
wxString wxLuaState::GetDebugHookBreakMessage () const
Definition at line 2785 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
wxLuaState wxLuaState::GetDerivedMethodState (void * obj_ptr, const char * method_name) [static]
Definition at line 3318 of file wxlstate.cpp.
References HasDerivedMethod(), s_wxHashMapLuaState, and wxNullLuaState.
wxEvtHandler * wxLuaState::GetEventHandler () const
Definition at line 2577 of file wxlstate.cpp.
References M_WXLSTATEDATA.
wxArrayString wxLuaState::GetGCObjectInfo () const
Definition at line 2963 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaO_getgcobjectinfo().
void wxLuaState::GetGlobals ()
Definition at line 3996 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
wxWindowID wxLuaState::GetId () const
Definition at line 2588 of file wxlstate.cpp.
References M_WXLSTATEDATA.
Referenced by Create(), SendLuaErrorEvent(), wxlua_debugHookFunction(), and wxlua_printFunction().
wxEventType wxLuaState::GetInEventType () const
Definition at line 2726 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getwxeventtype().
int * wxLuaState::GetIntArray (int stack_idx, int & count)
Definition at line 3282 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getintarray().
long wxLuaState::GetIntegerType (int stack_idx)
Definition at line 3213 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getintegertype().
unsigned long wxLuaState::GetLastLuaDebugHookTime () const
Definition at line 2828 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
wxLuaBinding * wxLuaState::GetLuaBinding (const wxString & bindingName) const
Definition at line 2879 of file wxlstate.cpp.
int wxLuaState::GetLuaDebugHook () const
Definition at line 2807 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by ClearDebugHookBreak().
int wxLuaState::GetLuaDebugHookCount () const
Definition at line 2812 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by ClearDebugHookBreak().
bool wxLuaState::GetLuaDebugHookSendEvt () const
Definition at line 2822 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by ClearDebugHookBreak().
int wxLuaState::GetLuaDebugHookYield () const
Definition at line 2817 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by ClearDebugHookBreak().
wxString wxLuaState::GetLuaPath ()
Definition at line 4005 of file wxlstate.cpp.
References lua_GetGlobal(), LUA_PATH, lua_Pop(), lua_TowxString(), and Ok().
Referenced by AddLuaPath().
lua_State * wxLuaState::GetLuaState () const
Definition at line 2512 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaDebugTarget::DebugHook(), DebugHookBreak(), wxLuaBinding::DoRegisterBinding(), wxLuaDebugData::EnumerateStack(), wxLuaDebugData::EnumerateStackEntry(), wxLuaDebugData::EnumerateTable(), wxLuaDebugTarget::EvaluateExpr(), wxLuaObject::GetObject(), wxLuaDebugData::GetTableInfo(), wxLuaDebugData::GetTypeValue(), wxLuaDebugData::GetUserDataInfo(), GetwxLuaState(), lua_XMove(), wxLuaWinDestroyCallback::OnDestroy(), wxLuaBinding_wxlua::RegisterBinding(), wxLuaBinding::RegisterBinding(), wxLuaStackDialog::RemoveAllLuaReferences(), SendLuaErrorEvent(), and wxLuaDebugTarget::wxLuaDebugTarget().
wxLuaStateData * wxLuaState::GetLuaStateData () const
Definition at line 2518 of file wxlstate.cpp.
References M_WXLSTATEDATA.
Referenced by GetwxLuaState().
wxLuaStateRefData* wxLuaState::GetLuaStateRefData () const
Definition at line 744 of file wxlstate.h.
double wxLuaState::GetNumberType (int stack_idx)
Definition at line 3218 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getnumbertype().
const char * wxLuaState::GetStringType (int stack_idx)
Definition at line 3198 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getstringtype().
wxArrayString wxLuaState::GetTrackedEventCallbackInfo () const
Definition at line 3031 of file wxlstate.cpp.
References wxLuaEventCallback::GetInfo(), M_WXLSTATEDATA, Ok(), and wxlua_lreg_evtcallbacks_key.
Referenced by wxLua_function_GetTrackedEventCallbackInfo().
wxArrayString wxLuaState::GetTrackedWinDestroyCallbackInfo () const
Definition at line 3090 of file wxlstate.cpp.
References wxLuaWinDestroyCallback::GetInfo(), M_WXLSTATEDATA, Ok(), and wxlua_lreg_windestroycallbacks_key.
Referenced by wxLua_function_GetTrackedWinDestroyCallbackInfo().
wxArrayString wxLuaState::GetTrackedWindowInfo () const
Definition at line 2987 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaW_gettrackedwindowinfo().
void * wxLuaState::GetUserDataType (int stack_idx, int iTag) const
Definition at line 3192 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaT_getuserdatatype().
wxLuaSmartwxArrayInt wxLuaState::GetwxArrayInt (int stack_idx)
Definition at line 3288 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getwxArrayInt().
Referenced by wxLuaObject::GetArrayPtr().
wxLuaSmartwxArrayString wxLuaState::GetwxArrayString (int stack_idx)
Definition at line 3258 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getwxArrayString().
wxLuaState wxLuaState::GetwxLuaState (lua_State * L) [static]
Definition at line 2524 of file wxlstate.cpp.
References GetLuaState(), GetLuaStateData(), wxLuaStateRefData::m_lua_State, wxLuaStateRefData::m_lua_State_coroutine, wxLuaStateRefData::m_lua_State_static, wxLuaStateRefData::m_own_stateData, wxLuaStateRefData::m_wxlStateData, wxlua_lreg_wxluastate_key, wxLuaState(), and wxNullLuaState.
Referenced by Create().
wxString wxLuaState::GetwxLuaTypeName (int wxl_type) const
Definition at line 3294 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaT_typename().
Referenced by wxLuaEventCallback::GetInfo().
wxString * wxLuaState::GetwxStringArray (int stack_idx, int & count)
Definition at line 3252 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getwxStringarray().
wxString wxLuaState::GetwxStringType (int stack_idx)
Definition at line 3203 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_getwxStringtype().
bool wxLuaState::HasDerivedMethod (void * obj_ptr, const char * method_name, bool push_method) const
Definition at line 3306 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_hasderivedmethod().
Referenced by GetDerivedMethodState().
bool wxLuaState::IsBooleanType (int stack_idx) const
Definition at line 3236 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_isbooleantype.
bool wxLuaState::IsClosing () const
Definition at line 2504 of file wxlstate.cpp.
References M_WXLSTATEDATA.
Referenced by wxLuaObject::~wxLuaObject().
int wxLuaState::IsDerivedType (int wxl_type, int base_wxl_type) const
Definition at line 2914 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaT_isderivedtype().
bool wxLuaState::IsGCObject (void * obj_ptr) const
Definition at line 2957 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaO_isgcobject().
bool wxLuaState::IsIntegerType (int stack_idx) const
Definition at line 3241 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_isintegertype.
bool wxLuaState::IsNumberType (int stack_idx) const
Definition at line 3246 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_isnumbertype.
bool wxLuaState::IsRunning () const
Definition at line 2663 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::IsStringType (int stack_idx) const
Definition at line 3224 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_isstringtype.
bool wxLuaState::IsTrackedWindow (wxWindow * win, bool check_parents = true) const
Definition at line 2981 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaW_istrackedwindow().
bool wxLuaState::IsUserDataType (int stack_idx, int wxl_type) const
Definition at line 3186 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaT_isuserdatatype().
int wxLuaState::IswxLuaType (int luatype, int wxl_type) const
Definition at line 3180 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_iswxluatype().
bool wxLuaState::IswxStringType (int stack_idx) const
Definition at line 3230 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_iswxstringtype().
void wxLuaState::lua_Call (int nargs, int nresults)
Definition at line 3619 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_CheckStack (int size)
Definition at line 3372 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaEventCallback::OnEvent().
void wxLuaState::lua_Concat (int n)
Definition at line 3690 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_CPCall (lua_CFunction func, void * ud)
Definition at line 3629 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_CreateTable (int narr, int nrec)
Definition at line 3556 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Dump (lua_Writer writer, void * data)
Definition at line 3639 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Equal (int index1, int index2) const
Definition at line 3417 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Error ()
Definition at line 3680 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_GetFenv (int idx)
Definition at line 3576 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_GetField (int idx, const char * k)
Definition at line 3541 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_GetGCCount ()
Definition at line 3667 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_GetGlobal (const char * s)
Definition at line 3756 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by GetLuaPath().
lua_Hook wxLuaState::lua_GetHook ()
Definition at line 3801 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_GetHookCount ()
Definition at line 3811 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_GetHookMask ()
Definition at line 3806 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_GetInfo (const char * what, lua_Debug * ar)
Definition at line 3770 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
const char * wxLuaState::lua_GetLocal (const lua_Debug * ar, int n)
Definition at line 3775 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_GetMetatable (int objindex)
Definition at line 3571 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_GetStack (int level, lua_Debug * ar)
Definition at line 3765 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_GetTable (int idx)
Definition at line 3536 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_GetTop () const
Definition at line 3337 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaEventCallback::OnEvent(), RunBuffer(), and RunFile().
const char * wxLuaState::lua_GetUpvalue (int funcindex, int n)
Definition at line 3785 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_Insert (int index)
Definition at line 3362 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsBoolean (int idx) const
Definition at line 3730 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsCFunction (int index) const
Definition at line 3396 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsFunction (int idx) const
Definition at line 3710 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsLightUserdata (int idx) const
Definition at line 3720 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsNil (int idx) const
Definition at line 3725 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsNone (int idx) const
Definition at line 3740 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsNoneOrNil (int idx) const
Definition at line 3745 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsNumber (int index) const
Definition at line 3386 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsString (int index) const
Definition at line 3391 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsTable (int idx) const
Definition at line 3715 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsThread (int idx) const
Definition at line 3735 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
bool wxLuaState::lua_IsUserdata (int index) const
Definition at line 3401 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_LessThan (int index1, int index2) const
Definition at line 3427 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Load (lua_Reader reader, void * dt, const char * chunkname)
void wxLuaState::lua_NewTable ()
Definition at line 3561 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void * wxLuaState::lua_NewUserdata (size_t sz)
Definition at line 3566 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Next (int idx)
Definition at line 3685 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_PCall (int nargs, int nresults, int errfunc)
Definition at line 3624 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_Pop (int count)
Definition at line 3357 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaObject::GetArrayPtr(), wxLuaObject::GetBoolPtr(), wxLuaObject::GetIntPtr(), GetLuaPath(), wxLuaObject::GetStringPtr(), RegisterBinding(), and RegisterBindings().
void wxLuaState::lua_PushBoolean (bool b)
Definition at line 3522 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushCClosure (lua_CFunction fn, int n)
Definition at line 3517 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushCFunction (lua_CFunction f)
Definition at line 3704 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushInteger (lua_Integer n)
Definition at line 3502 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushLightUserdata (void * p)
Definition at line 3527 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushLString (const char * s, size_t len)
Definition at line 3507 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushNil ()
Definition at line 3492 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushNumber (lua_Number n)
Definition at line 3497 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_PushString (const char * s)
Definition at line 3512 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by AddLuaPath().
void wxLuaState::lua_PushValue (int index)
Definition at line 3347 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaEventCallback::OnEvent().
int wxLuaState::lua_RawEqual (int index1, int index2) const
Definition at line 3422 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_RawGet (int idx)
Definition at line 3546 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_RawGeti (int idx, int n)
Definition at line 3551 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_RawSet (int idx)
Definition at line 3595 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_RawSeti (int idx, int n)
Definition at line 3600 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_Register (const char * funcName, lua_CFunction f)
Definition at line 3699 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_Remove (int index)
Definition at line 3352 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_Replace (int index)
Definition at line 3367 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Resume (int narg)
Definition at line 3653 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_SetFenv (int idx)
Definition at line 3610 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaEventCallback::OnEvent().
void wxLuaState::lua_SetField (int idx, const char * k)
Definition at line 3590 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_SetGlobal (const char * s)
Definition at line 3751 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by AddLuaPath().
int wxLuaState::lua_SetHook (lua_Hook func, int mask, int count)
Definition at line 3796 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
const char * wxLuaState::lua_SetLocal (const lua_Debug * ar, int n)
Definition at line 3780 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_SetMetatable (int objindex)
Definition at line 3605 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_SetTable (int idx)
Definition at line 3585 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::lua_SetTop (int index)
Definition at line 3342 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaEventCallback::OnEvent(), RunBuffer(), and RunFile().
const char * wxLuaState::lua_SetUpvalue (int funcindex, int n)
Definition at line 3790 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Status ()
Definition at line 3658 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
size_t wxLuaState::lua_StrLen (int index) const
Definition at line 3458 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_ToBoolean (int index) const
Definition at line 3443 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaObject::GetBoolPtr().
lua_CFunction wxLuaState::lua_ToCFunction (int index) const
Definition at line 3468 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_ToInteger (int index) const
Definition at line 3438 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
double wxLuaState::lua_ToNumber (int index) const
Definition at line 3433 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by wxLuaObject::GetIntPtr().
const void * wxLuaState::lua_ToPointer (int index) const
Definition at line 3483 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
const char * wxLuaState::lua_ToString (int index) const
Definition at line 3448 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
wxLuaState wxLuaState::lua_ToThread (int index) const
Definition at line 3478 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxLuaState().
void * wxLuaState::lua_ToUserdata (int index) const
Definition at line 3473 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
wxString wxLuaState::lua_TowxString (int index) const
Definition at line 3453 of file wxlstate.cpp.
References lua2wx(), M_WXLSTATEDATA, and Ok().
Referenced by GetLuaPath(), and wxLuaObject::GetStringPtr().
int wxLuaState::lua_Type (int index) const
Definition at line 3406 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
wxString wxLuaState::lua_TypeName (int type) const
Definition at line 3411 of file wxlstate.cpp.
References lua2wx(), M_WXLSTATEDATA, and Ok().
wxString wxLuaState::lua_Version () const
Definition at line 3676 of file wxlstate.cpp.
References lua2wx().
void wxLuaState::lua_XMove (const wxLuaState & to, int n)
Definition at line 3377 of file wxlstate.cpp.
References GetLuaState(), M_WXLSTATEDATA, and Ok().
int wxLuaState::lua_Yield (int nresults)
Definition at line 3648 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::LuaDoBuffer (const char * buffer, size_t len, const char * name, int nresults = 0)
Definition at line 812 of file wxlstate.h.
References lua2wx().
Referenced by wxLuaDebugTarget::Run().
int wxLuaState::LuaDoFile (const wxString & filename, int nresults = 0)
Definition at line 811 of file wxlstate.h.
int wxLuaState::LuaDoString (const wxString & script, const wxString & name = wxEmptyString, int nresults = 0)
Definition at line 810 of file wxlstate.h.
void wxLuaState::luaI_OpenLib (const char * libname, const luaL_reg * l, int nup)
Definition at line 3820 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_ArgCheck (bool condition, int numarg, const char * extramsg)
Definition at line 3957 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_ArgError (int numarg, const char * extramsg)
Definition at line 3845 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_CallMeta (int obj, const char * e)
Definition at line 3835 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_CheckAny (int narg)
Definition at line 3891 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_CheckInt (int numArg)
Definition at line 3972 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
lua_Integer wxLuaState::luaL_CheckInteger (int numArg)
Definition at line 3870 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
long wxLuaState::luaL_CheckLong (int numArg)
Definition at line 3982 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
const char * wxLuaState::luaL_CheckLString (int numArg, size_t * l)
Definition at line 3850 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
lua_Number wxLuaState::luaL_CheckNumber (int numArg)
Definition at line 3860 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_CheckOption (int narg, const char * def, const char *const lst[])
Definition at line 3924 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_CheckStack (int sz, const char * msg)
Definition at line 3881 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
const char * wxLuaState::luaL_CheckString (int numArg)
Definition at line 3962 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_CheckType (int narg, int t)
Definition at line 3886 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void * wxLuaState::luaL_CheckUdata (int ud, const char * tname)
Definition at line 3907 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_Error (const char * fmt, ...)
Definition at line 3918 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_GetMetafield (int obj, const char * e)
Definition at line 3830 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_GetMetatable (const char * tname)
Definition at line 3902 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_LoadBuffer (const char * buff, size_t sz, const char * name)
Definition at line 3946 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by RunBuffer().
int wxLuaState::luaL_LoadFile (const char * filename)
Definition at line 3941 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by RunFile().
int wxLuaState::luaL_LoadString (const char * s)
Definition at line 3951 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_NewMetatable (const char * tname)
Definition at line 3897 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
size_t wxLuaState::luaL_ObjLen (int index) const
Definition at line 3463 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_OptInt (int numArg, int def)
Definition at line 3977 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
lua_Integer wxLuaState::luaL_OptInteger (int nArg, lua_Integer def)
Definition at line 3875 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
long wxLuaState::luaL_OptLong (int numArg, int def)
Definition at line 3987 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
const char * wxLuaState::luaL_OptLString (int numArg, const char * def, size_t * len)
Definition at line 3855 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
lua_Number wxLuaState::luaL_OptNumber (int nArg, lua_Number def)
Definition at line 3865 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
const char * wxLuaState::luaL_OptString (int numArg, const char * def)
Definition at line 3967 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_Ref (int t)
Definition at line 3930 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_Register (const char * libname, const luaL_reg * l)
Definition at line 3825 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::luaL_TypeError (int narg, const char * tname)
Definition at line 3840 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_Unref (int t, int ref)
Definition at line 3935 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::luaL_Where (int lvl)
Definition at line 3913 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
int wxLuaState::LuaPCall (int narg, int nresults)
Definition at line 2688 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), SendLuaErrorEvent(), and wxlua_traceback().
Referenced by wxLuaEventCallback::OnEvent(), RunBuffer(), and RunFile().
bool wxLuaState::Ok () const
Definition at line 2480 of file wxlstate.cpp.
References M_WXLSTATEDATA.
Referenced by AddGCObject(), AddTrackedEventCallback(), AddTrackedWinDestroyCallback(), AddTrackedWindow(), ClearDebugHookBreak(), CloseLuaState(), wxLuaEventCallback::Connect(), Create(), DebugHookBreak(), DeleteGCObject(), wxLuaBinding::DoRegisterBinding(), wxLuaStackDialog::EnumerateGlobalData(), wxLuaStackDialog::EnumerateStack(), wxLuaDebugData::EnumerateStack(), wxLuaStackDialog::EnumerateStackEntry(), wxLuaDebugData::EnumerateStackEntry(), wxLuaStackDialog::EnumerateTable(), wxLuaDebugData::EnumerateTable(), wxLuaStackDialog::FillStackEntry(), GarbageCollectWindows(), wxLuaObject::GetArrayPtr(), GetBindClass(), GetBindEvent(), GetBooleanType(), wxLuaObject::GetBoolPtr(), GetCallBaseClassFunction(), GetCharArray(), GetDebugHookBreak(), GetDebugHookBreakMessage(), GetGCObjectInfo(), GetGlobals(), GetInEventType(), GetIntArray(), GetIntegerType(), wxLuaObject::GetIntPtr(), GetLastLuaDebugHookTime(), GetLuaDebugHook(), GetLuaDebugHookCount(), GetLuaDebugHookSendEvt(), GetLuaDebugHookYield(), GetLuaPath(), GetLuaState(), GetNumberType(), wxLuaObject::GetObject(), wxLuaObject::GetStringPtr(), GetStringType(), wxLuaDebugData::GetTableInfo(), GetTrackedEventCallbackInfo(), GetTrackedWinDestroyCallbackInfo(), GetTrackedWindowInfo(), wxLuaDebugData::GetTypeValue(), wxLuaDebugData::GetUserDataInfo(), GetUserDataType(), GetwxArrayInt(), GetwxArrayString(), GetwxLuaTypeName(), GetwxStringArray(), GetwxStringType(), HasDerivedMethod(), IsBooleanType(), IsDerivedType(), IsGCObject(), IsIntegerType(), IsNumberType(), IsRunning(), IsStringType(), IsTrackedWindow(), IsUserDataType(), IswxLuaType(), IswxStringType(), lua_Call(), lua_CheckStack(), lua_Concat(), lua_CPCall(), lua_CreateTable(), lua_Dump(), lua_Equal(), lua_Error(), lua_GetFenv(), lua_GetField(), lua_GetGCCount(), lua_GetGlobal(), lua_GetHook(), lua_GetHookCount(), lua_GetHookMask(), lua_GetInfo(), lua_GetLocal(), lua_GetMetatable(), lua_GetStack(), lua_GetTable(), lua_GetTop(), lua_GetUpvalue(), lua_Insert(), lua_IsBoolean(), lua_IsCFunction(), lua_IsFunction(), lua_IsLightUserdata(), lua_IsNil(), lua_IsNone(), lua_IsNoneOrNil(), lua_IsNumber(), lua_IsString(), lua_IsTable(), lua_IsThread(), lua_IsUserdata(), lua_LessThan(), lua_NewTable(), lua_NewUserdata(), lua_Next(), lua_PCall(), lua_Pop(), lua_PushBoolean(), lua_PushCClosure(), lua_PushCFunction(), lua_PushInteger(), lua_PushLightUserdata(), lua_PushLString(), lua_PushNil(), lua_PushNumber(), lua_PushString(), lua_PushValue(), lua_RawEqual(), lua_RawGet(), lua_RawGeti(), lua_RawSet(), lua_RawSeti(), lua_Register(), lua_Remove(), lua_Replace(), lua_Resume(), lua_SetFenv(), lua_SetField(), lua_SetGlobal(), lua_SetHook(), lua_SetLocal(), lua_SetMetatable(), lua_SetTable(), lua_SetTop(), lua_SetUpvalue(), lua_Status(), lua_StrLen(), lua_ToBoolean(), lua_ToCFunction(), lua_ToInteger(), lua_ToNumber(), lua_ToPointer(), lua_ToString(), lua_ToThread(), lua_ToUserdata(), lua_TowxString(), lua_Type(), lua_TypeName(), lua_XMove(), lua_Yield(), luaI_OpenLib(), luaL_ArgCheck(), luaL_ArgError(), luaL_CallMeta(), luaL_CheckAny(), luaL_CheckInt(), luaL_CheckInteger(), luaL_CheckLong(), luaL_CheckLString(), luaL_CheckNumber(), luaL_CheckOption(), luaL_CheckStack(), luaL_CheckString(), luaL_CheckType(), luaL_CheckUdata(), luaL_Error(), luaL_GetMetafield(), luaL_GetMetatable(), luaL_LoadBuffer(), luaL_LoadFile(), luaL_LoadString(), luaL_NewMetatable(), luaL_ObjLen(), luaL_OptInt(), luaL_OptInteger(), luaL_OptLong(), luaL_OptLString(), luaL_OptNumber(), luaL_OptString(), luaL_Ref(), luaL_Register(), luaL_TypeError(), luaL_Unref(), luaL_Where(), LuaPCall(), wxLuaWinDestroyCallback::OnDestroy(), wxLuaEventCallback::OnEvent(), PushwxArrayIntTable(), PushwxArrayStringTable(), RegisterBinding(), wxLuaBinding::RegisterBinding(), RegisterBindings(), RegisterFunction(), wxLuaStackDialog::RemoveAllLuaReferences(), RemoveDerivedMethods(), RemoveTrackedEventCallback(), RemoveTrackedWinDestroyCallback(), RemoveTrackedWindow(), RunBuffer(), RunFile(), SendLuaErrorEvent(), SetCallBaseClassFunction(), SetDerivedMethod(), SetInEventType(), SetLastLuaDebugHookTime(), SetLuaDebugHook(), wxLuaObject::SetObject(), wxlua_Error(), wxlua_printFunction(), wxlua_ToUserdata(), wxlua_wxLuaBindClass__newindex(), wxluaR_GetRef(), wxluaR_Ref(), wxluaR_Unref(), wxluaT_NewMetatable(), wxluaT_PushUserDataType(), wxluaT_pushuserdatatype(), wxluaT_SetMetatable(), wxluaT_Type(), wxLuaEventCallback::~wxLuaEventCallback(), wxLuaObject::~wxLuaObject(), and wxLuaWinDestroyCallback::~wxLuaWinDestroyCallback().
bool wxLuaState::operator!= (const wxLuaState & wxlState) const
Definition at line 1282 of file wxlstate.h.
wxLuaState& wxLuaState::operator= (const wxLuaState & wxlState)
Definition at line 1285 of file wxlstate.h.
bool wxLuaState::operator== (const wxLuaState & wxlState) const
Definition at line 1280 of file wxlstate.h.
int wxLuaState::PushwxArrayIntTable (const wxArrayInt & intArray)
Definition at line 3276 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_pushwxArrayInttable().
int wxLuaState::PushwxArrayStringTable (const wxArrayString & strArray)
Definition at line 3270 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_pushwxArrayStringtable().
bool wxLuaState::RegisterBinding (wxLuaBinding * binding)
Definition at line 2847 of file wxlstate.cpp.
References wxLuaBinding::InitAllBindings(), lua_Pop(), Ok(), and wxLuaBinding::RegisterBinding().
bool wxLuaState::RegisterBindings ()
Definition at line 2860 of file wxlstate.cpp.
References wxLuaBinding::GetBindingList(), wxLuaBinding::InitAllBindings(), lua_Pop(), Ok(), and wxLuaBinding::RegisterBinding().
Referenced by Create().
void wxLuaState::RegisterFunction (lua_CFunction func, const char * funcName)
Definition at line 2841 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
Referenced by Create().
bool wxLuaState::RemoveDerivedMethods (void * obj_ptr) const
Definition at line 3312 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_removederivedmethods().
bool wxLuaState::RemoveTrackedEventCallback (wxLuaEventCallback * callback)
Definition at line 3014 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_lreg_evtcallbacks_key.
Referenced by wxLuaEventCallback::~wxLuaEventCallback().
bool wxLuaState::RemoveTrackedWinDestroyCallback (wxLuaWinDestroyCallback * callback)
Definition at line 3073 of file wxlstate.cpp.
References wxLuaWinDestroyCallback::GetWindow(), M_WXLSTATEDATA, Ok(), and wxlua_lreg_windestroycallbacks_key.
Referenced by wxLuaWinDestroyCallback::~wxLuaWinDestroyCallback().
void wxLuaState::RemoveTrackedWindow (wxWindow * win)
Definition at line 2975 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaW_removetrackedwindow().
Referenced by wxLuaWinDestroyCallback::OnDestroy(), and wxLuaWinDestroyCallback::~wxLuaWinDestroyCallback().
int wxLuaState::RunBuffer (const char buf[], size_t size, const wxString & name = wxT("= lua"), int nresults = 0)
Definition at line 2639 of file wxlstate.cpp.
References lua_GetTop(), lua_SetTop(), luaL_LoadBuffer(), LuaPCall(), M_WXLSTATEDATA, Ok(), SendLuaErrorEvent(), and wx2lua().
Referenced by RunString().
int wxLuaState::RunFile (const wxString & fileName, int nresults = 0)
Definition at line 2609 of file wxlstate.cpp.
References lua_GetTop(), lua_SetTop(), luaL_LoadFile(), LuaPCall(), M_WXLSTATEDATA, Ok(), SendLuaErrorEvent(), and wx2lua().
int wxLuaState::RunString (const wxString & script, const wxString & name = wxEmptyString, int nresults = 0)
Definition at line 2633 of file wxlstate.cpp.
References wxLuaCharBuffer::GetData(), wxLuaCharBuffer::Length(), and RunBuffer().
bool wxLuaState::SendEvent (wxLuaEvent & event) const
Definition at line 2594 of file wxlstate.cpp.
References M_WXLSTATEDATA.
Referenced by Create(), SendLuaErrorEvent(), wxlua_debugHookFunction(), and wxlua_printFunction().
bool wxLuaState::SendLuaErrorEvent (int status, int top)
Definition at line 2712 of file wxlstate.cpp.
References GetId(), GetLuaState(), Ok(), SendEvent(), and wxlua_errorinfo().
Referenced by LuaPCall(), RunBuffer(), and RunFile().
void wxLuaState::SetCallBaseClassFunction (bool call_base)
Definition at line 2926 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_setcallbaseclassfunction().
bool wxLuaState::SetDerivedMethod (void * obj_ptr, const char * method_name, wxLuaObject * wxlObj)
Definition at line 3300 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_setderivedmethod().
void wxLuaState::SetEventHandler (wxEvtHandler * evtHandler)
Definition at line 2572 of file wxlstate.cpp.
References M_WXLSTATEDATA.
void wxLuaState::SetId (wxWindowID id)
Definition at line 2583 of file wxlstate.cpp.
References M_WXLSTATEDATA.
void wxLuaState::SetInEventType (wxEventType eventType)
Definition at line 2732 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_setwxeventtype().
void wxLuaState::SetLastLuaDebugHookTime (unsigned long t)
Definition at line 2833 of file wxlstate.cpp.
References M_WXLSTATEDATA, and Ok().
void wxLuaState::SetLuaDebugHook (int hook = LUA_MASKCALL|LUA_MASKRET|LUA_MASKLINE|LUA_MASKCOUNT, int count = 1000, int yield_ms = 100, bool send_debug_evt = false)
Definition at line 2793 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_debugHookFunction().
Referenced by ClearDebugHookBreak().
void wxLuaState::wxlua_Error (const char * errorMsg) const
Definition at line 3118 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_error().
Referenced by wxLuaEventCallback::OnEvent(), and wxlua_debugHookFunction().
void * wxLuaState::wxlua_ToUserdata (int stack_idx, bool null_ptr = false) const
Definition at line 3124 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxlua_touserdata().
bool wxLuaState::wxluaR_GetRef (int wxlref_index, void * lightuserdata_reg_key)
Definition at line 3145 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaR_getref().
Referenced by wxLuaDebugTarget::EvaluateExpr(), and wxLuaEventCallback::OnEvent().
int wxLuaState::wxluaR_Ref (int stack_idx, void * lightuserdata_reg_key)
Definition at line 3133 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaR_ref().
Referenced by wxLuaDebugTarget::EvaluateExpr(), and wxLuaObject::SetObject().
bool wxLuaState::wxluaR_Unref (int wxlref_index, void * lightuserdata_reg_key)
Definition at line 3139 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaR_unref().
Referenced by wxLuaDebugTarget::EvaluateExpr(), wxLuaDebugTarget::HandleDebuggerCmd(), wxLuaWinDestroyCallback::OnDestroy(), wxLuaObject::SetObject(), wxLuaEventCallback::~wxLuaEventCallback(), and wxLuaObject::~wxLuaObject().
int wxLuaState::wxluaT_NewMetatable (int wxl_type)
Definition at line 3153 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), WXLUA_TUNKNOWN, and wxluaT_newmetatable().
bool wxLuaState::wxluaT_PushUserDataType (const void * obj_ptr, int wxl_type, bool track)
Definition at line 3171 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaT_pushuserdatatype().
Referenced by wxLuaEventCallback::OnEvent().
bool wxLuaState::wxluaT_SetMetatable (int wxl_type)
Definition at line 3159 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), and wxluaT_setmetatable().
int wxLuaState::wxluaT_Type (int stack_idx) const
Definition at line 3165 of file wxlstate.cpp.
References M_WXLSTATEDATA, Ok(), WXLUA_TUNKNOWN, and wxluaT_type().
Member Data Documentation
wxHashMapLuaState wxLuaState::s_wxHashMapLuaState [static]
Definition at line 759 of file wxlstate.h.
Referenced by wxLuaStateRefData::CloseLuaState(), Create(), and GetDerivedMethodState().
bool wxLuaState::sm_wxAppMainLoop_will_run = false [static]
Definition at line 774 of file wxlstate.h.
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxlua/include/wxlstate.h
/mnt/share/devel/lua/wxLua/modules/wxlua/src/wxlstate.cpp