wxLua: wxLuaDebugItem Class Reference
wxLuaDebugItem Class Reference
#include <wxldebug.h>
Public Member Functions
wxLuaDebugItem (const wxLuaDebugItem &debugDataItem)
wxLuaDebugItem (const wxString &itemKey, int itemKeyType, const wxString &itemValue, int itemValueType, const wxString &itemSource, int lua_ref, int idx=0, int flag=0)
wxString GetKey () const
int GetKeyType () const
wxString GetKeyTypeString () const
wxString GetValue () const
int GetValueType () const
wxString GetValueTypeString () const
wxString GetSource () const
int GetRef () const
int GetIndex () const
int GetFlag () const
bool GetFlagBit (int mask) const
bool GetRefPtr (long &ptr) const
void SetFlag (int flag)
void SetFlagBit (int bit, bool set)
void SetRef (int lua_ref)
wxString ToString () const
Public Attributes
wxString m_itemKey
int m_itemKeyType
wxString m_itemValue
int m_itemValueType
wxString m_itemSource
int m_lua_ref
int m_index
int m_flag
Detailed Description
Definition at line 39 of file wxldebug.h.
Constructor & Destructor Documentation
wxLuaDebugItem::wxLuaDebugItem (const wxLuaDebugItem & debugDataItem)
Definition at line 39 of file wxldebug.cpp.
wxLuaDebugItem::wxLuaDebugItem (const wxString & itemKey, int itemKeyType, const wxString & itemValue, int itemValueType, const wxString & itemSource, int lua_ref, int idx = 0, int flag = 0)
Definition at line 28 of file wxldebug.cpp.
Member Function Documentation
int wxLuaDebugItem::GetFlag () const
Definition at line 63 of file wxldebug.h.
Referenced by wxLuaSocketBase::WriteDebugData().
bool wxLuaDebugItem::GetFlagBit (int mask) const
Definition at line 64 of file wxldebug.h.
References WXLUA_HASBIT.
Referenced by wxLuaStackDialog::CollapseItem(), wxLuaStackDialog::ExpandItem(), wxLuaStackDialog::ExpandItemChildren(), wxLuaStackDialog::FillTableEntry(), wxLuaStackDialog::GetItemImage(), GetRefPtr(), wxLuaStackListCtrl::OnGetItemColumnImage(), wxLuaStackDialog::OnListItem(), and wxLuaDebugData::SortFunction().
int wxLuaDebugItem::GetIndex () const
Definition at line 62 of file wxldebug.h.
Referenced by wxLuaStackDialog::ExpandItem(), wxLuaStackDialog::FillStackCombobox(), and wxLuaSocketBase::WriteDebugData().
wxString wxLuaDebugItem::GetKey () const
Definition at line 49 of file wxldebug.h.
Referenced by wxLuaStackDialog::FillStackCombobox(), wxLuaStackDialog::FillTableEntry(), wxLuaStackDialog::GetItemText(), and wxLuaSocketBase::WriteDebugData().
int wxLuaDebugItem::GetKeyType () const
Definition at line 50 of file wxldebug.h.
Referenced by wxLuaSocketBase::WriteDebugData().
wxString wxLuaDebugItem::GetKeyTypeString () const
Definition at line 51 of file wxldebug.h.
References wxluaT_typename().
Referenced by wxLuaStackDialog::GetItemText().
int wxLuaDebugItem::GetRef () const
Definition at line 61 of file wxldebug.h.
Referenced by wxLuaStackDialog::ExpandItem(), wxLuaStackDialog::FillTableEntry(), and wxLuaSocketBase::WriteDebugData().
bool wxLuaDebugItem::GetRefPtr (long & ptr) const
Definition at line 48 of file wxldebug.cpp.
References GetFlagBit(), m_itemKey, m_itemValue, WXLUA_DEBUGITEM_KEY_REF, and WXLUA_DEBUGITEM_VALUE_REF.
Referenced by wxLuaStackDialog::CollapseItem(), and wxLuaStackDialog::ExpandItem().
wxString wxLuaDebugItem::GetSource () const
Definition at line 59 of file wxldebug.h.
Referenced by wxLuaSocketBase::WriteDebugData().
wxString wxLuaDebugItem::GetValue () const
Definition at line 54 of file wxldebug.h.
Referenced by wxLuaStackDialog::GetItemText(), and wxLuaSocketBase::WriteDebugData().
int wxLuaDebugItem::GetValueType () const
Definition at line 55 of file wxldebug.h.
Referenced by wxLuaStackDialog::GetItemImage(), and wxLuaSocketBase::WriteDebugData().
wxString wxLuaDebugItem::GetValueTypeString () const
Definition at line 56 of file wxldebug.h.
References wxluaT_typename().
Referenced by wxLuaStackDialog::GetItemText().
void wxLuaDebugItem::SetFlag (int flag)
Definition at line 71 of file wxldebug.h.
void wxLuaDebugItem::SetFlagBit (int bit, bool set)
Definition at line 72 of file wxldebug.h.
References WXLUA_SETBIT.
Referenced by wxLuaStackDialog::CollapseItem(), and wxLuaStackDialog::ExpandItem().
void wxLuaDebugItem::SetRef (int lua_ref)
Definition at line 73 of file wxldebug.h.
wxString wxLuaDebugItem::ToString () const
Definition at line 76 of file wxldebug.h.
Member Data Documentation
int wxLuaDebugItem::m_flag
Definition at line 93 of file wxldebug.h.
int wxLuaDebugItem::m_index
Definition at line 92 of file wxldebug.h.
wxString wxLuaDebugItem::m_itemKey
Definition at line 86 of file wxldebug.h.
Referenced by GetRefPtr(), and wxLuaDebugData::SortFunction().
int wxLuaDebugItem::m_itemKeyType
Definition at line 87 of file wxldebug.h.
Referenced by wxLuaDebugData::SortFunction().
wxString wxLuaDebugItem::m_itemSource
Definition at line 90 of file wxldebug.h.
wxString wxLuaDebugItem::m_itemValue
Definition at line 88 of file wxldebug.h.
Referenced by GetRefPtr(), and wxLuaDebugData::SortFunction().
int wxLuaDebugItem::m_itemValueType
Definition at line 89 of file wxldebug.h.
Referenced by wxLuaDebugData::SortFunction().
int wxLuaDebugItem::m_lua_ref
Definition at line 91 of file wxldebug.h.
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluadebug/include/wxldebug.h
/mnt/share/devel/lua/wxLua/modules/wxluadebug/src/wxldebug.cpp