wxLua: wxLuaDebuggerStackDialog Class Reference
wxLuaDebuggerStackDialog Class Reference
#include <wxldserv.h>
Public Member Functions
wxLuaDebuggerStackDialog (wxLuaDebuggerBase *luaDebugger, wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("wxLua Stack"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~wxLuaDebuggerStackDialog ()
virtual void EnumerateStack ()
virtual void EnumerateStackEntry (int nEntry)
virtual void EnumerateTable (int nRef, int nEntry, long lc_item)
virtual void EnumerateGlobalData (long lc_item)
Public Attributes
wxLuaDebuggerBase * m_luaDebugger
Detailed Description
Definition at line 97 of file wxldserv.h.
Constructor & Destructor Documentation
wxLuaDebuggerStackDialog::wxLuaDebuggerStackDialog (wxLuaDebuggerBase * luaDebugger, wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxT("wxLua Stack"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Definition at line 92 of file wxldserv.cpp.
References wxNullLuaState.
wxLuaDebuggerStackDialog::~wxLuaDebuggerStackDialog () [virtual]
Definition at line 103 of file wxldserv.cpp.
References wxLuaDebuggerBase::ClearDebugReferences(), and m_luaDebugger.
Member Function Documentation
void wxLuaDebuggerStackDialog::EnumerateGlobalData (long lc_item) [virtual]
Reimplemented from wxLuaStackDialog.
Definition at line 130 of file wxldserv.cpp.
References wxLuaDebuggerBase::EnumerateTable(), and m_luaDebugger.
void wxLuaDebuggerStackDialog::EnumerateStack () [virtual]
Reimplemented from wxLuaStackDialog.
Definition at line 109 of file wxldserv.cpp.
References wxLuaDebuggerBase::EnumerateStack(), and m_luaDebugger.
void wxLuaDebuggerStackDialog::EnumerateStackEntry (int nEntry) [virtual]
Reimplemented from wxLuaStackDialog.
Definition at line 116 of file wxldserv.cpp.
References wxLuaDebuggerBase::EnumerateStackEntry(), and m_luaDebugger.
void wxLuaDebuggerStackDialog::EnumerateTable (int nRef, int nEntry, long lc_item) [virtual]
Reimplemented from wxLuaStackDialog.
Definition at line 123 of file wxldserv.cpp.
References wxLuaDebuggerBase::EnumerateTable(), and m_luaDebugger.
Member Data Documentation
wxLuaDebuggerBase* wxLuaDebuggerStackDialog::m_luaDebugger
Definition at line 119 of file wxldserv.h.
Referenced by EnumerateGlobalData(), EnumerateStack(), EnumerateStackEntry(), EnumerateTable(), and ~wxLuaDebuggerStackDialog().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluasocket/include/wxldserv.h
/mnt/share/devel/lua/wxLua/modules/wxluasocket/src/wxldserv.cpp