wxLua: wxLuaWinDestroyCallback Class Reference
wxLuaWinDestroyCallback Class Reference
#include <wxlcallb.h>
Public Member Functions
wxLuaWinDestroyCallback (const wxLuaState &state, wxWindow *win)
virtual ~wxLuaWinDestroyCallback ()
void ClearwxLuaState ()
wxLuaState GetwxLuaState () const
wxWindow * GetWindow () const
bool Ok () const
wxString GetInfo () const
void OnAllDestroyEvents (wxWindowDestroyEvent &event)
virtual void OnDestroy (wxWindowDestroyEvent &event)
Protected Attributes
wxLuaState m_wxlState
wxWindow * m_window
Detailed Description
Definition at line 106 of file wxlcallb.h.
Constructor & Destructor Documentation
wxLuaWinDestroyCallback::wxLuaWinDestroyCallback (const wxLuaState & state, wxWindow * win)
Definition at line 186 of file wxlcallb.cpp.
References OnAllDestroyEvents().
wxLuaWinDestroyCallback::~wxLuaWinDestroyCallback () [virtual]
Definition at line 201 of file wxlcallb.cpp.
References m_window, m_wxlState, wxLuaState::Ok(), wxLuaState::RemoveTrackedWinDestroyCallback(), and wxLuaState::RemoveTrackedWindow().
Member Function Documentation
void wxLuaWinDestroyCallback::ClearwxLuaState ()
Definition at line 210 of file wxlcallb.cpp.
References m_wxlState.
Referenced by wxLuaStateRefData::ClearCallbacks().
wxString wxLuaWinDestroyCallback::GetInfo () const
Definition at line 215 of file wxlcallb.cpp.
References m_window.
Referenced by wxLuaDebugData::EnumerateTable(), and wxLuaState::GetTrackedWinDestroyCallbackInfo().
wxWindow* wxLuaWinDestroyCallback::GetWindow () const
Definition at line 116 of file wxlcallb.h.
Referenced by wxLuaState::AddTrackedWinDestroyCallback(), and wxLuaState::RemoveTrackedWinDestroyCallback().
wxLuaState wxLuaWinDestroyCallback::GetwxLuaState () const
Definition at line 115 of file wxlcallb.h.
bool wxLuaWinDestroyCallback::Ok () const
Definition at line 120 of file wxlcallb.h.
void wxLuaWinDestroyCallback::OnAllDestroyEvents (wxWindowDestroyEvent & event)
Definition at line 226 of file wxlcallb.cpp.
References m_window, and OnDestroy().
Referenced by wxLuaWinDestroyCallback().
void wxLuaWinDestroyCallback::OnDestroy (wxWindowDestroyEvent & event) [virtual]
Definition at line 238 of file wxlcallb.cpp.
References wxLuaEventCallback::ClearwxLuaState(), wxLuaEventCallback::GetEvtHandler(), wxLuaEventCallback::GetLuaFuncRef(), wxLuaState::GetLuaState(), m_window, m_wxlState, wxLuaState::Ok(), wxLuaState::RemoveTrackedWindow(), wxlua_lreg_evtcallbacks_key, wxlua_lreg_refs_key, wxlua_removederivedmethods(), wxluaO_untrackweakobject(), and wxLuaState::wxluaR_Unref().
Referenced by OnAllDestroyEvents().
Member Data Documentation
wxWindow* wxLuaWinDestroyCallback::m_window [protected]
Definition at line 137 of file wxlcallb.h.
Referenced by GetInfo(), OnAllDestroyEvents(), OnDestroy(), and ~wxLuaWinDestroyCallback().
wxLuaState wxLuaWinDestroyCallback::m_wxlState [protected]
Definition at line 136 of file wxlcallb.h.
Referenced by ClearwxLuaState(), OnDestroy(), and ~wxLuaWinDestroyCallback().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxlua/include/wxlcallb.h
/mnt/share/devel/lua/wxLua/modules/wxlua/src/wxlcallb.cpp