wxLua: wxLuaStateRefData Class Reference
wxLuaStateRefData Class Reference
#include <wxlstate.h>
Public Member Functions
wxLuaStateRefData (bool create_data=true)
virtual ~wxLuaStateRefData ()
bool CloseLuaState (bool force)
void ClearCallbacks ()
Public Attributes
lua_State * m_lua_State
bool m_lua_State_static
bool m_lua_State_coroutine
wxLuaStateData * m_wxlStateData
bool m_own_stateData
Detailed Description
Definition at line 632 of file wxlstate.h.
Constructor & Destructor Documentation
wxLuaStateRefData::wxLuaStateRefData (bool create_data = true)
Definition at line 2129 of file wxlstate.cpp.
References m_own_stateData, and m_wxlStateData.
wxLuaStateRefData::~wxLuaStateRefData () [virtual]
Definition at line 2143 of file wxlstate.cpp.
References CloseLuaState(), m_lua_State, m_lua_State_static, m_own_stateData, and m_wxlStateData.
Member Function Documentation
void wxLuaStateRefData::ClearCallbacks ()
Definition at line 2267 of file wxlstate.cpp.
References wxLuaWinDestroyCallback::ClearwxLuaState(), wxLuaEventCallback::ClearwxLuaState(), m_lua_State, wxlua_lreg_createtable(), wxlua_lreg_evtcallbacks_key, and wxlua_lreg_windestroycallbacks_key.
Referenced by CloseLuaState().
bool wxLuaStateRefData::CloseLuaState (bool force)
Definition at line 2153 of file wxlstate.cpp.
References ClearCallbacks(), wxLuaStateData::m_is_closing, m_lua_State, m_lua_State_coroutine, m_lua_State_static, m_wxlStateData, wxLuaState::s_wxHashMapLuaState, wxlua_lreg_createtable(), wxlua_lreg_debug_refs_key, wxlua_lreg_refs_key, wxlua_lreg_topwindows_key, wxlua_lreg_wxluastatedata_key, and wxLuaCleanupWindows().
Referenced by ~wxLuaStateRefData().
Member Data Documentation
lua_State* wxLuaStateRefData::m_lua_State
Definition at line 646 of file wxlstate.h.
Referenced by ClearCallbacks(), CloseLuaState(), wxLuaState::GetwxLuaState(), and ~wxLuaStateRefData().
bool wxLuaStateRefData::m_lua_State_coroutine
Definition at line 648 of file wxlstate.h.
Referenced by CloseLuaState(), and wxLuaState::GetwxLuaState().
bool wxLuaStateRefData::m_lua_State_static
Definition at line 647 of file wxlstate.h.
Referenced by CloseLuaState(), wxLuaState::GetwxLuaState(), and ~wxLuaStateRefData().
bool wxLuaStateRefData::m_own_stateData
Definition at line 651 of file wxlstate.h.
Referenced by wxLuaState::GetwxLuaState(), wxLuaStateRefData(), and ~wxLuaStateRefData().
wxLuaStateData* wxLuaStateRefData::m_wxlStateData
Definition at line 650 of file wxlstate.h.
Referenced by CloseLuaState(), wxLuaState::GetwxLuaState(), wxLuaStateRefData(), and ~wxLuaStateRefData().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxlua/include/wxlstate.h
/mnt/share/devel/lua/wxLua/modules/wxlua/src/wxlstate.cpp