wxLua: wxLuaDebuggerCServer Class Reference
wxLuaDebuggerCServer Class Reference
#include <wxldserv.h>
Classes
class LuaThread
Public Member Functions
wxLuaDebuggerCServer (int port_number)
virtual ~wxLuaDebuggerCServer ()
virtual bool StartServer ()
virtual bool StopServer ()
virtual long StartClient ()
virtual wxLuaSocketBase * GetSocketBase ()
virtual wxString GetSocketErrorMsg ()
void ThreadFunction ()
bool WaitForConnect (int timeOut)
Public Attributes
wxLuaSocket * m_serverSocket
wxLuaSocket * m_acceptedSocket
wxLuaDebuggerCServer::LuaThread * m_pThread
bool m_shutdown
Detailed Description
Definition at line 278 of file wxldserv.h.
Constructor & Destructor Documentation
wxLuaDebuggerCServer::wxLuaDebuggerCServer (int port_number)
Definition at line 669 of file wxldserv.cpp.
wxLuaDebuggerCServer::~wxLuaDebuggerCServer () [virtual]
Definition at line 677 of file wxldserv.cpp.
References StopServer().
Member Function Documentation
virtual wxLuaSocketBase* wxLuaDebuggerCServer::GetSocketBase () [virtual]
Implements wxLuaDebuggerBase.
Definition at line 309 of file wxldserv.h.
wxString wxLuaDebuggerCServer::GetSocketErrorMsg () [virtual]
Implements wxLuaDebuggerBase.
Definition at line 873 of file wxldserv.cpp.
References wxLuaSocketBase::GetErrorMsg(), m_acceptedSocket, and m_serverSocket.
long wxLuaDebuggerCServer::StartClient () [virtual]
Reimplemented from wxLuaDebuggerBase.
Definition at line 717 of file wxldserv.cpp.
References wxLuaDebuggerBase::m_debuggeeProcessID, m_pThread, m_serverSocket, and m_shutdown.
bool wxLuaDebuggerCServer::StartServer () [virtual]
Implements wxLuaDebuggerBase.
Definition at line 682 of file wxldserv.cpp.
References wxLuaSocketBase::GetErrorMsg(), wxLuaCSocket::Listen(), wxLuaSocketBase::m_name, wxLuaDebuggerBase::m_port_number, m_pThread, m_serverSocket, m_shutdown, and wxLuaDebuggerEvent::SetMessage().
bool wxLuaDebuggerCServer::StopServer () [virtual]
Implements wxLuaDebuggerBase.
Definition at line 728 of file wxldserv.cpp.
References wxLuaCSocket::Connect(), wxLuaSocketBase::GetErrorMsg(), wxLuaDebuggerBase::GetNetworkName(), m_acceptedSocket, wxLuaSocketBase::m_name, wxLuaDebuggerBase::m_port_number, m_pThread, m_serverSocket, m_shutdown, wxLuaDebuggerBase::Reset(), SD_BOTH, wxLuaDebuggerEvent::SetMessage(), wxLuaCSocket::Shutdown(), and wxMilliSleep.
Referenced by ~wxLuaDebuggerCServer().
void wxLuaDebuggerCServer::ThreadFunction ()
Definition at line 800 of file wxldserv.cpp.
References wxLuaCSocket::Accept(), wxLuaSocketBase::GetErrorMsg(), wxLuaDebuggerBase::HandleDebuggeeEvent(), m_acceptedSocket, wxLuaDebuggerBase::m_acceptSockCritSect, wxLuaSocketBase::m_name, m_pThread, m_serverSocket, m_shutdown, wxLuaSocketBase::ReadCmd(), wxLuaDebuggerEvent::SetMessage(), and wxLUASOCKET_DEBUGGEE_EVENT_EXIT.
Referenced by wxLuaDebuggerCServer::LuaThread::Entry().
bool wxLuaDebuggerCServer::WaitForConnect (int timeOut)
Member Data Documentation
wxLuaSocket* wxLuaDebuggerCServer::m_acceptedSocket
Definition at line 322 of file wxldserv.h.
Referenced by GetSocketErrorMsg(), StopServer(), and ThreadFunction().
wxLuaDebuggerCServer::LuaThread* wxLuaDebuggerCServer::m_pThread
Definition at line 323 of file wxldserv.h.
Referenced by StartClient(), StartServer(), StopServer(), and ThreadFunction().
wxLuaSocket* wxLuaDebuggerCServer::m_serverSocket
Definition at line 321 of file wxldserv.h.
Referenced by GetSocketErrorMsg(), StartClient(), StartServer(), StopServer(), and ThreadFunction().
bool wxLuaDebuggerCServer::m_shutdown
Definition at line 324 of file wxldserv.h.
Referenced by StartClient(), StartServer(), StopServer(), and ThreadFunction().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluasocket/include/wxldserv.h
/mnt/share/devel/lua/wxLua/modules/wxluasocket/src/wxldserv.cpp