wxLua: wxLuaDebugData Class Reference
wxLuaDebugData Class Reference
#include <wxldebug.h>
Public Member Functions
wxLuaDebugData (bool create)
wxLuaDebugData (const wxLuaDebugData &debugData)
virtual ~wxLuaDebugData ()
bool Ok () const
wxLuaDebugItemArray * GetArray ()
const wxLuaDebugItemArray * GetArray () const
size_t GetCount () const
wxLuaDebugItem * Item (size_t index) const
void Add (wxLuaDebugItem *item)
int EnumerateStack (const wxLuaState &wxlState)
int EnumerateStackEntry (const wxLuaState &wxlState, int stack_frame, wxArrayInt &references)
int EnumerateTable (const wxLuaState &wxlState, int nRef, int nEntry, wxArrayInt &references)
wxLuaDebugData Copy () const
int RefTable (lua_State *L, int stack_idx, int *flag_type, int extra_flag, wxArrayInt &references)
bool operator== (const wxLuaDebugData &debugData) const
bool operator!= (const wxLuaDebugData &debugData) const
wxLuaDebugData & operator= (const wxLuaDebugData &debugData)
Static Public Member Functions
static int GetTypeValue (const wxLuaState &wxlState, int stack_idx, int *wxl_type, wxString &value)
static wxString GetTableInfo (const wxLuaState &wxlState, int stack_idx)
static wxString GetUserDataInfo (const wxLuaState &wxlState, int stack_idx, bool full_userdata)
static int SortFunction (wxLuaDebugItem *elem1, wxLuaDebugItem *elem2)
Detailed Description
Definition at line 110 of file wxldebug.h.
Constructor & Destructor Documentation
wxLuaDebugData::wxLuaDebugData (bool create)
Definition at line 84 of file wxldebug.cpp.
wxLuaDebugData::wxLuaDebugData (const wxLuaDebugData & debugData)
Definition at line 114 of file wxldebug.h.
virtual wxLuaDebugData::~wxLuaDebugData () [virtual]
Definition at line 116 of file wxldebug.h.
Member Function Documentation
void wxLuaDebugData::Add (wxLuaDebugItem * item)
Definition at line 111 of file wxldebug.cpp.
References M_DEBUGREFDATA.
Referenced by Copy(), EnumerateStack(), EnumerateStackEntry(), EnumerateTable(), and wxLuaSocketBase::ReadDebugData().
wxLuaDebugData wxLuaDebugData::Copy () const
Definition at line 118 of file wxldebug.cpp.
References Add(), GetCount(), M_DEBUGREFDATA, and wxNullLuaDebugData.
int wxLuaDebugData::EnumerateStack (const wxLuaState & wxlState)
Definition at line 171 of file wxldebug.cpp.
References Add(), wxLuaState::GetLuaState(), INIT_LUA_DEBUG, lua2wx(), M_DEBUGREFDATA, wxLuaState::Ok(), WXLUA_DEBUGITEM_LOCALS, and WXLUA_TNONE.
Referenced by wxLuaDebugTarget::EnumerateStack(), and wxLuaStackDialog::EnumerateStack().
int wxLuaDebugData::EnumerateStackEntry (const wxLuaState & wxlState, int stack_frame, wxArrayInt & references)
Definition at line 214 of file wxldebug.cpp.
References Add(), wxLuaState::GetLuaState(), GetTypeValue(), INIT_LUA_DEBUG, lua2wx(), M_DEBUGREFDATA, wxLuaState::Ok(), and WXLUA_TNONE.
Referenced by wxLuaDebugTarget::EnumerateStackEntry(), and wxLuaStackDialog::EnumerateStackEntry().
int wxLuaDebugData::EnumerateTable (const wxLuaState & wxlState, int nRef, int nEntry, wxArrayInt & references)
Definition at line 277 of file wxldebug.cpp.
References Add(), wxLuaBinding::GetBindingName(), wxLuaWinDestroyCallback::GetInfo(), wxLuaEventCallback::GetInfo(), wxLuaBinding::GetLuaNamespace(), wxLuaState::GetLuaState(), GetTypeValue(), M_DEBUGREFDATA, wxLuaState::Ok(), RefTable(), WXLUA_DEBUGITEM_KEY_REF, WXLUA_DEBUGITEM_VALUE_REF, wxlua_lreg_classes_key, wxlua_lreg_debug_refs_key, wxlua_lreg_evtcallbacks_key, wxlua_lreg_gcobjects_key, wxlua_lreg_regtable_key, wxlua_lreg_topwindows_key, wxlua_lreg_types_key, wxlua_lreg_windestroycallbacks_key, wxlua_lreg_wxluabindings_key, wxlua_metatable_type_key, wxlua_metatable_wxluabindclass_key, WXLUA_TNONE, WXLUA_TTABLE, wxLuaBindClassString(), wxluaR_getref(), and wxluaT_typename().
Referenced by wxLuaStackDialog::EnumerateGlobalData(), wxLuaDebugTarget::EnumerateTable(), wxLuaStackDialog::EnumerateTable(), and wxLuaStackDialog::FillStackEntry().
const wxLuaDebugItemArray * wxLuaDebugData::GetArray () const
Definition at line 95 of file wxldebug.cpp.
References M_DEBUGREFDATA.
wxLuaDebugItemArray * wxLuaDebugData::GetArray ()
Definition at line 90 of file wxldebug.cpp.
References M_DEBUGREFDATA.
size_t wxLuaDebugData::GetCount () const
Definition at line 101 of file wxldebug.cpp.
References M_DEBUGREFDATA.
Referenced by Copy(), wxLuaStackDialog::FillStackCombobox(), wxLuaStackDialog::FillStackEntry(), wxLuaStackDialog::FillTableEntry(), and wxLuaSocketBase::WriteDebugData().
wxString wxLuaDebugData::GetTableInfo (const wxLuaState & wxlState, int stack_idx) [static]
Definition at line 595 of file wxldebug.cpp.
References wxLuaState::GetLuaState(), wxLuaState::Ok(), wxlua_iswxuserdatatype, and wxluaT_type().
Referenced by GetTypeValue().
int wxLuaDebugData::GetTypeValue (const wxLuaState & wxlState, int stack_idx, int * wxl_type, wxString & value) [static]
Definition at line 513 of file wxldebug.cpp.
References wxLuaState::GetLuaState(), GetTableInfo(), GetUserDataInfo(), lua2wx(), wxLuaState::Ok(), wxlua_luatowxluatype(), and WXLUA_TCFUNCTION.
Referenced by wxLuaCheckStack::DumpStack(), wxLuaCheckStack::DumpTable(), EnumerateStackEntry(), EnumerateTable(), and wxLuaDebugTarget::EvaluateExpr().
wxString wxLuaDebugData::GetUserDataInfo (const wxLuaState & wxlState, int stack_idx, bool full_userdata) [static]
Definition at line 615 of file wxldebug.cpp.
References wxLuaState::GetLuaState(), lua2wx(), wxLuaState::Ok(), wxlua_iswxuserdatatype, wxlua_lreg_callbaseclassfunc_key, wxlua_lreg_classes_key, wxlua_lreg_debug_refs_key, wxlua_lreg_derivedmethods_key, wxlua_lreg_evtcallbacks_key, wxlua_lreg_gcobjects_key, wxlua_lreg_refs_key, wxlua_lreg_regtable_key, wxlua_lreg_topwindows_key, wxlua_lreg_types_key, wxlua_lreg_weakobjects_key, wxlua_lreg_windestroycallbacks_key, wxlua_lreg_wxeventtype_key, wxlua_lreg_wxluabindings_key, wxlua_lreg_wxluastate_key, wxlua_lreg_wxluastatedata_key, wxlua_metatable_type_key, wxlua_metatable_wxluabindclass_key, wxluaT_type(), and wxluaT_typename().
Referenced by GetTypeValue().
wxLuaDebugItem * wxLuaDebugData::Item (size_t index) const
Definition at line 106 of file wxldebug.cpp.
References M_DEBUGREFDATA.
Referenced by wxLuaStackDialog::FillStackCombobox(), wxLuaStackDialog::FillTableEntry(), and wxLuaSocketBase::WriteDebugData().
bool wxLuaDebugData::Ok () const
Definition at line 119 of file wxldebug.h.
Referenced by wxLuaStackDialog::CollapseItem(), wxLuaStackDialog::ExpandItem(), wxLuaStackDialog::FillStackCombobox(), wxLuaStackDialog::FillStackEntry(), and wxLuaStackDialog::FillTableEntry().
bool wxLuaDebugData::operator!= (const wxLuaDebugData & debugData) const
Definition at line 171 of file wxldebug.h.
wxLuaDebugData& wxLuaDebugData::operator= (const wxLuaDebugData & debugData)
Definition at line 174 of file wxldebug.h.
bool wxLuaDebugData::operator== (const wxLuaDebugData & debugData) const
Definition at line 169 of file wxldebug.h.
int wxLuaDebugData::RefTable (lua_State * L, int stack_idx, int * flag_type, int extra_flag, wxArrayInt & references)
Definition at line 493 of file wxldebug.cpp.
References WXLUA_DEBUGITEM_IS_REFED, wxlua_lreg_debug_refs_key, and wxluaR_ref().
Referenced by EnumerateTable().
int wxLuaDebugData::SortFunction (wxLuaDebugItem * elem1, wxLuaDebugItem * elem2) [static]
Definition at line 135 of file wxldebug.cpp.
References wxLuaDebugItem::GetFlagBit(), wxLuaDebugItem::m_itemKey, wxLuaDebugItem::m_itemKeyType, wxLuaDebugItem::m_itemValue, wxLuaDebugItem::m_itemValueType, WXLUA_DEBUGITEM_KEY_REF, and WXLUA_TNUMBER.
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluadebug/include/wxldebug.h
/mnt/share/devel/lua/wxLua/modules/wxluadebug/src/wxldebug.cpp