wxLua: wxLuaDebuggerBase Class Reference
wxLuaDebuggerBase Class Reference
#include <wxldserv.h>
Public Member Functions
wxLuaDebuggerBase (int port_number)
virtual ~wxLuaDebuggerBase ()
virtual bool StartServer ()=0
virtual bool StopServer ()=0
virtual long StartClient ()
bool AddBreakPoint (const wxString &fileName, int lineNumber)
bool RemoveBreakPoint (const wxString &fileName, int lineNumber)
bool DisableBreakPoint (const wxString &fileName, int lineNumber)
bool EnableBreakPoint (const wxString &fileName, int lineNumber)
bool ClearAllBreakPoints ()
bool Run (const wxString &fileName, const wxString &buffer)
bool Step ()
bool StepOver ()
bool StepOut ()
bool Continue ()
bool Break ()
bool Reset ()
bool EnumerateStack ()
bool EnumerateStackEntry (int stackEntry)
bool EnumerateTable (int tableRef, int nIndex, long nItemNode)
bool ClearDebugReferences ()
bool EvaluateExpr (int exprRef, const wxString &strExpression)
virtual int HandleDebuggeeEvent (int event_type)
virtual wxLuaSocketBase * GetSocketBase ()=0
virtual bool CheckSocketConnected (bool send_event=true, const wxString &msg=wxEmptyString)
virtual bool CheckSocketRead (bool read_ok, const wxString &msg=wxEmptyString)
virtual bool CheckSocketWrite (bool write_ok, const wxString &msg=wxEmptyString)
virtual wxString GetSocketErrorMsg ()=0
virtual void SendEvent (wxEvent &event)
wxLuaStackDialog * GetStackDialog ()
void SetStackDialog (wxLuaStackDialog *stackDialog)
bool DisplayStackDialog (wxWindow *parent, wxWindowID id=wxID_ANY)
void OnDebugStackEnum (wxLuaDebuggerEvent &event)
void OnDebugTableEnum (wxLuaDebuggerEvent &event)
void OnDebugStackEntryEnum (wxLuaDebuggerEvent &event)
void OnEndDebugeeProcess (wxProcessEvent &event)
int GetPortNumber () const
wxLuaDebuggerProcess * GetDebuggeeProcess ()
long GetDebuggeeProcessId () const
bool KillDebuggee ()
Static Public Member Functions
static void SetProgramName (const wxString &name)
static wxString GetProgramName ()
static void SetNetworkName (const wxString &name)
static wxString GetNetworkName ()
Public Attributes
int m_port_number
wxLuaStackDialog * m_stackDialog
wxLuaDebuggerProcess * m_debuggeeProcess
long m_debuggeeProcessID
wxCriticalSection m_acceptSockCritSect
wxCriticalSection m_processCritSect
Static Public Attributes
static wxString sm_programName
static wxString sm_networkName
Private Member Functions
DECLARE_EVENT_TABLE ()
Friends
class wxLuaDebuggerProcess
Detailed Description
Definition at line 154 of file wxldserv.h.
Constructor & Destructor Documentation
wxLuaDebuggerBase::wxLuaDebuggerBase (int port_number)
Definition at line 175 of file wxldserv.cpp.
wxLuaDebuggerBase::~wxLuaDebuggerBase () [virtual]
Definition at line 195 of file wxldserv.cpp.
References m_debuggeeProcess, m_debuggeeProcessID, and wxLuaDebuggerProcess::m_debugger.
Member Function Documentation
bool wxLuaDebuggerBase::AddBreakPoint (const wxString & fileName, int lineNumber)
Definition at line 228 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_ADD_BREAKPOINT.
bool wxLuaDebuggerBase::Break ()
Definition at line 308 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_DEBUG_BREAK.
bool wxLuaDebuggerBase::CheckSocketConnected (bool send_event = true, const wxString & msg = wxEmptyString) [virtual]
Definition at line 510 of file wxldserv.cpp.
References GetSocketBase(), SendEvent(), and wxLuaDebuggerEvent::SetMessage().
Referenced by AddBreakPoint(), Break(), ClearAllBreakPoints(), ClearDebugReferences(), Continue(), DisableBreakPoint(), EnableBreakPoint(), EnumerateStack(), EnumerateStackEntry(), EnumerateTable(), EvaluateExpr(), RemoveBreakPoint(), Reset(), Run(), Step(), StepOut(), and StepOver().
bool wxLuaDebuggerBase::CheckSocketRead (bool read_ok, const wxString & msg = wxEmptyString) [virtual]
Definition at line 537 of file wxldserv.cpp.
References GetSocketErrorMsg(), SendEvent(), and wxLuaDebuggerEvent::SetMessage().
Referenced by HandleDebuggeeEvent().
bool wxLuaDebuggerBase::CheckSocketWrite (bool write_ok, const wxString & msg = wxEmptyString) [virtual]
Definition at line 551 of file wxldserv.cpp.
References GetSocketErrorMsg(), SendEvent(), and wxLuaDebuggerEvent::SetMessage().
Referenced by AddBreakPoint(), Break(), ClearAllBreakPoints(), ClearDebugReferences(), Continue(), DisableBreakPoint(), EnableBreakPoint(), EnumerateStack(), EnumerateStackEntry(), EnumerateTable(), EvaluateExpr(), RemoveBreakPoint(), Reset(), Run(), Step(), StepOut(), and StepOver().
bool wxLuaDebuggerBase::ClearAllBreakPoints ()
Definition at line 264 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_CLEAR_ALL_BREAKPOINTS.
bool wxLuaDebuggerBase::ClearDebugReferences ()
Definition at line 347 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_CLEAR_DEBUG_REFERENCES.
Referenced by wxLuaDebuggerStackDialog::~wxLuaDebuggerStackDialog().
bool wxLuaDebuggerBase::Continue ()
Definition at line 301 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_DEBUG_CONTINUE.
wxLuaDebuggerBase::DECLARE_EVENT_TABLE () [private]
bool wxLuaDebuggerBase::DisableBreakPoint (const wxString & fileName, int lineNumber)
Definition at line 246 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_DISABLE_BREAKPOINT.
bool wxLuaDebuggerBase::DisplayStackDialog (wxWindow * parent, wxWindowID id = wxID_ANY)
Definition at line 566 of file wxldserv.cpp.
References m_stackDialog.
bool wxLuaDebuggerBase::EnableBreakPoint (const wxString & fileName, int lineNumber)
Definition at line 255 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_ENABLE_BREAKPOINT.
bool wxLuaDebuggerBase::EnumerateStack ()
Definition at line 322 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_ENUMERATE_STACK.
Referenced by wxLuaDebuggerStackDialog::EnumerateStack().
bool wxLuaDebuggerBase::EnumerateStackEntry (int stackEntry)
Definition at line 329 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_ENUMERATE_STACK_ENTRY.
Referenced by wxLuaDebuggerStackDialog::EnumerateStackEntry().
bool wxLuaDebuggerBase::EnumerateTable (int tableRef, int nIndex, long nItemNode)
Definition at line 337 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_ENUMERATE_TABLE_REF.
Referenced by wxLuaDebuggerStackDialog::EnumerateGlobalData(), and wxLuaDebuggerStackDialog::EnumerateTable().
bool wxLuaDebuggerBase::EvaluateExpr (int exprRef, const wxString & strExpression)
Definition at line 354 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_EVALUATE_EXPR.
wxLuaDebuggerProcess* wxLuaDebuggerBase::GetDebuggeeProcess ()
Definition at line 232 of file wxldserv.h.
long wxLuaDebuggerBase::GetDebuggeeProcessId () const
Definition at line 233 of file wxldserv.h.
static wxString wxLuaDebuggerBase::GetNetworkName () [static]
Definition at line 248 of file wxldserv.h.
Referenced by StartClient(), wxLuaDebuggerCServer::StopServer(), and wxLua_wxLuaDebuggerServer_GetNetworkName().
int wxLuaDebuggerBase::GetPortNumber () const
Definition at line 229 of file wxldserv.h.
static wxString wxLuaDebuggerBase::GetProgramName () [static]
Definition at line 241 of file wxldserv.h.
Referenced by StartClient(), and wxLua_wxLuaDebuggerServer_GetProgramName().
virtual wxLuaSocketBase* wxLuaDebuggerBase::GetSocketBase () [pure virtual]
Implemented in wxLuaDebuggerCServer.
Referenced by AddBreakPoint(), Break(), CheckSocketConnected(), ClearAllBreakPoints(), ClearDebugReferences(), Continue(), DisableBreakPoint(), EnableBreakPoint(), EnumerateStack(), EnumerateStackEntry(), EnumerateTable(), EvaluateExpr(), HandleDebuggeeEvent(), RemoveBreakPoint(), Reset(), Run(), Step(), StepOut(), and StepOver().
virtual wxString wxLuaDebuggerBase::GetSocketErrorMsg () [pure virtual]
Implemented in wxLuaDebuggerCServer.
Referenced by CheckSocketRead(), and CheckSocketWrite().
wxLuaStackDialog* wxLuaDebuggerBase::GetStackDialog ()
Definition at line 215 of file wxldserv.h.
Referenced by OnDebugStackEntryEnum(), OnDebugStackEnum(), and OnDebugTableEnum().
int wxLuaDebuggerBase::HandleDebuggeeEvent (int event_type) [virtual]
Definition at line 367 of file wxldserv.cpp.
References CheckSocketRead(), GetSocketBase(), SendEvent(), wxLuaDebuggerEvent::SetDebugData(), wxLuaDebuggerEvent::SetMessage(), wxLUASOCKET_DEBUGGEE_EVENT_BREAK, wxLUASOCKET_DEBUGGEE_EVENT_ERROR, wxLUASOCKET_DEBUGGEE_EVENT_EVALUATE_EXPR, wxLUASOCKET_DEBUGGEE_EVENT_EXIT, wxLUASOCKET_DEBUGGEE_EVENT_PRINT, wxLUASOCKET_DEBUGGEE_EVENT_STACK_ENTRY_ENUM, wxLUASOCKET_DEBUGGEE_EVENT_STACK_ENUM, and wxLUASOCKET_DEBUGGEE_EVENT_TABLE_ENUM.
Referenced by wxLuaDebuggerCServer::ThreadFunction().
bool wxLuaDebuggerBase::KillDebuggee ()
Definition at line 621 of file wxldserv.cpp.
References m_debuggeeProcess, m_debuggeeProcessID, and wxLuaDebuggerProcess::m_debugger.
Referenced by StartClient().
void wxLuaDebuggerBase::OnDebugStackEntryEnum (wxLuaDebuggerEvent & event)
Definition at line 586 of file wxldserv.cpp.
References wxLuaStackDialog::FillStackEntry(), wxLuaDebuggerEvent::GetReference(), and GetStackDialog().
void wxLuaDebuggerBase::OnDebugStackEnum (wxLuaDebuggerEvent & event)
Definition at line 577 of file wxldserv.cpp.
References wxLuaStackDialog::FillStackCombobox(), wxLuaDebuggerEvent::GetDebugData(), and GetStackDialog().
void wxLuaDebuggerBase::OnDebugTableEnum (wxLuaDebuggerEvent & event)
Definition at line 595 of file wxldserv.cpp.
References wxLuaStackDialog::FillTableEntry(), wxLuaDebuggerEvent::GetReference(), and GetStackDialog().
void wxLuaDebuggerBase::OnEndDebugeeProcess (wxProcessEvent & event)
Definition at line 605 of file wxldserv.cpp.
References m_debuggeeProcess, and wxLuaDebuggerEvent::SetMessage().
Referenced by wxLuaDebuggerProcess::OnTerminate().
bool wxLuaDebuggerBase::RemoveBreakPoint (const wxString & fileName, int lineNumber)
Definition at line 237 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_REMOVE_BREAKPOINT.
bool wxLuaDebuggerBase::Reset ()
Definition at line 315 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_RESET.
Referenced by wxLuaDebuggerCServer::StopServer().
bool wxLuaDebuggerBase::Run (const wxString & fileName, const wxString & buffer)
Definition at line 271 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_RUN_BUFFER.
virtual void wxLuaDebuggerBase::SendEvent (wxEvent & event) [virtual]
Definition at line 212 of file wxldserv.h.
Referenced by CheckSocketConnected(), CheckSocketRead(), CheckSocketWrite(), and HandleDebuggeeEvent().
static void wxLuaDebuggerBase::SetNetworkName (const wxString & name) [static]
Definition at line 247 of file wxldserv.h.
static void wxLuaDebuggerBase::SetProgramName (const wxString & name) [static]
Definition at line 240 of file wxldserv.h.
void wxLuaDebuggerBase::SetStackDialog (wxLuaStackDialog * stackDialog)
Definition at line 216 of file wxldserv.h.
long wxLuaDebuggerBase::StartClient () [virtual]
Reimplemented in wxLuaDebuggerCServer.
Definition at line 209 of file wxldserv.cpp.
References GetNetworkName(), GetProgramName(), ID_WXLUASOCKET_DEBUGGEE_PROCESS, KillDebuggee(), m_debuggeeProcess, m_debuggeeProcessID, m_port_number, and wxLuaDebuggerProcess.
virtual bool wxLuaDebuggerBase::StartServer () [pure virtual]
Implemented in wxLuaDebuggerCServer.
bool wxLuaDebuggerBase::Step ()
Definition at line 280 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_DEBUG_STEP.
bool wxLuaDebuggerBase::StepOut ()
Definition at line 294 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_DEBUG_STEPOUT.
bool wxLuaDebuggerBase::StepOver ()
Definition at line 287 of file wxldserv.cpp.
References CheckSocketConnected(), CheckSocketWrite(), GetSocketBase(), and wxLUASOCKET_DEBUGGER_CMD_DEBUG_STEPOVER.
virtual bool wxLuaDebuggerBase::StopServer () [pure virtual]
Implemented in wxLuaDebuggerCServer.
Friends And Related Function Documentation
friend class wxLuaDebuggerProcess [friend]
Definition at line 263 of file wxldserv.h.
Referenced by StartClient().
Member Data Documentation
wxCriticalSection wxLuaDebuggerBase::m_acceptSockCritSect
Definition at line 257 of file wxldserv.h.
Referenced by wxLuaDebuggerCServer::ThreadFunction().
wxLuaDebuggerProcess* wxLuaDebuggerBase::m_debuggeeProcess
Definition at line 254 of file wxldserv.h.
Referenced by KillDebuggee(), OnEndDebugeeProcess(), wxLuaDebuggerProcess::OnTerminate(), StartClient(), and ~wxLuaDebuggerBase().
long wxLuaDebuggerBase::m_debuggeeProcessID
Definition at line 255 of file wxldserv.h.
Referenced by KillDebuggee(), wxLuaDebuggerProcess::OnTerminate(), wxLuaDebuggerCServer::StartClient(), StartClient(), and ~wxLuaDebuggerBase().
int wxLuaDebuggerBase::m_port_number
Definition at line 252 of file wxldserv.h.
Referenced by StartClient(), wxLuaDebuggerCServer::StartServer(), and wxLuaDebuggerCServer::StopServer().
wxCriticalSection wxLuaDebuggerBase::m_processCritSect
Definition at line 258 of file wxldserv.h.
wxLuaStackDialog* wxLuaDebuggerBase::m_stackDialog
Definition at line 253 of file wxldserv.h.
Referenced by DisplayStackDialog().
wxString wxLuaDebuggerBase::sm_networkName [static]
Definition at line 261 of file wxldserv.h.
wxString wxLuaDebuggerBase::sm_programName [static]
Definition at line 260 of file wxldserv.h.
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluasocket/include/wxldserv.h
/mnt/share/devel/lua/wxLua/modules/wxluasocket/src/wxldserv.cpp