wxLua: wxLuaCharBuffer Class Reference
wxLuaCharBuffer Class Reference
#include <wxlstate.h>
Public Member Functions
wxLuaCharBuffer (const wxString &wxstr)
size_t Length () const
const char * GetData () const
operator const char * () const
Public Attributes
wxCharBuffer m_buffer
Detailed Description
Definition at line 74 of file wxlstate.h.
Constructor & Destructor Documentation
wxLuaCharBuffer::wxLuaCharBuffer (const wxString & wxstr)
Definition at line 77 of file wxlstate.h.
Member Function Documentation
const char* wxLuaCharBuffer::GetData () const
Definition at line 80 of file wxlstate.h.
Referenced by wxLuaState::CompileString(), wxLuaDebugTarget::EvaluateExpr(), wxLuaState::RunString(), and wxLuaSocketBase::WriteString().
size_t wxLuaCharBuffer::Length () const
Definition at line 79 of file wxlstate.h.
Referenced by wxLuaState::CompileString(), wxLuaDebugTarget::EvaluateExpr(), wxLuaDebugTarget::Run(), wxLuaState::RunString(), and wxLuaSocketBase::WriteString().
wxLuaCharBuffer::operator const char * () const
Definition at line 82 of file wxlstate.h.
Member Data Documentation
wxCharBuffer wxLuaCharBuffer::m_buffer
Definition at line 84 of file wxlstate.h.
The documentation for this class was generated from the following file:
/mnt/share/devel/lua/wxLua/modules/wxlua/include/wxlstate.h