wxLua: wxLuawxSocket Class Reference
wxLuawxSocket Class Reference
#include <wxlsock.h>
Public Member Functions
wxLuawxSocket ()
wxLuawxSocket (wxSocketBase *sock)
virtual ~wxLuawxSocket ()
bool Destroy ()
wxSocketBase * GetSocket () const
void SetSocket (wxSocketBase *sock)
bool Error ()
bool WaitForRead (long seconds=0, long milliseconds=300)
virtual bool IsConnected ()
virtual int Read (char *buffer, wxUint32 length)
virtual int Write (const char *buffer, wxUint32 length)
virtual wxString GetLastErrorMsg () const
Protected Attributes
wxSocketBase * m_socket
Detailed Description
Definition at line 201 of file wxlsock.h.
Constructor & Destructor Documentation
wxLuawxSocket::wxLuawxSocket ()
Definition at line 204 of file wxlsock.h.
wxLuawxSocket::wxLuawxSocket (wxSocketBase * sock)
Definition at line 205 of file wxlsock.h.
virtual wxLuawxSocket::~wxLuawxSocket () [virtual]
Definition at line 207 of file wxlsock.h.
Member Function Documentation
bool wxLuawxSocket::Destroy ()
Definition at line 641 of file wxlsock.cpp.
References m_socket.
bool wxLuawxSocket::Error ()
Definition at line 217 of file wxlsock.h.
wxString wxLuawxSocket::GetLastErrorMsg () const [virtual]
Implements wxLuaSocketBase.
Definition at line 707 of file wxlsock.cpp.
References m_socket.
Referenced by Read(), and Write().
wxSocketBase* wxLuawxSocket::GetSocket () const
Definition at line 214 of file wxlsock.h.
virtual bool wxLuawxSocket::IsConnected () [virtual]
Implements wxLuaSocketBase.
Definition at line 222 of file wxlsock.h.
Referenced by Read(), and Write().
int wxLuawxSocket::Read (char * buffer, wxUint32 length) [virtual]
Implements wxLuaSocketBase.
Definition at line 653 of file wxlsock.cpp.
References wxLuaSocketBase::AddErrorMessage(), GetLastErrorMsg(), IsConnected(), and m_socket.
void wxLuawxSocket::SetSocket (wxSocketBase * sock)
Definition at line 215 of file wxlsock.h.
bool wxLuawxSocket::WaitForRead (long seconds = 0, long milliseconds = 300)
Definition at line 219 of file wxlsock.h.
int wxLuawxSocket::Write (const char * buffer, wxUint32 length) [virtual]
Implements wxLuaSocketBase.
Definition at line 680 of file wxlsock.cpp.
References wxLuaSocketBase::AddErrorMessage(), GetLastErrorMsg(), IsConnected(), and m_socket.
Member Data Documentation
wxSocketBase* wxLuawxSocket::m_socket [protected]
Definition at line 232 of file wxlsock.h.
Referenced by Destroy(), GetLastErrorMsg(), Read(), and Write().
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxluasocket/include/wxlsock.h
/mnt/share/devel/lua/wxLua/modules/wxluasocket/src/wxlsock.cpp