wxLua: wxLuaBinding_wxlua Class Reference
wxLuaBinding_wxlua Class Reference
#include <wxlua_bind.h>
Public Member Functions
wxLuaBinding_wxlua ()
virtual bool RegisterBinding (const wxLuaState &wxlState)
Detailed Description
Definition at line 25 of file wxlua_bind.h.
Constructor & Destructor Documentation
wxLuaBinding_wxlua::wxLuaBinding_wxlua ()
Definition at line 1243 of file wxlua_bind.cpp.
References wxLuaGetClassList_wxlua(), wxLuaGetDefineList_wxlua(), wxLuaGetEventList_wxlua(), wxLuaGetFunctionList_wxlua(), wxLuaGetObjectList_wxlua(), and wxLuaGetStringList_wxlua().
Member Function Documentation
bool wxLuaBinding_wxlua::RegisterBinding (const wxLuaState & wxlState) [virtual]
Reimplemented from wxLuaBinding.
Definition at line 1255 of file wxlua_bind.cpp.
References wxLuaState::GetLuaState(), wxluaT_pushuserdatatype(), and wxluatype_NULL.
The documentation for this class was generated from the following files:
/mnt/share/devel/lua/wxLua/modules/wxlua/include/wxlua_bind.h
/mnt/share/devel/lua/wxLua/modules/wxlua/src/wxlua_bind.cpp