wxLua: /mnt/share/devel/lua/wxLua/modules/wxlua/src/wxlbind.cpp File Reference
wxlbind.cpp File Reference
#include "wx/wxprec.h"
#include "wx/wx.h"
#include "wxlua/include/wxlbind.h"
#include "wxlua/include/wxlstate.h"
#include "wx/listimpl.cpp"
Classes
class wxLuaSmartwxArrayStringRefData
class wxLuaSmartwxSortedArrayStringRefData
class wxLuaSmartwxArrayIntRefData
Functions
WX_DEFINE_LIST (wxLuaBindingList)
static int LUACALL wxlua_tableErrorHandler (lua_State *L)
int LUACALL wxlua_userdata_delete (lua_State *L)
int LUACALL wxlua_wxLuaBindClass__gc (lua_State *L)
int LUACALL wxlua_wxLuaBindClass__index (lua_State *L)
int LUACALL wxlua_wxLuaBindClass__newindex (lua_State *L)
int LUACALL wxlua_wxLuaBindClass__tostring (lua_State *L)
int LUACALL wxlua_wxLuaBindMethod_table__call (lua_State *L)
int LUACALL wxlua_wxLuaBindMethod_table__index (lua_State *L)
int LUACALL wxlua_wxLuaBindMethod_table__newindex (lua_State *L)
int LUACALL wxlua_callOverloadedFunction (lua_State *L)
int LUACALL wxlua_callOverloadedFunction (lua_State *L, struct wxLuaBindMethod *wxlMethod)
wxString wxlua_getLuaArgsMsg (lua_State *L, int start_stack_idx, int end_stack_idx)
wxString wxlua_getBindMethodArgsMsg (lua_State *L, struct wxLuaBindMethod *wxlMethod)
int wxLuaBindEventArrayCompareFn (const void *p1, const void *p2)
int wxLuaBindNumberArrayCompareFn (const void *p1, const void *p2)
int wxLuaBindStringArrayCompareFn (const void *p1, const void *p2)
int wxLuaBindObjectArrayCompareFn (const void *p1, const void *p2)
int wxLuaBindMethodArrayCompareFnInit (const void *p1, const void *p2)
int wxLuaBindMethodArrayCompareFnGet (const void *p1, const void *p2)
int wxLuaBindClassArrayCompareFn (const void *p1, const void *p2)
int wxLuaBindClassArrayCompareBywxLuaType (const void *p1, const void *p2)
static void wxLuaBinding_RecurseBaseMethods (wxLuaBindClass *wxlClass, wxLuaBindMethod *wxlMethod, bool force_update)
Variables
const wxLuaSmartwxArrayString wxLuaNullSmartwxArrayString (NULL, true)
wxLuaArgType g_wxluaargtypeArray_None [1] = {0}
wxLuaBindNumber g_wxluanumberArray_None [1] = {{0, 0}}
int wxluatype_TNONE = 1
int wxluatype_TNIL = 2
int wxluatype_TBOOLEAN = 3
int wxluatype_TLIGHTUSERDATA = 4
int wxluatype_TNUMBER = 5
int wxluatype_TSTRING = 6
int wxluatype_TTABLE = 7
int wxluatype_TFUNCTION = 8
int wxluatype_TUSERDATA = 9
int wxluatype_TTHREAD = 10
int wxluatype_TINTEGER = 11
int wxluatype_TCFUNCTION = 12
int wxluatype_NULL = 13
wxLuaBindClass wxLuaBindClass_NULL
static int wxluatype_dummy = 0
int * p_wxluatype_wxEvent = &wxluatype_dummy
int * p_wxluatype_wxWindow = &wxluatype_dummy
int * p_wxluatype_wxString = &wxluatype_dummy
int * p_wxluatype_wxArrayString = &wxluatype_dummy
int * p_wxluatype_wxSortedArrayString = &wxluatype_dummy
int * p_wxluatype_wxArrayInt = &wxluatype_dummy
Function Documentation
WX_DEFINE_LIST (wxLuaBindingList)
int LUACALL wxlua_callOverloadedFunction (lua_State * L, struct wxLuaBindMethod * wxlMethod)
Definition at line 658 of file wxlbind.cpp.
References wxLuaBindCFunc::argtypes, wxLuaBindMethod::basemethod, wxLuaBindCFunc::minargs, wxlua_error(), wxlua_getBindMethodArgsMsg(), wxlua_getLuaArgsMsg(), wxlua_iswxluatype(), WXLUA_TSTRING, wxLuaBindMethod::wxluacfuncs, wxLuaBindMethod::wxluacfuncs_n, wxluaT_isuserdatatype(), and wxluatype_NULL.
int LUACALL wxlua_callOverloadedFunction (lua_State * L)
Definition at line 647 of file wxlbind.cpp.
References wxLuaBindMethod::basemethod, wxLuaBindCFunc::lua_cfunc, wxlua_callOverloadedFunction(), wxLuaBindMethod::wxluacfuncs, and wxLuaBindMethod::wxluacfuncs_n.
Referenced by wxLuaBinding::InstallClass(), wxlua_callOverloadedFunction(), wxlua_wxLuaBindClass__index(), and wxlua_wxLuaBindMethod_table__call().
wxString wxlua_getBindMethodArgsMsg (lua_State * L, struct wxLuaBindMethod * wxlMethod)
Definition at line 816 of file wxlbind.cpp.
References wxLuaBindMethod::basemethod, wxLuaBinding::FindBindClass(), lua2wx(), wxLuaBindCFunc::maxargs, wxLuaBindCFunc::minargs, wxLuaBindMethod::name, wxLuaBindClass::name, WXLUA_HASBIT, wxLuaBindMethod::wxluacfuncs, wxLuaBindMethod::wxluacfuncs_n, WXLUAMETHOD_CFUNCTION, WXLUAMETHOD_CONSTRUCTOR, WXLUAMETHOD_STATIC, and wxluaT_typename().
Referenced by wxlua_argerrormsg(), and wxlua_callOverloadedFunction().
wxString wxlua_getLuaArgsMsg (lua_State * L, int start_stack_idx, int end_stack_idx)
Definition at line 791 of file wxlbind.cpp.
References lua2wx(), and wxluaT_gettypename().
Referenced by wxlua_argerrormsg(), and wxlua_callOverloadedFunction().
static int LUACALL wxlua_tableErrorHandler (lua_State * L) [static]
Definition at line 282 of file wxlbind.cpp.
References wxlua_error().
int LUACALL wxlua_userdata_delete (lua_State * L)
Definition at line 292 of file wxlbind.cpp.
References wxlua_argerrormsg(), WXLUA_DELETE_OBJECT_ALL, wxlua_touserdata(), and wxluaO_deletegcobject().
int LUACALL wxlua_wxLuaBindClass__gc (lua_State * L)
Definition at line 320 of file wxlbind.cpp.
References WXLUA_DELETE_OBJECT_LAST, wxlua_iswxuserdata, wxlua_touserdata(), wxluaO_deletegcobject(), wxluaT_type(), and wxLuaBindClass::wxluatype.
Referenced by wxLuaBinding::InstallClassMetatable().
int LUACALL wxlua_wxLuaBindClass__index (lua_State * L)
Definition at line 340 of file wxlbind.cpp.
References wxLuaBindMethod::basemethod, wxLuaBinding::GetClassMethod(), lua2wx(), wxLuaBindCFunc::lua_cfunc, wxLuaBindMethod::method_type, wxLuaBindClass::name, wxlua_callOverloadedFunction(), wxlua_error(), WXLUA_HASBIT, wxlua_hasderivedmethod(), wxlua_luaL_typename(), wxlua_setcallbaseclassfunction(), wxlua_touserdata(), wxLuaBindMethod::wxluacfuncs, wxLuaBindMethod::wxluacfuncs_n, WXLUAMETHOD_GETPROP, WXLUAMETHOD_METHOD, WXLUAMETHOD_STATIC, wxluaT_type(), and wxLuaBindClass::wxluatype.
Referenced by wxLuaBinding::InstallClassMetatable().
int LUACALL wxlua_wxLuaBindClass__newindex (lua_State * L)
Definition at line 459 of file wxlbind.cpp.
References wxLuaBinding::GetClassMethod(), lua2wx(), wxLuaBindCFunc::lua_cfunc, wxLuaBindMethod::method_type, wxLuaBindClass::name, wxLuaState::Ok(), wxlua_error(), WXLUA_HASBIT, wxlua_luaL_typename(), wxlua_setderivedmethod(), wxlua_touserdata(), wxLuaBindMethod::wxluacfuncs, WXLUAMETHOD_METHOD, WXLUAMETHOD_SETPROP, WXLUAMETHOD_STATIC, wxluaT_type(), and wxLuaBindClass::wxluatype.
Referenced by wxLuaBinding::InstallClassMetatable().
int LUACALL wxlua_wxLuaBindClass__tostring (lua_State * L)
Definition at line 537 of file wxlbind.cpp.
References wx2lua(), wxlua_iswxuserdatatype, wxlua_touserdata(), wxluaT_type(), and wxluaT_typename().
Referenced by wxLuaBinding::InstallClassMetatable().
int LUACALL wxlua_wxLuaBindMethod_table__call (lua_State * L)
Definition at line 567 of file wxlbind.cpp.
References wxlua_callOverloadedFunction().
Referenced by wxLuaBinding::InstallClass().
int LUACALL wxlua_wxLuaBindMethod_table__index (lua_State * L)
Definition at line 574 of file wxlbind.cpp.
References wxLuaBinding::GetClassMethod(), lua2wx(), wxLuaBindCFunc::lua_cfunc, wxLuaBindMethod::method_type, wxLuaBindClass::name, wxlua_error(), WXLUA_HASBIT, wxlua_luaL_typename(), wxLuaBindMethod::wxluacfuncs, WXLUAMETHOD_GETPROP, and WXLUAMETHOD_STATIC.
Referenced by wxLuaBinding::InstallClass().
int LUACALL wxlua_wxLuaBindMethod_table__newindex (lua_State * L)
Definition at line 609 of file wxlbind.cpp.
References wxLuaBinding::GetClassMethod(), lua2wx(), wxLuaBindCFunc::lua_cfunc, wxLuaBindMethod::method_type, wxLuaBindClass::name, wxlua_error(), WXLUA_HASBIT, wxlua_luaL_typename(), wxLuaBindMethod::wxluacfuncs, WXLUAMETHOD_SETPROP, and WXLUAMETHOD_STATIC.
Referenced by wxLuaBinding::InstallClass().
int wxLuaBindClassArrayCompareBywxLuaType (const void * p1, const void * p2)
Definition at line 946 of file wxlbind.cpp.
Referenced by wxLuaBinding::GetBindClass().
int wxLuaBindClassArrayCompareFn (const void * p1, const void * p2)
Definition at line 941 of file wxlbind.cpp.
Referenced by wxLuaBinding::GetBindClass(), and wxLuaBinding::InitBinding().
int wxLuaBindEventArrayCompareFn (const void * p1, const void * p2)
Definition at line 890 of file wxlbind.cpp.
Referenced by wxLuaBinding::GetBindEvent(), and wxLuaBinding::InitBinding().
static void wxLuaBinding_RecurseBaseMethods (wxLuaBindClass * wxlClass, wxLuaBindMethod * wxlMethod, bool force_update) [static]
Definition at line 1605 of file wxlbind.cpp.
References wxLuaBindClass::baseBindClasses, wxLuaBindClass::baseclassNames, wxLuaBindMethod::basemethod, wxLuaBinding::GetClassMethod(), wxLuaBindMethod::method_type, wxLuaBindMethod::name, WXLUA_HASBIT, WXLUAMETHOD_CHECKED_OVERLOAD, WXLUAMETHOD_DELETE, and WXLUAMETHOD_SEARCH_MASK.
Referenced by wxLuaBinding::InitAllBindings().
int wxLuaBindMethodArrayCompareFnGet (const void * p1, const void * p2)
Definition at line 925 of file wxlbind.cpp.
References WXLUAMETHOD_SEARCH_MASK.
Referenced by wxLuaBinding::GetClassMethod().
int wxLuaBindMethodArrayCompareFnInit (const void * p1, const void * p2)
Definition at line 910 of file wxlbind.cpp.
References WXLUAMETHOD_SORT_MASK.
Referenced by wxLuaBinding::InitBinding().
int wxLuaBindNumberArrayCompareFn (const void * p1, const void * p2)
Definition at line 895 of file wxlbind.cpp.
Referenced by wxLuaBinding::InitBinding().
int wxLuaBindObjectArrayCompareFn (const void * p1, const void * p2)
Definition at line 905 of file wxlbind.cpp.
Referenced by wxLuaBinding::InitBinding().
int wxLuaBindStringArrayCompareFn (const void * p1, const void * p2)
Definition at line 900 of file wxlbind.cpp.
Referenced by wxLuaBinding::InitBinding().
Variable Documentation
wxLuaArgType g_wxluaargtypeArray_None[1] = {0}
Definition at line 31 of file wxlbind.cpp.
wxLuaBindNumber g_wxluanumberArray_None[1] = {{0, 0}}
Definition at line 32 of file wxlbind.cpp.
Referenced by wxLuaGetClassList_wxlua(), and wxLuaGetClassList_wxluasocket().
int* p_wxluatype_wxArrayInt = &wxluatype_dummy
Definition at line 58 of file wxlbind.cpp.
int* p_wxluatype_wxArrayString = &wxluatype_dummy
Definition at line 56 of file wxlbind.cpp.
int* p_wxluatype_wxEvent = &wxluatype_dummy
Definition at line 53 of file wxlbind.cpp.
Referenced by wxLuaEventCallback::OnEvent().
int* p_wxluatype_wxSortedArrayString = &wxluatype_dummy
Definition at line 57 of file wxlbind.cpp.
int* p_wxluatype_wxString = &wxluatype_dummy
Definition at line 55 of file wxlbind.cpp.
Referenced by wxlua_getstringtype(), wxlua_getwxStringtype(), wxlua_iswxstringtype(), and wxluaT_isuserdatatype().
int* p_wxluatype_wxWindow = &wxluatype_dummy
Definition at line 54 of file wxlbind.cpp.
Referenced by wxluaT_pushuserdatatype().
wxLuaBindClass wxLuaBindClass_NULL
Initial value:
    { "NULL", NULL, 0, NULL, &wxluatype_NULL, NULL, NULL, g_wxluanumberArray_None, 0, }
Definition at line 49 of file wxlbind.cpp.
Referenced by wxLuaState::Create().
const wxLuaSmartwxArrayString wxLuaNullSmartwxArrayString(NULL, true)
int wxluatype_dummy = 0 [static]
Definition at line 52 of file wxlbind.cpp.
int wxluatype_NULL = 13
Definition at line 47 of file wxlbind.cpp.
Referenced by wxLuaBinding_wxlua::RegisterBinding(), wxlua_callOverloadedFunction(), wxluaT_getuserdatatype(), and wxluaT_isuserdatatype().
int wxluatype_TBOOLEAN = 3
Definition at line 36 of file wxlbind.cpp.
int wxluatype_TCFUNCTION = 12
Definition at line 45 of file wxlbind.cpp.
int wxluatype_TFUNCTION = 8
Definition at line 41 of file wxlbind.cpp.
int wxluatype_TINTEGER = 11
Definition at line 44 of file wxlbind.cpp.
int wxluatype_TLIGHTUSERDATA = 4
Definition at line 37 of file wxlbind.cpp.
int wxluatype_TNIL = 2
Definition at line 35 of file wxlbind.cpp.
int wxluatype_TNONE = 1
Definition at line 34 of file wxlbind.cpp.
int wxluatype_TNUMBER = 5
Definition at line 38 of file wxlbind.cpp.
int wxluatype_TSTRING = 6
Definition at line 39 of file wxlbind.cpp.
int wxluatype_TTABLE = 7
Definition at line 40 of file wxlbind.cpp.
int wxluatype_TTHREAD = 10
Definition at line 43 of file wxlbind.cpp.
int wxluatype_TUSERDATA = 9
Definition at line 42 of file wxlbind.cpp.