wxLua: /mnt/share/devel/lua/wxLua/modules/wxlua/include/wxlstate.h File Reference
wxlstate.h File Reference
#include "wxlua/include/wxldefs.h"
#include "wxlua/include/wxlbind.h"
#include "wx/filefn.h"
#include "wx/filename.h"
#include "wx/hashmap.h"
Classes
class wxLuaCharBuffer
class wxLuaStateData
class wxLuaStateRefData
class wxLuaState
class wxLuaEvent
Defines
#define WXLUA_USE_WXSTR_CONVCURRENT 1
#define wxlua_iswxuserdata(L, stack_idx) (lua_type((L), (stack_idx)) == LUA_TUSERDATA)
#define wxlua_isstringtype(L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TSTRING) == 1)
#define wxlua_isbooleantype(L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TBOOLEAN) == 1)
#define wxlua_isintegertype(L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TINTEGER) == 1)
#define wxlua_isnumbertype(L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TNUMBER) == 1)
#define wxLuaEventHandler(func) (wxObjectEventFunction)(wxEventFunction)(wxCommandEventFunction)(wxNotifyEventFunction)wxStaticCastEvent(wxLuaEventFunction, &func)
#define wx__DECLARE_WXLUAEVT(evt, id, fn) wx__DECLARE_EVT1(evt, id, wxLuaEventHandler(fn))
#define EVT_LUA_CREATION(id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_CREATION, id, fn)
#define EVT_LUA_PRINT(id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_PRINT, id, fn)
#define EVT_LUA_ERROR(id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_ERROR, id, fn)
#define EVT_LUA_DEBUG_HOOK(id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_DEBUG_HOOK, id, fn)
Typedefs
typedef void(wxEvtHandler::* wxLuaEventFunction)(wxLuaEvent &)
Enumerations
enum wxLuaGCObject_Flags { WXLUA_DELETE_OBJECT_LAST = 0x0000, WXLUA_DELETE_OBJECT_ALL = 0x0001 }
enum wxLuaState_Type { wxLUASTATE_GETSTATE = 1, wxLUASTATE_SETSTATE = 2, wxLUASTATE_STATICSTATE = 0x10, wxLUASTATE_OPENBINDINGS = 0x20 }
Functions
wxString lua2wx (const char *luastr)
const wxCharBuffer wx2lua (const wxString &wxstr)
void wxlua_lreg_createtable (lua_State *L, void *lightuserdata_reg_key, int narr=0, int nrec=0)
wxString wxlua_LUA_ERR_msg (int LUA_ERRx)
bool wxlua_errorinfo (lua_State *L, int status, int top, wxString *errMsg=NULL, int *line_num=NULL)
void LUACALL wxlua_error (lua_State *L, const char *errorMsg)
void LUACALL wxlua_argerror (lua_State *L, int stack_idx, const wxString &expectedType)
void LUACALL wxlua_argerrormsg (lua_State *L, const wxString &msg)
void *LUACALL wxlua_touserdata (lua_State *L, int stack_idx, bool null_ptr=false)
int LUACALL wxluaR_ref (lua_State *L, int stack_idx, void *lightuserdata_reg_key)
bool LUACALL wxluaR_unref (lua_State *L, int wxlref_idx, void *lightuserdata_reg_key)
bool LUACALL wxluaR_getref (lua_State *L, int wxlref_idx, void *lightuserdata_reg_key)
int LUACALL wxluaR_isrefed (lua_State *L, int stack_idx, void *lightuserdata_reg_key)
void LUACALL wxluaO_addgcobject (lua_State *L, wxObject *wxobj)
void LUACALL wxluaO_addgcobject (lua_State *L, void *obj_ptr, wxObject *wxobj)
bool LUACALL wxluaO_deletegcobject (lua_State *L, void *udata, void *obj_ptr, int flags)
bool LUACALL wxluaO_undeletegcobject (lua_State *L, void *obj_ptr)
bool LUACALL wxluaO_isgcobject (lua_State *L, void *obj_ptr)
wxArrayString LUACALL wxluaO_getgcobjectinfo (lua_State *L)
void LUACALL wxluaO_trackweakobject (lua_State *L, int udata_stack_idx, void *obj_ptr, int wxl_type)
int LUACALL wxluaO_untrackweakobject (lua_State *L, void *udata, void *obj_ptr)
bool LUACALL wxluaO_istrackedweakobject (lua_State *L, void *obj_ptr, int wxl_type, bool push_on_stack)
wxArrayString LUACALL wxluaO_gettrackedweakobjectinfo (lua_State *L)
void LUACALL wxluaW_addtrackedwindow (lua_State *L, wxObject *wxobj)
void LUACALL wxluaW_removetrackedwindow (lua_State *L, wxWindow *win)
bool LUACALL wxluaW_istrackedwindow (lua_State *L, wxWindow *win, bool check_parents)
wxArrayString LUACALL wxluaW_gettrackedwindowinfo (lua_State *L)
int LUACALL wxluaT_newmetatable (lua_State *L, int wxl_type)
bool LUACALL wxluaT_getmetatable (lua_State *L, int wxl_type)
bool LUACALL wxluaT_setmetatable (lua_State *L, int wxl_type)
int LUACALL wxluaT_type (lua_State *L, int stack_idx)
wxString LUACALL wxluaT_typename (lua_State *L, int wxl_type)
wxString LUACALL wxluaT_gettypename (lua_State *L, int stack_idx)
wxString LUACALL wxlua_luaL_typename (lua_State *L, int stack_idx)
int LUACALL wxluaT_gettype (lua_State *L, const char *name)
const wxLuaBindClass *LUACALL wxluaT_getclass (lua_State *L, int wxl_type)
const wxLuaBindClass *LUACALL wxluaT_getclass (lua_State *L, const char *class_name)
bool wxluaT_isuserdatatype (lua_State *L, int stack_idx, int wxl_type)
void *LUACALL wxluaT_getuserdatatype (lua_State *L, int stack_idx, int wxl_type)
bool LUACALL wxluaT_pushuserdatatype (lua_State *L, const void *obj_ptr, int wxl_type, bool track=true, bool allow_NULL=false)
int LUACALL wxluaT_isderivedtype (lua_State *L, int wxl_type, int base_wxl_type)
int LUACALL wxluaT_isderivedclass (const wxLuaBindClass *wxlClass, const wxLuaBindClass *base_wxlClass)
int LUACALL wxlua_iswxluatype (int luatype, int wxl_type, lua_State *L=NULL)
int wxlua_luatowxluatype (int luatype)
int wxlua_wxluatoluatype (int wxluatype)
bool wxlua_iswxstringtype (lua_State *L, int stack_idx)
const char *LUACALL wxlua_getstringtype (lua_State *L, int stack_idx)
wxString LUACALL wxlua_getwxStringtype (lua_State *L, int stack_idx)
bool LUACALL wxlua_getbooleantype (lua_State *L, int stack_idx)
long LUACALL wxlua_getenumtype (lua_State *L, int stack_idx)
long LUACALL wxlua_getintegertype (lua_State *L, int stack_idx)
unsigned long LUACALL wxlua_getuintegertype (lua_State *L, int stack_idx)
double LUACALL wxlua_getnumbertype (lua_State *L, int stack_idx)
const char **LUACALL wxlua_getchararray (lua_State *L, int stack_idx, int &count)
wxString *LUACALL wxlua_getwxStringarray (lua_State *L, int stack_idx, int &count)
int *LUACALL wxlua_getintarray (lua_State *L, int stack_idx, int &count)
wxLuaSmartwxArrayString LUACALL wxlua_getwxArrayString (lua_State *L, int stack_idx)
wxLuaSmartwxSortedArrayString
LUACALL wxlua_getwxSortedArrayString (lua_State *L, int stack_idx)
wxLuaSmartwxArrayInt LUACALL wxlua_getwxArrayInt (lua_State *L, int stack_idx)
int LUACALL wxlua_pushwxArrayStringtable (lua_State *L, const wxArrayString &strArray)
int LUACALL wxlua_pushwxArrayInttable (lua_State *L, const wxArrayInt &intArray)
void LUACALL wxlua_pushwxString (lua_State *L, const wxString &str)
wxString wxlua_concatwxArrayString (const wxArrayString &arr, const wxString &sep=wxT("\n"))
int wxlua_pushargs (lua_State *L, wxChar **argv, int argc, int start_n)
bool LUACALL wxlua_setderivedmethod (lua_State *L, void *obj_ptr, const char *method_name, wxLuaObject *wxlObj)
bool LUACALL wxlua_hasderivedmethod (lua_State *L, void *obj_ptr, const char *method_name, bool push_method)
bool LUACALL wxlua_removederivedmethods (lua_State *L, void *obj_ptr)
bool LUACALL wxlua_getcallbaseclassfunction (lua_State *L)
void LUACALL wxlua_setcallbaseclassfunction (lua_State *L, bool call_base)
wxEventType LUACALL wxlua_getwxeventtype (lua_State *L)
void LUACALL wxlua_setwxeventtype (lua_State *L, wxEventType evt_type)
wxLuaStateData *LUACALL wxlua_getwxluastatedata (lua_State *L)
WX_DECLARE_VOIDPTR_HASH_MAP_WITH_DECL (wxLuaState *, wxHashMapLuaState, class)
Variables
const char * wxlua_lreg_types_key
const char * wxlua_lreg_refs_key
const char * wxlua_lreg_debug_refs_key
const char * wxlua_lreg_classes_key
const char * wxlua_lreg_derivedmethods_key
const char * wxlua_lreg_wxluastate_key
const char * wxlua_lreg_wxluabindings_key
const char * wxlua_lreg_weakobjects_key
const char * wxlua_lreg_gcobjects_key
const char * wxlua_lreg_evtcallbacks_key
const char * wxlua_lreg_windestroycallbacks_key
const char * wxlua_lreg_topwindows_key
const char * wxlua_lreg_callbaseclassfunc_key
const char * wxlua_lreg_wxeventtype_key
const char * wxlua_lreg_wxluastatedata_key
const char * wxlua_lreg_regtable_key
const char * wxlua_metatable_type_key
const char * wxlua_metatable_wxluabindclass_key
wxLuaState wxNullLuaState
Define Documentation
#define EVT_LUA_CREATION (id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_CREATION, id, fn)
Definition at line 1358 of file wxlstate.h.
#define EVT_LUA_DEBUG_HOOK (id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_DEBUG_HOOK, id, fn)
Definition at line 1361 of file wxlstate.h.
#define EVT_LUA_ERROR (id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_ERROR, id, fn)
Definition at line 1360 of file wxlstate.h.
#define EVT_LUA_PRINT (id, fn) wx__DECLARE_WXLUAEVT(wxEVT_LUA_PRINT, id, fn)
Definition at line 1359 of file wxlstate.h.
#define wx__DECLARE_WXLUAEVT (evt, id, fn) wx__DECLARE_EVT1(evt, id, wxLuaEventHandler(fn))
Definition at line 1356 of file wxlstate.h.
#define wxlua_isbooleantype (L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TBOOLEAN) == 1)
Definition at line 474 of file wxlstate.h.
Referenced by wxLuaState::IsBooleanType().
#define wxlua_isintegertype (L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TINTEGER) == 1)
Definition at line 475 of file wxlstate.h.
Referenced by wxLuaState::IsIntegerType().
#define wxlua_isnumbertype (L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TNUMBER) == 1)
Definition at line 476 of file wxlstate.h.
Referenced by wxLuaState::IsNumberType(), and wxlua_getwxArrayInt().
#define wxlua_isstringtype (L, stack_idx) (wxlua_iswxluatype(lua_type(L, stack_idx), WXLUA_TSTRING) == 1)
Definition at line 473 of file wxlstate.h.
Referenced by wxLuaState::IsStringType(), wxlua_getstringtype(), and wxlua_getwxStringtype().
#define wxlua_iswxuserdata (L, stack_idx) (lua_type((L), (stack_idx)) == LUA_TUSERDATA)
Definition at line 465 of file wxlstate.h.
Referenced by wxlua_getstringtype(), wxlua_getwxArrayInt(), wxlua_getwxArrayString(), wxlua_getwxSortedArrayString(), wxlua_getwxStringtype(), wxlua_iswxstringtype(), and wxlua_wxLuaBindClass__gc().
#define WXLUA_USE_WXSTR_CONVCURRENT 1
Definition at line 30 of file wxlstate.h.
#define wxLuaEventHandler (func) (wxObjectEventFunction)(wxEventFunction)(wxCommandEventFunction)(wxNotifyEventFunction)wxStaticCastEvent(wxLuaEventFunction, &func)
Definition at line 1353 of file wxlstate.h.
Typedef Documentation
typedef void(wxEvtHandler::* wxLuaEventFunction)(wxLuaEvent &)
Definition at line 1351 of file wxlstate.h.
Enumeration Type Documentation
enum wxLuaGCObject_Flags
Enumerator:
WXLUA_DELETE_OBJECT_LAST
WXLUA_DELETE_OBJECT_ALL
Definition at line 286 of file wxlstate.h.
enum wxLuaState_Type
Enumerator:
wxLUASTATE_GETSTATE
wxLUASTATE_SETSTATE
wxLUASTATE_STATICSTATE
wxLUASTATE_OPENBINDINGS
Definition at line 660 of file wxlstate.h.
Function Documentation
wxString lua2wx (const char * luastr)
Definition at line 33 of file wxlstate.h.
Referenced by wxLuaCSocket::Connect(), wxLuaDebugTarget::DebugHook(), wxLuaDebugData::EnumerateStack(), wxLuaDebugData::EnumerateStackEntry(), wxLuaDebugTarget::EvaluateExpr(), wxLuaBinding::GetEventTypeName(), wxLuaEventCallback::GetInfo(), wxLuaCSocket::GetLastErrorMsg(), wxLuaDebugData::GetTypeValue(), wxLuaDebugData::GetUserDataInfo(), wxLuaState::lua_TowxString(), wxLuaState::lua_TypeName(), wxLuaState::lua_Version(), wxLuaState::LuaDoBuffer(), wxLuaDebugTarget::LuaPrint(), wxLuaSocketBase::ReadDebugData(), wxLuaSocketBase::ReadLong(), wxLuaSocketBase::ReadString(), wxlua_errorinfo(), wxlua_getBindMethodArgsMsg(), wxlua_getLuaArgsMsg(), wxlua_getwxStringtype(), wxlua_luaL_typename(), wxlua_printFunction(), wxlua_wxLuaBindClass__index(), wxlua_wxLuaBindClass__newindex(), wxlua_wxLuaBindMethod_table__index(), wxlua_wxLuaBindMethod_table__newindex(), wxLuaBindClassString(), wxLuaCSocket::wxLuaCSocket(), and wxluaT_typename().
const wxCharBuffer wx2lua (const wxString & wxstr)
Definition at line 56 of file wxlstate.h.
Referenced by wxLuaState::CompileBuffer(), wxLuaCSocket::Connect(), wxLuaBinding::DoRegisterBinding(), wxLuaCheckStack::DumpTable(), wxLuaObject::GetObject(), wxLuaBinding::RegisterBinding(), wxLuaDebugTarget::Run(), wxLuaState::RunBuffer(), wxLuaState::RunFile(), wxLua_function_type(), wxlua_getstringtype(), wxlua_pushargs(), wxlua_pushwxString(), wxlua_wxLuaBindClass__tostring(), and wxluabind_wxLuaBinding__index().
WX_DECLARE_VOIDPTR_HASH_MAP_WITH_DECL (wxLuaState * , wxHashMapLuaState , class)
void LUACALL wxlua_argerror (lua_State * L, int stack_idx, const wxString & expectedType)
Definition at line 298 of file wxlstate.cpp.
References wxlua_argerrormsg(), and wxlua_luaL_typename().
Referenced by wxLua_function_ungcobject(), wxlua_getbooleantype(), wxlua_getchararray(), wxlua_getenumtype(), wxlua_getintegertype(), wxlua_getnumbertype(), wxlua_getstringtype(), wxlua_getuintegertype(), wxlua_getwxArrayInt(), wxlua_getwxArrayString(), wxlua_getwxSortedArrayString(), wxlua_getwxStringtype(), and wxluaT_getuserdatatype().
void LUACALL wxlua_argerrormsg (lua_State * L, const wxString & msg)
Definition at line 308 of file wxlstate.cpp.
References wxLuaBinding::FindBindClass(), wxLuaBinding::FindMethodBinding(), wxlua_error(), wxlua_getBindMethodArgsMsg(), and wxlua_getLuaArgsMsg().
Referenced by wxlua_argerror(), and wxlua_userdata_delete().
wxString wxlua_concatwxArrayString (const wxArrayString & arr, const wxString & sep = wxT("\n"))
Definition at line 1748 of file wxlstate.cpp.
Referenced by wxLua_function_GetGCUserdataInfo(), wxLua_function_GetTrackedEventCallbackInfo(), wxLua_function_GetTrackedObjectInfo(), wxLua_function_GetTrackedWinDestroyCallbackInfo(), and wxLua_function_GetTrackedWindowInfo().
void LUACALL wxlua_error (lua_State * L, const char * errorMsg)
Definition at line 291 of file wxlstate.cpp.
Referenced by wxlua_argerrormsg(), wxlua_callOverloadedFunction(), wxlua_debugHookFunction(), wxLuaState::wxlua_Error(), wxlua_tableErrorHandler(), wxlua_wxLuaBindClass__index(), wxlua_wxLuaBindClass__newindex(), wxlua_wxLuaBindMethod_table__index(), wxlua_wxLuaBindMethod_table__newindex(), wxluaT_pushuserdatatype(), and wxluaT_setmetatable().
bool wxlua_errorinfo (lua_State * L, int status, int top, wxString * errMsg = NULL, int * line_num = NULL)
Definition at line 235 of file wxlstate.cpp.
References lua2wx(), and wxlua_LUA_ERR_msg().
Referenced by wxLuaState::CompileBuffer(), and wxLuaState::SendLuaErrorEvent().
bool LUACALL wxlua_getbooleantype (lua_State * L, int stack_idx)
Definition at line 1429 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_iswxluatype(), and WXLUA_TBOOLEAN.
Referenced by wxLuaState::GetBooleanType().
bool LUACALL wxlua_getcallbaseclassfunction (lua_State * L)
Definition at line 1915 of file wxlstate.cpp.
References wxlua_lreg_callbaseclassfunc_key.
Referenced by wxLuaState::GetCallBaseClassFunction().
const char** LUACALL wxlua_getchararray (lua_State * L, int stack_idx, int & count)
Definition at line 1520 of file wxlstate.cpp.
References wxlua_argerror(), and wxlua_getstringtype().
Referenced by wxLuaState::GetCharArray().
long LUACALL wxlua_getenumtype (lua_State * L, int stack_idx)
Definition at line 1445 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_iswxluatype(), and WXLUA_TINTEGER.
int* LUACALL wxlua_getintarray (lua_State * L, int stack_idx, int & count)
Definition at line 1564 of file wxlstate.cpp.
References wxlua_getwxArrayInt().
Referenced by wxLuaState::GetIntArray().
long LUACALL wxlua_getintegertype (lua_State * L, int stack_idx)
Definition at line 1461 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_iswxluatype(), and WXLUA_TINTEGER.
Referenced by wxLuaState::GetIntegerType().
double LUACALL wxlua_getnumbertype (lua_State * L, int stack_idx)
Definition at line 1503 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_iswxluatype(), and WXLUA_TNUMBER.
Referenced by wxLuaState::GetNumberType(), wxLua_function_iswxluatype(), wxLua_function_typename(), wxLua_function_wxLUA_CHECK_VERSION(), wxLua_function_wxLUA_CHECK_VERSION_FULL(), wxLua_wxLuaDebuggerServer_AddBreakPoint(), wxLua_wxLuaDebuggerServer_constructor(), wxLua_wxLuaDebuggerServer_DisplayStackDialog(), wxLua_wxLuaDebuggerServer_EvaluateExpr(), and wxLua_wxLuaDebuggerServer_RemoveBreakPoint().
const char* LUACALL wxlua_getstringtype (lua_State * L, int stack_idx)
Definition at line 1387 of file wxlstate.cpp.
References p_wxluatype_wxString, wx2lua(), wxlua_argerror(), wxlua_isstringtype, wxlua_iswxuserdata, wxlua_touserdata(), wxluaT_isderivedtype(), and wxluaT_type().
Referenced by wxLuaState::GetStringType(), and wxlua_getchararray().
unsigned long LUACALL wxlua_getuintegertype (lua_State * L, int stack_idx)
Definition at line 1482 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_iswxluatype(), and WXLUA_TINTEGER.
wxLuaSmartwxArrayInt LUACALL wxlua_getwxArrayInt (lua_State * L, int stack_idx)
Definition at line 1663 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_isnumbertype, wxlua_iswxuserdata, wxluaT_gettype(), wxluaT_getuserdatatype(), and wxluaT_isuserdatatype().
Referenced by wxLuaState::GetwxArrayInt(), and wxlua_getintarray().
wxLuaSmartwxArrayString LUACALL wxlua_getwxArrayString (lua_State * L, int stack_idx)
Definition at line 1578 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_getwxStringtype(), wxlua_iswxstringtype(), wxlua_iswxuserdata, wxluaT_gettype(), wxluaT_getuserdatatype(), and wxluaT_isuserdatatype().
Referenced by wxLuaState::GetwxArrayString(), wxlua_getwxSortedArrayString(), and wxlua_getwxStringarray().
wxEventType LUACALL wxlua_getwxeventtype (lua_State * L)
Definition at line 1933 of file wxlstate.cpp.
References wxlua_lreg_wxeventtype_key.
Referenced by wxLuaState::GetInEventType(), and wxlua_debugHookFunction().
wxLuaStateData* LUACALL wxlua_getwxluastatedata (lua_State * L)
Definition at line 1951 of file wxlstate.cpp.
References wxlua_lreg_wxluastatedata_key.
Referenced by wxlua_debugHookFunction().
wxLuaSmartwxSortedArrayString LUACALL wxlua_getwxSortedArrayString (lua_State * L, int stack_idx)
Definition at line 1631 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_getwxArrayString(), wxlua_iswxuserdata, wxluaT_gettype(), wxluaT_getuserdatatype(), and wxluaT_isuserdatatype().
wxString* LUACALL wxlua_getwxStringarray (lua_State * L, int stack_idx, int & count)
Definition at line 1550 of file wxlstate.cpp.
References wxlua_getwxArrayString().
Referenced by wxLuaState::GetwxStringArray().
wxString LUACALL wxlua_getwxStringtype (lua_State * L, int stack_idx)
Definition at line 1408 of file wxlstate.cpp.
References lua2wx(), p_wxluatype_wxString, wxlua_argerror(), wxlua_isstringtype, wxlua_iswxuserdata, wxlua_touserdata(), wxluaT_isderivedtype(), and wxluaT_type().
Referenced by wxLuaState::GetwxStringType(), wxLua_function_CompileLuaScript(), wxlua_getwxArrayString(), wxLua_wxLuaDebuggerServer_AddBreakPoint(), wxLua_wxLuaDebuggerServer_EvaluateExpr(), wxLua_wxLuaDebuggerServer_RemoveBreakPoint(), and wxLua_wxLuaDebuggerServer_Run().
bool LUACALL wxlua_hasderivedmethod (lua_State * L, void * obj_ptr, const char * method_name, bool push_method)
Definition at line 1833 of file wxlstate.cpp.
References wxLuaObject::GetObject(), and wxlua_lreg_derivedmethods_key.
Referenced by wxLuaState::HasDerivedMethod(), and wxlua_wxLuaBindClass__index().
int LUACALL wxlua_iswxluatype (int luatype, int wxl_type, lua_State * L = NULL)
Definition at line 1256 of file wxlstate.cpp.
References WXLUA_TBOOLEAN, WXLUA_TCFUNCTION, WXLUA_TFUNCTION, WXLUA_TINTEGER, WXLUA_TLIGHTUSERDATA, WXLUA_TNIL, WXLUA_TNONE, WXLUA_TNUMBER, WXLUA_TSTRING, WXLUA_TTABLE, WXLUA_TTHREAD, WXLUA_TUSERDATA, wxluaT_getclass(), and wxluaT_isderivedclass().
Referenced by wxLuaState::IswxLuaType(), wxlua_callOverloadedFunction(), wxLua_function_iswxluatype(), wxLua_function_ungcobject(), wxlua_getbooleantype(), wxlua_getenumtype(), wxlua_getintegertype(), wxlua_getnumbertype(), wxlua_getuintegertype(), and wxlua_iswxstringtype().
bool wxlua_iswxstringtype (lua_State * L, int stack_idx)
Definition at line 1371 of file wxlstate.cpp.
References p_wxluatype_wxString, wxlua_iswxluatype(), wxlua_iswxuserdata, WXLUA_TSTRING, wxluaT_isderivedtype(), and wxluaT_type().
Referenced by wxLuaState::IswxStringType(), and wxlua_getwxArrayString().
void wxlua_lreg_createtable (lua_State * L, void * lightuserdata_reg_key, int narr = 0, int nrec = 0)
Definition at line 186 of file wxlstate.cpp.
References wxlua_lreg_regtable_key.
Referenced by wxLuaStateRefData::ClearCallbacks(), wxLuaStateRefData::CloseLuaState(), wxLuaState::Create(), and wxLuaStackDialog::RemoveAllLuaReferences().
wxString wxlua_LUA_ERR_msg (int LUA_ERRx)
Definition at line 219 of file wxlstate.cpp.
Referenced by wxLuaDebugTarget::EvaluateExpr(), wxLuaDebugTarget::Run(), and wxlua_errorinfo().
wxString LUACALL wxlua_luaL_typename (lua_State * L, int stack_idx)
Definition at line 1038 of file wxlstate.cpp.
References lua2wx().
Referenced by wxlua_argerror(), wxlua_wxLuaBindClass__index(), wxlua_wxLuaBindClass__newindex(), wxlua_wxLuaBindMethod_table__index(), and wxlua_wxLuaBindMethod_table__newindex().
int wxlua_luatowxluatype (int luatype)
Definition at line 1324 of file wxlstate.cpp.
References WXLUA_TBOOLEAN, WXLUA_TFUNCTION, WXLUA_TLIGHTUSERDATA, WXLUA_TNIL, WXLUA_TNONE, WXLUA_TNUMBER, WXLUA_TSTRING, WXLUA_TTABLE, WXLUA_TTHREAD, WXLUA_TUNKNOWN, and WXLUA_TUSERDATA.
Referenced by wxLuaDebugData::GetTypeValue(), and wxluaT_type().
int wxlua_pushargs (lua_State * L, wxChar ** argv, int argc, int start_n)
Definition at line 1761 of file wxlstate.cpp.
References wx2lua().
int LUACALL wxlua_pushwxArrayInttable (lua_State * L, const wxArrayInt & intArray)
Definition at line 1730 of file wxlstate.cpp.
Referenced by wxLuaObject::GetObject(), and wxLuaState::PushwxArrayIntTable().
int LUACALL wxlua_pushwxArrayStringtable (lua_State * L, const wxArrayString & strArray)
Definition at line 1717 of file wxlstate.cpp.
References wxlua_pushwxString().
Referenced by wxLuaState::PushwxArrayStringTable(), wxLua_function_GetGCUserdataInfo(), wxLua_function_GetTrackedEventCallbackInfo(), wxLua_function_GetTrackedObjectInfo(), wxLua_function_GetTrackedWinDestroyCallbackInfo(), and wxLua_function_GetTrackedWindowInfo().
void LUACALL wxlua_pushwxString (lua_State * L, const wxString & str)
Definition at line 1743 of file wxlstate.cpp.
References wx2lua().
Referenced by wxLuaDebugTarget::EvaluateExpr(), wxLua_function_CompileLuaScript(), wxLua_function_GetGCUserdataInfo(), wxLua_function_GetTrackedEventCallbackInfo(), wxLua_function_GetTrackedObjectInfo(), wxLua_function_GetTrackedWinDestroyCallbackInfo(), wxLua_function_GetTrackedWindowInfo(), wxLua_function_typename(), wxlua_pushwxArrayStringtable(), wxLua_wxLuaDebuggerEvent_GetFileName(), wxLua_wxLuaDebuggerEvent_GetMessage(), wxLua_wxLuaDebuggerServer_GetNetworkName(), and wxLua_wxLuaDebuggerServer_GetProgramName().
bool LUACALL wxlua_removederivedmethods (lua_State * L, void * obj_ptr)
Definition at line 1869 of file wxlstate.cpp.
References wxlua_lreg_derivedmethods_key.
Referenced by wxLuaWinDestroyCallback::OnDestroy(), wxLuaState::RemoveDerivedMethods(), and wxluaO_deletegcobject().
void LUACALL wxlua_setcallbaseclassfunction (lua_State * L, bool call_base)
Definition at line 1926 of file wxlstate.cpp.
References wxlua_lreg_callbaseclassfunc_key.
Referenced by wxLuaState::SetCallBaseClassFunction(), and wxlua_wxLuaBindClass__index().
bool LUACALL wxlua_setderivedmethod (lua_State * L, void * obj_ptr, const char * method_name, wxLuaObject * wxlObj)
Definition at line 1788 of file wxlstate.cpp.
References wxlua_lreg_derivedmethods_key.
Referenced by wxLuaState::SetDerivedMethod(), and wxlua_wxLuaBindClass__newindex().
void LUACALL wxlua_setwxeventtype (lua_State * L, wxEventType evt_type)
Definition at line 1944 of file wxlstate.cpp.
References wxlua_lreg_wxeventtype_key.
Referenced by wxLuaState::Create(), and wxLuaState::SetInEventType().
void* LUACALL wxlua_touserdata (lua_State * L, int stack_idx, bool null_ptr = false)
Definition at line 335 of file wxlstate.cpp.
Referenced by wxLua_function_isgcobject(), wxLua_function_istrackedobject(), wxLua_function_ungcobject(), wxlua_getstringtype(), wxlua_getwxStringtype(), wxLuaState::wxlua_ToUserdata(), wxlua_userdata_delete(), wxlua_wxLuaBindClass__gc(), wxlua_wxLuaBindClass__index(), wxlua_wxLuaBindClass__newindex(), wxlua_wxLuaBindClass__tostring(), and wxluaT_getuserdatatype().
int wxlua_wxluatoluatype (int wxluatype)
Definition at line 1350 of file wxlstate.cpp.
References WXLUA_TBOOLEAN, WXLUA_TCFUNCTION, WXLUA_TFUNCTION, WXLUA_TINTEGER, WXLUA_TLIGHTUSERDATA, WXLUA_TNIL, WXLUA_TNONE, WXLUA_TNUMBER, WXLUA_TSTRING, WXLUA_TTABLE, WXLUA_TTHREAD, and WXLUA_TUSERDATA.
void LUACALL wxluaO_addgcobject (lua_State * L, void * obj_ptr, wxObject * wxobj)
Definition at line 487 of file wxlstate.cpp.
References wxlua_lreg_gcobjects_key.
void LUACALL wxluaO_addgcobject (lua_State * L, wxObject * wxobj)
Definition at line 483 of file wxlstate.cpp.
References wxluaO_addgcobject().
Referenced by wxLuaState::AddGCObject(), wxLua_wxLuaDebuggerServer_constructor(), wxLua_wxLuaObject_constructor(), and wxluaO_addgcobject().
bool LUACALL wxluaO_deletegcobject (lua_State * L, void * udata, void * obj_ptr, int flags)
Definition at line 511 of file wxlstate.cpp.
References WXLUA_DELETE_OBJECT_ALL, WXLUA_HASBIT, wxlua_lreg_gcobjects_key, wxlua_removederivedmethods(), and wxluaO_untrackweakobject().
Referenced by wxLuaState::DeleteGCObject(), wxlua_userdata_delete(), and wxlua_wxLuaBindClass__gc().
wxArrayString LUACALL wxluaO_getgcobjectinfo (lua_State * L)
Definition at line 599 of file wxlstate.cpp.
References wxlua_lreg_gcobjects_key.
Referenced by wxLuaState::GetGCObjectInfo(), and wxLua_function_GetGCUserdataInfo().
wxArrayString LUACALL wxluaO_gettrackedweakobjectinfo (lua_State * L)
Definition at line 760 of file wxlstate.cpp.
References wxlua_lreg_weakobjects_key, and wxluaT_typename().
Referenced by wxLua_function_GetTrackedObjectInfo().
bool LUACALL wxluaO_isgcobject (lua_State * L, void * obj_ptr)
Definition at line 585 of file wxlstate.cpp.
References wxlua_lreg_gcobjects_key.
Referenced by wxLuaState::IsGCObject(), wxLua_function_isgcobject(), and wxLua_function_ungcobject().
bool LUACALL wxluaO_istrackedweakobject (lua_State * L, void * obj_ptr, int wxl_type, bool push_on_stack)
Definition at line 726 of file wxlstate.cpp.
References wxlua_lreg_weakobjects_key, and wxluaT_type().
Referenced by wxLua_function_istrackedobject(), and wxluaT_pushuserdatatype().
void LUACALL wxluaO_trackweakobject (lua_State * L, int udata_stack_idx, void * obj_ptr, int wxl_type)
Definition at line 627 of file wxlstate.cpp.
References ABS_LUA_STKIDX, and wxlua_lreg_weakobjects_key.
Referenced by wxluaT_pushuserdatatype().
bool LUACALL wxluaO_undeletegcobject (lua_State * L, void * obj_ptr)
Definition at line 558 of file wxlstate.cpp.
References wxlua_lreg_gcobjects_key.
Referenced by wxLua_function_ungcobject().
int LUACALL wxluaO_untrackweakobject (lua_State * L, void * udata, void * obj_ptr)
Definition at line 667 of file wxlstate.cpp.
References wxlua_lreg_weakobjects_key.
Referenced by wxLuaWinDestroyCallback::OnDestroy(), and wxluaO_deletegcobject().
bool LUACALL wxluaR_getref (lua_State * L, int wxlref_idx, void * lightuserdata_reg_key)
Definition at line 416 of file wxlstate.cpp.
Referenced by wxLuaDebugData::EnumerateTable(), wxLuaObject::GetObject(), wxLuaState::wxluaR_GetRef(), and wxluaT_getmetatable().
int LUACALL wxluaR_isrefed (lua_State * L, int stack_idx, void * lightuserdata_reg_key)
Definition at line 437 of file wxlstate.cpp.
References ABS_LUA_STKIDX, and wxlua_lreg_debug_refs_key.
Referenced by wxLua_function_isrefed().
int LUACALL wxluaR_ref (lua_State * L, int stack_idx, void * lightuserdata_reg_key)
Definition at line 364 of file wxlstate.cpp.
References ABS_LUA_STKIDX, and wxlua_lreg_debug_refs_key.
Referenced by wxLuaDebugData::RefTable(), wxLuaBinding::RegisterBinding(), and wxLuaState::wxluaR_Ref().
bool LUACALL wxluaR_unref (lua_State * L, int wxlref_idx, void * lightuserdata_reg_key)
Definition at line 390 of file wxlstate.cpp.
References wxlua_lreg_debug_refs_key.
Referenced by wxLuaStackDialog::RemoveAllLuaReferences(), and wxLuaState::wxluaR_Unref().
const wxLuaBindClass* LUACALL wxluaT_getclass (lua_State * L, const char * class_name)
Definition at line 1071 of file wxlstate.cpp.
References wxlua_lreg_classes_key.
const wxLuaBindClass* LUACALL wxluaT_getclass (lua_State * L, int wxl_type)
Definition at line 1053 of file wxlstate.cpp.
References wxlua_metatable_wxluabindclass_key, and wxluaT_getmetatable().
Referenced by wxLuaState::GetBindClass(), wxlua_iswxluatype(), wxluabind_wxLuaBindClass__index(), wxluaT_gettype(), wxluaT_isderivedtype(), and wxluaT_typename().
bool LUACALL wxluaT_getmetatable (lua_State * L, int wxl_type)
Definition at line 928 of file wxlstate.cpp.
References wxlua_lreg_types_key, and wxluaR_getref().
Referenced by wxLuaBinding::InstallClassMetatable(), wxluaT_getclass(), wxluaT_pushuserdatatype(), and wxluaT_setmetatable().
int LUACALL wxluaT_gettype (lua_State * L, const char * name)
Definition at line 1044 of file wxlstate.cpp.
References WXLUA_TUNKNOWN, wxluaT_getclass(), and wxLuaBindClass::wxluatype.
Referenced by wxlua_getwxArrayInt(), wxlua_getwxArrayString(), and wxlua_getwxSortedArrayString().
wxString LUACALL wxluaT_gettypename (lua_State * L, int stack_idx)
Definition at line 1033 of file wxlstate.cpp.
References wxluaT_type(), and wxluaT_typename().
Referenced by wxlua_getLuaArgsMsg().
void* LUACALL wxluaT_getuserdatatype (lua_State * L, int stack_idx, int wxl_type)
Definition at line 1098 of file wxlstate.cpp.
References wxlua_argerror(), wxlua_touserdata(), wxluaT_isderivedtype(), wxluaT_type(), wxluaT_typename(), and wxluatype_NULL.
Referenced by wxLuaState::GetUserDataType(), wxlua_getwxArrayInt(), wxlua_getwxArrayString(), wxlua_getwxSortedArrayString(), wxLua_wxLuaDebuggerEvent_GetFileName(), wxLua_wxLuaDebuggerEvent_GetLineNumber(), wxLua_wxLuaDebuggerEvent_GetMessage(), wxLua_wxLuaDebuggerEvent_GetReference(), wxLua_wxLuaDebuggerServer_AddBreakPoint(), wxLua_wxLuaDebuggerServer_Break(), wxLua_wxLuaDebuggerServer_ClearAllBreakPoints(), wxLua_wxLuaDebuggerServer_Continue(), wxLua_wxLuaDebuggerServer_DisplayStackDialog(), wxLua_wxLuaDebuggerServer_EvaluateExpr(), wxLua_wxLuaDebuggerServer_GetDebuggeeProcessId(), wxLua_wxLuaDebuggerServer_KillDebuggee(), wxLua_wxLuaDebuggerServer_RemoveBreakPoint(), wxLua_wxLuaDebuggerServer_Reset(), wxLua_wxLuaDebuggerServer_Run(), wxLua_wxLuaDebuggerServer_StartClient(), wxLua_wxLuaDebuggerServer_StartServer(), wxLua_wxLuaDebuggerServer_Step(), wxLua_wxLuaDebuggerServer_StepOut(), wxLua_wxLuaDebuggerServer_StepOver(), wxLua_wxLuaDebuggerServer_StopServer(), wxLua_wxLuaObject_GetAllocationFlag(), wxLua_wxLuaObject_GetObject(), and wxLua_wxLuaObject_SetObject().
int LUACALL wxluaT_isderivedclass (const wxLuaBindClass * wxlClass, const wxLuaBindClass * base_wxlClass)
Definition at line 1243 of file wxlstate.cpp.
References wxluaT_isderivedtype_recurser(), and wxLuaBindClass::wxluatype.
Referenced by wxlua_iswxluatype().
int LUACALL wxluaT_isderivedtype (lua_State * L, int wxl_type, int base_wxl_type)
Definition at line 1228 of file wxlstate.cpp.
References wxlua_iswxuserdatatype, wxluaT_getclass(), and wxluaT_isderivedtype_recurser().
Referenced by wxLuaState::IsDerivedType(), wxlua_getstringtype(), wxlua_getwxStringtype(), wxlua_iswxstringtype(), wxluaT_getuserdatatype(), wxluaT_isuserdatatype(), and wxluaT_pushuserdatatype().
bool wxluaT_isuserdatatype (lua_State * L, int stack_idx, int wxl_type)
Definition at line 1085 of file wxlstate.cpp.
References p_wxluatype_wxString, wxlua_iswxuserdatatype, WXLUA_TSTRING, wxluaT_isderivedtype(), wxluaT_type(), and wxluatype_NULL.
Referenced by wxLuaState::IsUserDataType(), wxlua_callOverloadedFunction(), wxlua_getwxArrayInt(), wxlua_getwxArrayString(), and wxlua_getwxSortedArrayString().
int LUACALL wxluaT_newmetatable (lua_State * L, int wxl_type)
Definition at line 896 of file wxlstate.cpp.
References wxlua_lreg_types_key, wxlua_metatable_type_key, and WXLUA_TUNKNOWN.
Referenced by wxLuaBinding::InstallClassMetatable(), and wxLuaState::wxluaT_NewMetatable().
bool LUACALL wxluaT_pushuserdatatype (lua_State * L, const void * obj_ptr, int wxl_type, bool track = true, bool allow_NULL = false)
Definition at line 1112 of file wxlstate.cpp.
References wxLuaState::Ok(), p_wxluatype_wxWindow, wxlua_error(), wxlua_lreg_windestroycallbacks_key, wxluaO_istrackedweakobject(), wxluaO_trackweakobject(), wxluaT_getmetatable(), and wxluaT_isderivedtype().
Referenced by wxLuaBinding::DoRegisterBinding(), wxLuaBinding_wxlua::RegisterBinding(), wxLua_wxLuaDebuggerServer_constructor(), wxLua_wxLuaObject_constructor(), wxluabind_wxLuaBindClass__index(), wxluabind_wxLuaBinding__index(), and wxLuaState::wxluaT_PushUserDataType().
bool LUACALL wxluaT_setmetatable (lua_State * L, int wxl_type)
Definition at line 941 of file wxlstate.cpp.
References wxlua_error(), and wxluaT_getmetatable().
Referenced by wxLuaState::wxluaT_SetMetatable().
int LUACALL wxluaT_type (lua_State * L, int stack_idx)
Definition at line 960 of file wxlstate.cpp.
References wxlua_luatowxluatype(), wxlua_metatable_type_key, WXLUA_TUNKNOWN, and WXLUA_TUSERDATA.
Referenced by wxLuaDebugData::GetTableInfo(), wxLuaDebugData::GetUserDataInfo(), wxLua_function_isgcobject(), wxLua_function_istrackedobject(), wxLua_function_type(), wxlua_getstringtype(), wxlua_getwxStringtype(), wxlua_iswxstringtype(), wxlua_wxLuaBindClass__gc(), wxlua_wxLuaBindClass__index(), wxlua_wxLuaBindClass__newindex(), wxlua_wxLuaBindClass__tostring(), wxluaO_istrackedweakobject(), wxluaT_gettypename(), wxluaT_getuserdatatype(), wxluaT_isuserdatatype(), and wxLuaState::wxluaT_Type().
wxString LUACALL wxluaT_typename (lua_State * L, int wxl_type)
Definition at line 983 of file wxlstate.cpp.
References lua2wx(), wxLuaBindClass::name, WXLUA_TBOOLEAN, WXLUA_TCFUNCTION, WXLUA_TFUNCTION, WXLUA_TINTEGER, WXLUA_TLIGHTUSERDATA, WXLUA_TNIL, WXLUA_TNONE, WXLUA_TNUMBER, WXLUA_TSTRING, WXLUA_TTABLE, WXLUA_TTHREAD, WXLUA_TUNKNOWN, WXLUA_TUSERDATA, wxluaT_getclass(), and WXLUAT_IS_LUAT.
Referenced by wxLuaCheckStack::DumpStack(), wxLuaCheckStack::DumpTable(), wxLuaDebugData::EnumerateTable(), wxLuaDebugTarget::EvaluateExpr(), wxLuaDebugItem::GetKeyTypeString(), wxLuaDebugData::GetUserDataInfo(), wxLuaDebugItem::GetValueTypeString(), wxLuaState::GetwxLuaTypeName(), wxLua_function_type(), wxLua_function_typename(), wxlua_getBindMethodArgsMsg(), wxlua_wxLuaBindClass__tostring(), wxluaO_gettrackedweakobjectinfo(), wxluaT_gettypename(), and wxluaT_getuserdatatype().
void LUACALL wxluaW_addtrackedwindow (lua_State * L, wxObject * wxobj)
Definition at line 801 of file wxlstate.cpp.
References wxlua_lreg_topwindows_key, and wxluaW_istrackedwindow().
Referenced by wxLuaState::AddTrackedWindow().
wxArrayString LUACALL wxluaW_gettrackedwindowinfo (lua_State * L)
Definition at line 866 of file wxlstate.cpp.
References wxlua_lreg_topwindows_key.
Referenced by wxLuaState::GetTrackedWindowInfo(), and wxLua_function_GetTrackedWindowInfo().
bool LUACALL wxluaW_istrackedwindow (lua_State * L, wxWindow * win, bool check_parents)
Definition at line 839 of file wxlstate.cpp.
References wxlua_lreg_topwindows_key.
Referenced by wxLuaState::IsTrackedWindow(), and wxluaW_addtrackedwindow().
void LUACALL wxluaW_removetrackedwindow (lua_State * L, wxWindow * win)
Definition at line 827 of file wxlstate.cpp.
References wxlua_lreg_topwindows_key.
Referenced by wxLuaState::RemoveTrackedWindow().
Variable Documentation
const char* wxlua_lreg_callbaseclassfunc_key
Definition at line 40 of file wxlstate.cpp.
Referenced by wxLuaDebugData::GetUserDataInfo(), wxlua_getcallbaseclassfunction(), and wxlua_setcallbaseclassfunction().
const char* wxlua_lreg_classes_key
Definition at line 31 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), wxLuaBinding::InstallClassMetatable(), and wxluaT_getclass().
const char* wxlua_lreg_debug_refs_key
Definition at line 30 of file wxlstate.cpp.
Referenced by wxLuaStateRefData::CloseLuaState(), wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), wxLuaDebugTarget::HandleDebuggerCmd(), wxLuaDebugData::RefTable(), wxLuaStackDialog::RemoveAllLuaReferences(), wxluaR_isrefed(), wxluaR_ref(), and wxluaR_unref().
const char* wxlua_lreg_derivedmethods_key
Definition at line 32 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::GetUserDataInfo(), wxlua_hasderivedmethod(), wxlua_removederivedmethods(), and wxlua_setderivedmethod().
const char* wxlua_lreg_evtcallbacks_key
Definition at line 37 of file wxlstate.cpp.
Referenced by wxLuaState::AddTrackedEventCallback(), wxLuaStateRefData::ClearCallbacks(), wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaState::GetTrackedEventCallbackInfo(), wxLuaDebugData::GetUserDataInfo(), wxLuaWinDestroyCallback::OnDestroy(), and wxLuaState::RemoveTrackedEventCallback().
const char* wxlua_lreg_gcobjects_key
Definition at line 36 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), wxluaO_addgcobject(), wxluaO_deletegcobject(), wxluaO_getgcobjectinfo(), wxluaO_isgcobject(), and wxluaO_undeletegcobject().
const char* wxlua_lreg_refs_key
Definition at line 29 of file wxlstate.cpp.
Referenced by wxLuaStateRefData::CloseLuaState(), wxLuaEventCallback::Connect(), wxLuaState::Create(), wxLuaDebugTarget::EvaluateExpr(), wxLuaObject::GetObject(), wxLuaDebugData::GetUserDataInfo(), wxLuaWinDestroyCallback::OnDestroy(), wxLuaEventCallback::OnEvent(), wxLuaBinding::RegisterBinding(), wxLuaObject::SetObject(), wxLua_function_isrefed(), wxLuaObject::wxLuaObject(), wxLuaEventCallback::~wxLuaEventCallback(), and wxLuaObject::~wxLuaObject().
const char* wxlua_lreg_regtable_key
Definition at line 43 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), and wxlua_lreg_createtable().
const char* wxlua_lreg_topwindows_key
Definition at line 39 of file wxlstate.cpp.
Referenced by wxLuaStateRefData::CloseLuaState(), wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), wxLuaCleanupWindows(), wxluaW_addtrackedwindow(), wxluaW_gettrackedwindowinfo(), wxluaW_istrackedwindow(), and wxluaW_removetrackedwindow().
const char* wxlua_lreg_types_key
Definition at line 28 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), wxluaT_getmetatable(), and wxluaT_newmetatable().
const char* wxlua_lreg_weakobjects_key
Definition at line 35 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::GetUserDataInfo(), wxluaO_gettrackedweakobjectinfo(), wxluaO_istrackedweakobject(), wxluaO_trackweakobject(), and wxluaO_untrackweakobject().
const char* wxlua_lreg_windestroycallbacks_key
Definition at line 38 of file wxlstate.cpp.
Referenced by wxLuaState::AddTrackedWinDestroyCallback(), wxLuaStateRefData::ClearCallbacks(), wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaState::GetTrackedWinDestroyCallbackInfo(), wxLuaDebugData::GetUserDataInfo(), wxLuaState::RemoveTrackedWinDestroyCallback(), and wxluaT_pushuserdatatype().
const char* wxlua_lreg_wxeventtype_key
Definition at line 41 of file wxlstate.cpp.
Referenced by wxLuaDebugData::GetUserDataInfo(), wxlua_getwxeventtype(), and wxlua_setwxeventtype().
const char* wxlua_lreg_wxluabindings_key
Definition at line 34 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), and wxLuaBinding::RegisterBinding().
const char* wxlua_lreg_wxluastate_key
Definition at line 33 of file wxlstate.cpp.
Referenced by wxLuaState::Create(), wxLuaDebugData::GetUserDataInfo(), and wxLuaState::GetwxLuaState().
const char* wxlua_lreg_wxluastatedata_key
Definition at line 42 of file wxlstate.cpp.
Referenced by wxLuaStateRefData::CloseLuaState(), wxLuaState::Create(), wxLuaDebugData::GetUserDataInfo(), and wxlua_getwxluastatedata().
const char* wxlua_metatable_type_key
Definition at line 45 of file wxlstate.cpp.
Referenced by wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), wxluaT_newmetatable(), and wxluaT_type().
const char* wxlua_metatable_wxluabindclass_key
Definition at line 46 of file wxlstate.cpp.
Referenced by wxLuaDebugData::EnumerateTable(), wxLuaDebugData::GetUserDataInfo(), wxLuaBinding::InstallClassMetatable(), and wxluaT_getclass().
wxLuaState wxNullLuaState
Referenced by wxLuaState::GetDerivedMethodState(), wxLuaState::GetwxLuaState(), wxLuaObject::GetwxLuaState(), and wxLuaDebuggerStackDialog::wxLuaDebuggerStackDialog().