wxLua: /mnt/share/devel/lua/wxLua/modules/wxlua/src/wxlua_bind.cpp File Reference
wxlua_bind.cpp File Reference
#include "wx/wxprec.h"
#include "wx/wx.h"
#include "wxlua/include/wxlstate.h"
#include "wxlua/include/wxlua_bind.h"
Functions
static int LUACALL wxLua_wxLuaObject_GetAllocationFlag (lua_State *L)
static int LUACALL wxLua_wxLuaObject_GetObject (lua_State *L)
static int LUACALL wxLua_wxLuaObject_SetObject (lua_State *L)
static int LUACALL wxLua_wxLuaObject_constructor (lua_State *L)
wxLuaBindEvent * wxLuaGetEventList_wxlua (size_t &count)
wxLuaBindNumber * wxLuaGetDefineList_wxlua (size_t &count)
wxLuaBindString * wxLuaGetStringList_wxlua (size_t &count)
wxLuaBindObject * wxLuaGetObjectList_wxlua (size_t &count)
static int LUACALL wxLua_function_CompileLuaScript (lua_State *L)
int LUACALL wxluabind_wxLuaBinding__index (lua_State *L)
static int LUACALL wxLua_function_GetBindings (lua_State *L)
int LUACALL wxluabind_wxLuaBindClass__index (lua_State *L)
int LUACALL wxluabind_wxLuaBindCFunc__index (lua_State *L)
int LUACALL wxluabind_wxLuaBindMethod__index (lua_State *L)
static int LUACALL wxLua_function_GetGCUserdataInfo (lua_State *L)
static int LUACALL wxLua_function_GetTrackedEventCallbackInfo (lua_State *L)
static int LUACALL wxLua_function_GetTrackedObjectInfo (lua_State *L)
static int LUACALL wxLua_function_GetTrackedWinDestroyCallbackInfo (lua_State *L)
static int LUACALL wxLua_function_GetTrackedWindowInfo (lua_State *L)
static int LUACALL wxLua_function_isgcobject (lua_State *L)
static int LUACALL wxLua_function_isrefed (lua_State *L)
static int LUACALL wxLua_function_istrackedobject (lua_State *L)
static int LUACALL wxLua_function_iswxluatype (lua_State *L)
static int LUACALL wxLua_function_type (lua_State *L)
static int LUACALL wxLua_function_typename (lua_State *L)
static int LUACALL wxLua_function_ungcobject (lua_State *L)
static int LUACALL wxLua_function_wxLUA_CHECK_VERSION (lua_State *L)
static int LUACALL wxLua_function_wxLUA_CHECK_VERSION_FULL (lua_State *L)
wxLuaBindMethod * wxLuaGetFunctionList_wxlua (size_t &count)
wxLuaBindClass * wxLuaGetClassList_wxlua (size_t &count)
bool wxLuaBinding_wxlua_init ()
Variables
int wxluatype_wxLuaState = 0
static wxLuaArgType s_wxluatypeArray_wxLua_wxLuaState_delete [] = { &wxluatype_wxLuaState, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaState_delete [1] = {{ wxlua_userdata_delete, WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, 1, 1, s_wxluatypeArray_wxLua_wxLuaState_delete }}
wxLuaBindMethod wxLuaState_methods []
int wxLuaState_methodCount = sizeof(wxLuaState_methods)/sizeof(wxLuaBindMethod) - 1
int wxluatype_wxLuaObject = 0
static wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_GetAllocationFlag [] = { &wxluatype_wxLuaObject, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_GetAllocationFlag [1] = {{ wxLua_wxLuaObject_GetAllocationFlag, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_GetAllocationFlag }}
static wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_GetObject [] = { &wxluatype_wxLuaObject, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_GetObject [1] = {{ wxLua_wxLuaObject_GetObject, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_GetObject }}
static wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_SetObject [] = { &wxluatype_wxLuaObject, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_SetObject [1] = {{ wxLua_wxLuaObject_SetObject, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_SetObject }}
static wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_delete [] = { &wxluatype_wxLuaObject, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_delete [1] = {{ wxlua_userdata_delete, WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_delete }}
static wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_constructor [1] = {{ wxLua_wxLuaObject_constructor, WXLUAMETHOD_CONSTRUCTOR, 0, 0, g_wxluaargtypeArray_None }}
wxLuaBindMethod wxLuaObject_methods []
int wxLuaObject_methodCount = sizeof(wxLuaObject_methods)/sizeof(wxLuaBindMethod) - 1
static wxLuaArgType s_wxluatypeArray_wxLua_function_CompileLuaScript [] = { &wxluatype_TSTRING, &wxluatype_TSTRING, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_CompileLuaScript [1] = {{ wxLua_function_CompileLuaScript, WXLUAMETHOD_CFUNCTION, 2, 2, s_wxluatypeArray_wxLua_function_CompileLuaScript }}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_GetBindings [1] = {{ wxLua_function_GetBindings, WXLUAMETHOD_CFUNCTION, 0, 0, g_wxluaargtypeArray_None }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_GetGCUserdataInfo [] = { &wxluatype_TBOOLEAN, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_GetGCUserdataInfo [1] = {{ wxLua_function_GetGCUserdataInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetGCUserdataInfo }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedEventCallbackInfo [] = { &wxluatype_TBOOLEAN, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedEventCallbackInfo [1] = {{ wxLua_function_GetTrackedEventCallbackInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedEventCallbackInfo }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedObjectInfo [] = { &wxluatype_TBOOLEAN, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedObjectInfo [1] = {{ wxLua_function_GetTrackedObjectInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedObjectInfo }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedWinDestroyCallbackInfo [] = { &wxluatype_TBOOLEAN, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedWinDestroyCallbackInfo [1] = {{ wxLua_function_GetTrackedWinDestroyCallbackInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedWinDestroyCallbackInfo }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedWindowInfo [] = { &wxluatype_TBOOLEAN, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedWindowInfo [1] = {{ wxLua_function_GetTrackedWindowInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedWindowInfo }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_isgcobject [] = { &wxluatype_TLIGHTUSERDATA, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_isgcobject [1] = {{ wxLua_function_isgcobject, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_isgcobject }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_isrefed [] = { &wxluatype_TLIGHTUSERDATA, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_isrefed [1] = {{ wxLua_function_isrefed, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_isrefed }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_istrackedobject [] = { &wxluatype_TLIGHTUSERDATA, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_istrackedobject [1] = {{ wxLua_function_istrackedobject, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_istrackedobject }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_iswxluatype [] = { &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_iswxluatype [1] = {{ wxLua_function_iswxluatype, WXLUAMETHOD_CFUNCTION, 2, 2, s_wxluatypeArray_wxLua_function_iswxluatype }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_type [] = { &wxluatype_TLIGHTUSERDATA, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_type [1] = {{ wxLua_function_type, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_type }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_typename [] = { &wxluatype_TNUMBER, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_typename [1] = {{ wxLua_function_typename, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_typename }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_ungcobject [] = { &wxluatype_TLIGHTUSERDATA, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_ungcobject [1] = {{ wxLua_function_ungcobject, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_ungcobject }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION [] = { &wxluatype_TNUMBER, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_wxLUA_CHECK_VERSION [1] = {{ wxLua_function_wxLUA_CHECK_VERSION, WXLUAMETHOD_CFUNCTION, 3, 3, s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION }}
static wxLuaArgType s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION_FULL [] = { &wxluatype_TNUMBER, &wxluatype_TNUMBER, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL }
static wxLuaBindCFunc s_wxluafunc_wxLua_function_wxLUA_CHECK_VERSION_FULL [1] = {{ wxLua_function_wxLUA_CHECK_VERSION_FULL, WXLUAMETHOD_CFUNCTION, 4, 4, s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION_FULL }}
static const char * wxluaclassname_wxLuaObject = "wxLuaObject"
static const char * wxluaclassname_wxLuaState = "wxLuaState"
static const char * wxluaclassname_wxObject = "wxObject"
static const char * wxluabaseclassnames_wxLuaObject [] = { wxluaclassname_wxObject, NULL }
static wxLuaBindClass * wxluabaseclassbinds_wxLuaObject [] = { NULL }
static const char * wxluabaseclassnames_wxLuaState [] = { wxluaclassname_wxObject, NULL }
static wxLuaBindClass * wxluabaseclassbinds_wxLuaState [] = { NULL }
Function Documentation
static int LUACALL wxLua_function_CompileLuaScript (lua_State * L) [static]
Definition at line 261 of file wxlua_bind.cpp.
References wxLuaState::CompileString(), wxlua_getwxStringtype(), and wxlua_pushwxString().
static int LUACALL wxLua_function_GetBindings (lua_State * L) [static]
Definition at line 286 of file wxlua_bind.cpp.
References wxLuaBinding::GetBindingList(), and wxluabind_wxLuaBinding__index().
static int LUACALL wxLua_function_GetGCUserdataInfo (lua_State * L) [static]
Definition at line 914 of file wxlua_bind.cpp.
References wxlua_concatwxArrayString(), wxlua_pushwxArrayStringtable(), wxlua_pushwxString(), and wxluaO_getgcobjectinfo().
static int LUACALL wxLua_function_GetTrackedEventCallbackInfo (lua_State * L) [static]
Definition at line 930 of file wxlua_bind.cpp.
References wxLuaState::GetTrackedEventCallbackInfo(), wxlua_concatwxArrayString(), wxlua_pushwxArrayStringtable(), and wxlua_pushwxString().
static int LUACALL wxLua_function_GetTrackedObjectInfo (lua_State * L) [static]
Definition at line 947 of file wxlua_bind.cpp.
References wxlua_concatwxArrayString(), wxlua_pushwxArrayStringtable(), wxlua_pushwxString(), and wxluaO_gettrackedweakobjectinfo().
static int LUACALL wxLua_function_GetTrackedWinDestroyCallbackInfo (lua_State * L) [static]
Definition at line 963 of file wxlua_bind.cpp.
References wxLuaState::GetTrackedWinDestroyCallbackInfo(), wxlua_concatwxArrayString(), wxlua_pushwxArrayStringtable(), and wxlua_pushwxString().
static int LUACALL wxLua_function_GetTrackedWindowInfo (lua_State * L) [static]
Definition at line 980 of file wxlua_bind.cpp.
References wxlua_concatwxArrayString(), wxlua_pushwxArrayStringtable(), wxlua_pushwxString(), and wxluaW_gettrackedwindowinfo().
static int LUACALL wxLua_function_isgcobject (lua_State * L) [static]
Definition at line 996 of file wxlua_bind.cpp.
References wxlua_iswxuserdatatype, wxlua_touserdata(), wxluaO_isgcobject(), and wxluaT_type().
static int LUACALL wxLua_function_isrefed (lua_State * L) [static]
Definition at line 1014 of file wxlua_bind.cpp.
References wxlua_lreg_refs_key, and wxluaR_isrefed().
static int LUACALL wxLua_function_istrackedobject (lua_State * L) [static]
Definition at line 1027 of file wxlua_bind.cpp.
References wxlua_iswxuserdatatype, wxlua_touserdata(), wxluaO_istrackedweakobject(), and wxluaT_type().
static int LUACALL wxLua_function_iswxluatype (lua_State * L) [static]
Definition at line 1046 of file wxlua_bind.cpp.
References wxlua_getnumbertype(), and wxlua_iswxluatype().
static int LUACALL wxLua_function_type (lua_State * L) [static]
Definition at line 1064 of file wxlua_bind.cpp.
References wx2lua(), wxluaT_type(), and wxluaT_typename().
static int LUACALL wxLua_function_typename (lua_State * L) [static]
Definition at line 1087 of file wxlua_bind.cpp.
References wxlua_getnumbertype(), wxlua_pushwxString(), and wxluaT_typename().
static int LUACALL wxLua_function_ungcobject (lua_State * L) [static]
Definition at line 1104 of file wxlua_bind.cpp.
References wxlua_argerror(), wxlua_iswxluatype(), wxlua_touserdata(), WXLUA_TUSERDATA, wxluaO_isgcobject(), and wxluaO_undeletegcobject().
static int LUACALL wxLua_function_wxLUA_CHECK_VERSION (lua_State * L) [static]
Definition at line 1128 of file wxlua_bind.cpp.
References wxLUA_CHECK_VERSION, and wxlua_getnumbertype().
static int LUACALL wxLua_function_wxLUA_CHECK_VERSION_FULL (lua_State * L) [static]
Definition at line 1147 of file wxlua_bind.cpp.
References wxLUA_CHECK_VERSION_FULL, and wxlua_getnumbertype().
static int LUACALL wxLua_wxLuaObject_constructor (lua_State * L) [static]
Definition at line 112 of file wxlua_bind.cpp.
References wxluaO_addgcobject(), and wxluaT_pushuserdatatype().
static int LUACALL wxLua_wxLuaObject_GetAllocationFlag (lua_State * L) [static]
Definition at line 60 of file wxlua_bind.cpp.
References wxluaT_getuserdatatype().
static int LUACALL wxLua_wxLuaObject_GetObject (lua_State * L) [static]
Definition at line 77 of file wxlua_bind.cpp.
References wxluaT_getuserdatatype().
static int LUACALL wxLua_wxLuaObject_SetObject (lua_State * L) [static]
Definition at line 94 of file wxlua_bind.cpp.
References wxluaT_getuserdatatype().
int LUACALL wxluabind_wxLuaBindCFunc__index (lua_State * L)
Definition at line 322 of file wxlua_bind.cpp.
References wxLuaBindCFunc::argtypes, wxLuaBinding::GetBindClass(), wxLuaBindCFunc::lua_cfunc, wxLuaBindCFunc::maxargs, wxLuaBindCFunc::method_type, wxLuaBindCFunc::minargs, wxLuaBindClass::name, and wxluabind_wxLuaBindClass__index().
Referenced by wxluabind_wxLuaBindMethod__index().
int LUACALL wxluabind_wxLuaBindClass__index (lua_State * L)
Definition at line 505 of file wxlua_bind.cpp.
References wxLuaBindClass::baseBindClasses, wxLuaBindClass::baseclassNames, wxLuaBindClass::classInfo, wxLuaBindClass::enums, wxLuaBindClass::enums_n, wxLuaBindNumber::name, wxLuaBindClass::name, wxLuaBindNumber::value, wxluabind_wxLuaBindMethod__index(), wxLuaBindClass::wxluamethods, wxLuaBindClass::wxluamethods_n, wxluaT_getclass(), wxluaT_pushuserdatatype(), and wxLuaBindClass::wxluatype.
Referenced by wxluabind_wxLuaBindCFunc__index(), wxluabind_wxLuaBinding__index(), and wxluabind_wxLuaBindMethod__index().
int LUACALL wxluabind_wxLuaBinding__index (lua_State * L)
Definition at line 669 of file wxlua_bind.cpp.
References wxLuaBindEvent::eventType, wxLuaBinding::GetBindClass(), wxLuaBinding::GetBindingName(), wxLuaBinding::GetClassArray(), wxLuaBinding::GetClassCount(), wxLuaBinding::GetEventArray(), wxLuaBinding::GetEventCount(), wxLuaBinding::GetFunctionArray(), wxLuaBinding::GetFunctionCount(), wxLuaBinding::GetLuaNamespace(), wxLuaBinding::GetNumberArray(), wxLuaBinding::GetNumberCount(), wxLuaBinding::GetObjectArray(), wxLuaBinding::GetObjectCount(), wxLuaBinding::GetStringArray(), wxLuaBinding::GetStringCount(), wxLuaBindObject::name, wxLuaBindEvent::name, wxLuaBindString::name, wxLuaBindNumber::name, wxLuaBindObject::objPtr, wxLuaBindObject::pObjPtr, wxLuaBindString::value, wxLuaBindNumber::value, wx2lua(), wxluabind_wxLuaBindClass__index(), wxluabind_wxLuaBindMethod__index(), wxluaT_pushuserdatatype(), wxLuaBindObject::wxluatype, and wxLuaBindEvent::wxluatype.
Referenced by wxLua_function_GetBindings().
int LUACALL wxluabind_wxLuaBindMethod__index (lua_State * L)
Definition at line 403 of file wxlua_bind.cpp.
References wxLuaBindMethod::basemethod, wxLuaBinding::GetBindClass(), wxLuaBindMethod::method_type, wxLuaBindClass::name, wxLuaBindMethod::name, wxluabind_wxLuaBindCFunc__index(), wxluabind_wxLuaBindClass__index(), wxLuaBindMethod::wxluacfuncs, and wxLuaBindMethod::wxluacfuncs_n.
Referenced by wxluabind_wxLuaBindClass__index(), and wxluabind_wxLuaBinding__index().
bool wxLuaBinding_wxlua_init ()
Definition at line 1271 of file wxlua_bind.cpp.
References wxLuaBinding::GetBindingList().
wxLuaBindClass* wxLuaGetClassList_wxlua (size_t & count)
Definition at line 1223 of file wxlua_bind.cpp.
References g_wxluanumberArray_None, and wxluatype_wxLuaState.
Referenced by wxLuaBinding_wxlua::wxLuaBinding_wxlua().
wxLuaBindNumber* wxLuaGetDefineList_wxlua (size_t & count)
Definition at line 171 of file wxlua_bind.cpp.
References wxLUA_MAJOR_VERSION, wxLUA_MINOR_VERSION, wxLUA_RELEASE_NUMBER, wxLUA_SUBRELEASE_NUMBER, WXLUA_T_MAX, WXLUA_TBOOLEAN, WXLUA_TCFUNCTION, WXLUA_TFUNCTION, WXLUA_TINTEGER, WXLUA_TLIGHTUSERDATA, WXLUA_TNIL, WXLUA_TNONE, WXLUA_TNUMBER, WXLUA_TSTRING, WXLUA_TTABLE, WXLUA_TTHREAD, WXLUA_TUSERDATA, WXLUAMETHOD_CFUNCTION, WXLUAMETHOD_CHECKED_OVERLOAD, WXLUAMETHOD_CONSTRUCTOR, WXLUAMETHOD_DELETE, WXLUAMETHOD_GETPROP, WXLUAMETHOD_METHOD, WXLUAMETHOD_SETPROP, WXLUAMETHOD_STATIC, wxLUAOBJECT_ARRAYINT, wxLUAOBJECT_BOOL, wxLUAOBJECT_INT, wxLUAOBJECT_NONE, and wxLUAOBJECT_STRING.
Referenced by wxLuaBinding_wxlua::wxLuaBinding_wxlua().
wxLuaBindEvent* wxLuaGetEventList_wxlua (size_t & count)
Definition at line 156 of file wxlua_bind.cpp.
Referenced by wxLuaBinding_wxlua::wxLuaBinding_wxlua().
wxLuaBindMethod* wxLuaGetFunctionList_wxlua (size_t & count)
Definition at line 1170 of file wxlua_bind.cpp.
References WXLUAMETHOD_CFUNCTION.
Referenced by wxLuaBinding_wxlua::wxLuaBinding_wxlua().
wxLuaBindObject* wxLuaGetObjectList_wxlua (size_t & count)
Definition at line 243 of file wxlua_bind.cpp.
Referenced by wxLuaBinding_wxlua::wxLuaBinding_wxlua().
wxLuaBindString* wxLuaGetStringList_wxlua (size_t & count)
Definition at line 227 of file wxlua_bind.cpp.
References wxLUA_VERSION_STRING.
Referenced by wxLuaBinding_wxlua::wxLuaBinding_wxlua().
Variable Documentation
wxLuaBindCFunc s_wxluafunc_wxLua_function_CompileLuaScript[1] = {{ wxLua_function_CompileLuaScript, WXLUAMETHOD_CFUNCTION, 2, 2, s_wxluatypeArray_wxLua_function_CompileLuaScript }} [static]
Definition at line 279 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_GetBindings[1] = {{ wxLua_function_GetBindings, WXLUAMETHOD_CFUNCTION, 0, 0, g_wxluaargtypeArray_None }} [static]
Definition at line 909 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_GetGCUserdataInfo[1] = {{ wxLua_function_GetGCUserdataInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetGCUserdataInfo }} [static]
Definition at line 925 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedEventCallbackInfo[1] = {{ wxLua_function_GetTrackedEventCallbackInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedEventCallbackInfo }} [static]
Definition at line 942 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedObjectInfo[1] = {{ wxLua_function_GetTrackedObjectInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedObjectInfo }} [static]
Definition at line 958 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedWinDestroyCallbackInfo[1] = {{ wxLua_function_GetTrackedWinDestroyCallbackInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedWinDestroyCallbackInfo }} [static]
Definition at line 975 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_GetTrackedWindowInfo[1] = {{ wxLua_function_GetTrackedWindowInfo, WXLUAMETHOD_CFUNCTION, 0, 1, s_wxluatypeArray_wxLua_function_GetTrackedWindowInfo }} [static]
Definition at line 991 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_isgcobject[1] = {{ wxLua_function_isgcobject, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_isgcobject }} [static]
Definition at line 1009 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_isrefed[1] = {{ wxLua_function_isrefed, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_isrefed }} [static]
Definition at line 1022 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_istrackedobject[1] = {{ wxLua_function_istrackedobject, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_istrackedobject }} [static]
Definition at line 1042 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_iswxluatype[1] = {{ wxLua_function_iswxluatype, WXLUAMETHOD_CFUNCTION, 2, 2, s_wxluatypeArray_wxLua_function_iswxluatype }} [static]
Definition at line 1059 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_type[1] = {{ wxLua_function_type, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_type }} [static]
Definition at line 1082 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_typename[1] = {{ wxLua_function_typename, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_typename }} [static]
Definition at line 1099 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_ungcobject[1] = {{ wxLua_function_ungcobject, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatypeArray_wxLua_function_ungcobject }} [static]
Definition at line 1124 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_wxLUA_CHECK_VERSION[1] = {{ wxLua_function_wxLUA_CHECK_VERSION, WXLUAMETHOD_CFUNCTION, 3, 3, s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION }} [static]
Definition at line 1143 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_function_wxLUA_CHECK_VERSION_FULL[1] = {{ wxLua_function_wxLUA_CHECK_VERSION_FULL, WXLUAMETHOD_CFUNCTION, 4, 4, s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION_FULL }} [static]
Definition at line 1164 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_constructor[1] = {{ wxLua_wxLuaObject_constructor, WXLUAMETHOD_CONSTRUCTOR, 0, 0, g_wxluaargtypeArray_None }} [static]
Definition at line 109 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_delete[1] = {{ wxlua_userdata_delete, WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_delete }} [static]
Definition at line 106 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_GetAllocationFlag[1] = {{ wxLua_wxLuaObject_GetAllocationFlag, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_GetAllocationFlag }} [static]
Definition at line 58 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_GetObject[1] = {{ wxLua_wxLuaObject_GetObject, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_GetObject }} [static]
Definition at line 74 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaObject_SetObject[1] = {{ wxLua_wxLuaObject_SetObject, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_wxLuaObject_SetObject }} [static]
Definition at line 91 of file wxlua_bind.cpp.
wxLuaBindCFunc s_wxluafunc_wxLua_wxLuaState_delete[1] = {{ wxlua_userdata_delete, WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, 1, 1, s_wxluatypeArray_wxLua_wxLuaState_delete }} [static]
Definition at line 36 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_CompileLuaScript[] = { &wxluatype_TSTRING, &wxluatype_TSTRING, NULL } [static]
Definition at line 258 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_GetGCUserdataInfo[] = { &wxluatype_TBOOLEAN, NULL } [static]
Definition at line 911 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedEventCallbackInfo[] = { &wxluatype_TBOOLEAN, NULL } [static]
Definition at line 927 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedObjectInfo[] = { &wxluatype_TBOOLEAN, NULL } [static]
Definition at line 944 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedWinDestroyCallbackInfo[] = { &wxluatype_TBOOLEAN, NULL } [static]
Definition at line 960 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_GetTrackedWindowInfo[] = { &wxluatype_TBOOLEAN, NULL } [static]
Definition at line 977 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_isgcobject[] = { &wxluatype_TLIGHTUSERDATA, NULL } [static]
Definition at line 993 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_isrefed[] = { &wxluatype_TLIGHTUSERDATA, NULL } [static]
Definition at line 1011 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_istrackedobject[] = { &wxluatype_TLIGHTUSERDATA, NULL } [static]
Definition at line 1024 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_iswxluatype[] = { &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL } [static]
Definition at line 1044 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_type[] = { &wxluatype_TLIGHTUSERDATA, NULL } [static]
Definition at line 1061 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_typename[] = { &wxluatype_TNUMBER, NULL } [static]
Definition at line 1084 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_ungcobject[] = { &wxluatype_TLIGHTUSERDATA, NULL } [static]
Definition at line 1101 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION[] = { &wxluatype_TNUMBER, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL } [static]
Definition at line 1126 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_function_wxLUA_CHECK_VERSION_FULL[] = { &wxluatype_TNUMBER, &wxluatype_TNUMBER, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL } [static]
Definition at line 1145 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_delete[] = { &wxluatype_wxLuaObject, NULL } [static]
Definition at line 105 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_GetAllocationFlag[] = { &wxluatype_wxLuaObject, NULL } [static]
Definition at line 56 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_GetObject[] = { &wxluatype_wxLuaObject, NULL } [static]
Definition at line 72 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_wxLuaObject_SetObject[] = { &wxluatype_wxLuaObject, NULL } [static]
Definition at line 89 of file wxlua_bind.cpp.
wxLuaArgType s_wxluatypeArray_wxLua_wxLuaState_delete[] = { &wxluatype_wxLuaState, NULL } [static]
Definition at line 35 of file wxlua_bind.cpp.
wxLuaBindClass* wxluabaseclassbinds_wxLuaObject[] = { NULL } [static]
Definition at line 1208 of file wxlua_bind.cpp.
wxLuaBindClass* wxluabaseclassbinds_wxLuaState[] = { NULL } [static]
Definition at line 1210 of file wxlua_bind.cpp.
const char* wxluabaseclassnames_wxLuaObject[] = { wxluaclassname_wxObject, NULL } [static]
Definition at line 1207 of file wxlua_bind.cpp.
const char* wxluabaseclassnames_wxLuaState[] = { wxluaclassname_wxObject, NULL } [static]
Definition at line 1209 of file wxlua_bind.cpp.
const char* wxluaclassname_wxLuaObject = "wxLuaObject" [static]
Definition at line 1203 of file wxlua_bind.cpp.
const char* wxluaclassname_wxLuaState = "wxLuaState" [static]
Definition at line 1204 of file wxlua_bind.cpp.
const char* wxluaclassname_wxObject = "wxObject" [static]
Definition at line 1205 of file wxlua_bind.cpp.
int wxLuaObject_methodCount = sizeof(wxLuaObject_methods)/sizeof(wxLuaBindMethod) - 1
Definition at line 140 of file wxlua_bind.cpp.
wxLuaBindMethod wxLuaObject_methods
Initial value:
 {
    { "GetAllocationFlag", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxLuaObject_GetAllocationFlag, 1, NULL },
    { "GetObject", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxLuaObject_GetObject, 1, NULL },
    { "SetObject", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxLuaObject_SetObject, 1, NULL },
    { "delete", WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, s_wxluafunc_wxLua_wxLuaObject_delete, 1, NULL },
    { "wxLuaObject", WXLUAMETHOD_CONSTRUCTOR, s_wxluafunc_wxLua_wxLuaObject_constructor, 1, NULL },
    { 0, 0, 0, 0 },
}
Definition at line 131 of file wxlua_bind.cpp.
int wxLuaState_methodCount = sizeof(wxLuaState_methods)/sizeof(wxLuaBindMethod) - 1
Definition at line 46 of file wxlua_bind.cpp.
wxLuaBindMethod wxLuaState_methods
Initial value:
 {
    { "delete", WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, s_wxluafunc_wxLua_wxLuaState_delete, 1, NULL },
    { 0, 0, 0, 0 },
}
Definition at line 41 of file wxlua_bind.cpp.
int wxluatype_wxLuaObject = 0
Definition at line 54 of file wxlua_bind.cpp.
int wxluatype_wxLuaState = 0
Definition at line 33 of file wxlua_bind.cpp.
Referenced by wxLuaGetClassList_wxlua().